package com.sige.gui;

import java.util.List;
import java.util.Map;

import com.sige.entidad.Dependencia;
import com.sige.gui.ui.NumberField;
import com.sige.servicio.DependenciaServicio;
import com.sige.servicio.UtilService;
import com.sige.util.Boton;
import com.sige.util.Busqueda;
import com.sige.util.Constantes;
import com.sige.util.Injector;
import com.sige.util.TextField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.event.ShortcutListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.vaadin.ui.themes.Reindeer;

public class DependenciaBuscar extends CustomComponent implements ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,10","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnBuscar;
	@AutoGenerated
	private Label lblPiso;
	@AutoGenerated
	private Label lblNomenclatura;
	@AutoGenerated
	private Label lblNombre;
	@AutoGenerated
	private NumberField txtBuscarPiso;
	@AutoGenerated
	private TextField txtBuscarNomeclatura;
	@AutoGenerated
	private TextField txtBuscarNombre;
	@AutoGenerated
	private Label lblTotalPaginas;
	@AutoGenerated
	private Label lblSeparador;
	@AutoGenerated
	private NumberField txtPaginaActual;
	@AutoGenerated
	private Label lblPagina;
	@AutoGenerated
	private Boton btnFin;
	@AutoGenerated
	private Boton btnSiguiente;
	@AutoGenerated
	private Boton btnAtras;
	@AutoGenerated
	private Boton btnInicio;
	@AutoGenerated
	private Table tblDependencias;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DependenciaServicio dependenciaServicio;

	private Window windowContiene;

	private CustomComponent quienLlama;
	private UtilService utilService;
	private Map<String, Integer> columnLenghts;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public DependenciaBuscar(Window windowContiene, CustomComponent quienLlama) {
		utilService = Injector.obtenerServicio(UtilService.class);
		dependenciaServicio = Injector
				.obtenerServicio(DependenciaServicio.class);
		this.quienLlama = quienLlama;
		this.windowContiene = windowContiene;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		postBuid();
		getAllDependencias();

		// TODO add user code here
	}

	@SuppressWarnings("deprecation")
	private void postBuid() {
		columnLenghts = utilService.getLengthColumns("dependencias");
		this.btnBuscar.addClickListener((ClickListener) this);
		this.btnInicio.addClickListener((ClickListener) this);
		this.btnAtras.addClickListener((ClickListener) this);
		this.btnSiguiente.addClickListener((ClickListener) this);
		this.btnFin.addClickListener((ClickListener) this);
		this.btnInicio.setStyleName(Reindeer.BUTTON_LINK);
		this.btnAtras.setStyleName(Reindeer.BUTTON_LINK);
		this.btnSiguiente.setStyleName(Reindeer.BUTTON_LINK);
		this.btnFin.setStyleName(Reindeer.BUTTON_LINK);
		this.btnBuscar.setStyleName("buscar");
		this.txtPaginaActual.setValue("1");

		this.txtPaginaActual.setId("paginaActual");
		this.txtBuscarNombre.setId("buscarNombres");
		this.txtBuscarNombre.setImmediate(true);
		this.txtBuscarNomeclatura.setId("buscarNomeclatura");
		this.txtBuscarPiso.setId("buscarPiso");
		this.txtBuscarNombre.setMaxLength(columnLenghts.get("nombre"));
		this.txtBuscarNomeclatura.setMaxLength(columnLenghts
				.get("nomenclatura"));
		IndexedContainer container = new IndexedContainer();
		container.addContainerProperty("id", Long.class, null);
		container.addContainerProperty("item", Long.class, null);
		container.addContainerProperty("nombre", String.class, null);
		container.addContainerProperty("nomeclatura", String.class, null);
		container.addContainerProperty("piso", Integer.class, null);
		tblDependencias.setContainerDataSource(container);
		tblDependencias.setVisibleColumns(new Object[] { "item", "nombre",
				"nomeclatura", "piso" });
		tblDependencias.setColumnWidth("item", 25);
		tblDependencias.setColumnWidth("nombre", 370);
		tblDependencias.setColumnWidth("nomeclatura", 105);
		tblDependencias.setColumnWidth("piso", 30);

		tblDependencias.setColumnHeader("item", "Item");
		tblDependencias.setColumnHeader("nomeclatura", "Nomeclatura");
		tblDependencias.setColumnHeader("nombre", "Nombre");
		tblDependencias.setColumnHeader("piso", "Piso");
		tblDependencias.setSelectable(true);
		tblDependencias.setImmediate(true);

		this.txtPaginaActual.setImmediate(true);
		this.tblDependencias.addListener(new ItemClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void itemClick(ItemClickEvent event) {
				if (event.isDoubleClick()) {
					Item item = tblDependencias.getItem(event.getItemId());
					respuesta(new Long(item.getItemProperty("id").getValue()
							.toString()));
				}
			}
		});

		this.txtPaginaActual.addShortcutListener(new ShortcutListener("",
				KeyCode.ENTER, null) {
			private static final long serialVersionUID = 1L;

			@Override
			public void handleAction(Object sender, Object target) {
				if (target instanceof TextField
						&& ((TextField) target).getId().equals("paginaActual")) {
					Long paginaActual = null;
					try {
						paginaActual = Long.parseLong(txtPaginaActual
								.getValue().toString());
					} catch (Exception exception) {
						paginaActual = 1L;
					}
					txtPaginaActual.setValue(paginaActual.toString());
					getAllDependencias();
				}
			}
		});

		this.txtBuscarNombre.addShortcutListener(new ShortcutListener("",
				KeyCode.ENTER, null) {

			private static final long serialVersionUID = 1L;

			@Override
			public void handleAction(Object sender, Object target) {
				// TODO Auto-generated method stub
				if (target instanceof TextField
						&& ((TextField) target).getId().equals("buscarNombres")) {
					txtPaginaActual.setValue("1");
					getAllDependencias();

				}
			}
		});

		txtBuscarNomeclatura.addShortcutListener(new ShortcutListener("",
				KeyCode.ENTER, null) {
			private static final long serialVersionUID = 1L;

			@Override
			public void handleAction(Object sender, Object target) {
				// TODO Auto-generated method stub
				if (target instanceof TextField
						&& ((TextField) target).getId().equals(
								"buscarNomeclatura")) {
					txtPaginaActual.setValue("1");
					getAllDependencias();
				}
			}
		});

		txtBuscarPiso.addShortcutListener(new ShortcutListener("",
				KeyCode.ENTER, null) {
			private static final long serialVersionUID = 1L;

			@Override
			public void handleAction(Object sender, Object target) {
				// TODO Auto-generated method stub
				if (target instanceof TextField
						&& ((TextField) target).getId().equals("buscarPiso")) {
					txtPaginaActual.setValue("1");
					getAllDependencias();
				}
			}
		});

		this.txtBuscarNombre.setImmediate(true);
		this.txtBuscarNombre.addTextChangeListener(new TextChangeListener() {

			@Override
			public void textChange(TextChangeEvent event) {
				// TODO Auto-generated method stub
				txtPaginaActual.setValue("1");
				txtBuscarNombre.setValue(event.getText());
				getAllDependencias();
			}
		});

		this.txtBuscarNomeclatura.setImmediate(true);
		this.txtBuscarNomeclatura
				.addTextChangeListener(new TextChangeListener() {

					@Override
					public void textChange(TextChangeEvent event) {
						// TODO Auto-generated method stub
						txtPaginaActual.setValue("1");
						txtBuscarNomeclatura.setValue(event.getText());
						getAllDependencias();
					}
				});

		this.txtBuscarPiso.setImmediate(true);
		this.txtBuscarPiso.addTextChangeListener(new TextChangeListener() {

			@Override
			public void textChange(TextChangeEvent event) {
				// TODO Auto-generated method stub
				txtPaginaActual.setValue("1");
				txtBuscarPiso.setValue(event.getText());
				getAllDependencias();
			}
		});

	}

	@SuppressWarnings("unchecked")
	private void getAllDependencias() {
		IndexedContainer container = (IndexedContainer) tblDependencias.getContainerDataSource();
		container.removeAllItems();

		List<Dependencia> dependenciasListado = null;
		Long paginaActual = Long.parseLong(this.txtPaginaActual.getValue().toString());
		Dependencia dependenciaBuscar = new Dependencia();
		dependenciaBuscar.setNombre(this.txtBuscarNombre.getValue().toString());
		dependenciaBuscar.setNomenclatura(this.txtBuscarNomeclatura.getValue().toString());
		if (this.txtBuscarPiso.getValue().toString().length() > 0) {
			dependenciaBuscar.setPiso(new Integer(this.txtBuscarPiso.getValue().toString()));
		} else {
			dependenciaBuscar.setPiso(-1);
		}
		Busqueda busqueda = dependenciaServicio.buscarPorDependencia(dependenciaBuscar, paginaActual);
		
		dependenciasListado = (List<Dependencia>) busqueda.getRegistos();
		this.lblTotalPaginas.setValue(busqueda.getNumeroPaginas().toString());
		this.txtPaginaActual.setValue(busqueda.getPaginaActual().toString());

		Long numeroItem = (Long.parseLong(this.txtPaginaActual.getValue().toString()) - 1) * Constantes.PAGINACION.DEPENDENCIA + 1;
		for (int i = 0; i < dependenciasListado.size(); i++) {
			Item item = container.addItem(i);
			item.getItemProperty("id").setValue(dependenciasListado.get(i).getId());
			item.getItemProperty("item").setValue(numeroItem++);
			item.getItemProperty("nomeclatura").setValue(dependenciasListado.get(i).getNomenclatura());
			item.getItemProperty("nombre").setValue(dependenciasListado.get(i).getNombre());
			item.getItemProperty("piso").setValue(dependenciasListado.get(i).getPiso());
		}
	}

	private void respuesta(Long dependenciaId) {
		if (quienLlama instanceof DependenciasMantenimiento) {
			DependenciasMantenimiento panel = (DependenciasMantenimiento) quienLlama;
			panel.obtenerDependenciaSuperior(dependenciaId);
		} else if (quienLlama instanceof TipoTramiteMantenimiento) {
			TipoTramiteMantenimiento panel = (TipoTramiteMantenimiento) quienLlama;
			panel.obtenerDependencia(dependenciaId);
		} else if (quienLlama instanceof ExpedienteMantenimiento) {
			ExpedienteMantenimiento panel = (ExpedienteMantenimiento) quienLlama;
			panel.obtenerDependencia(dependenciaId);
		} else if (quienLlama instanceof ModificarDocumentoProceso) {
			ModificarDocumentoProceso panel = (ModificarDocumentoProceso) quienLlama;
			panel.obtenerDependencia(dependenciaId);
		} else if (quienLlama instanceof ExpedienteConsulta) {
			ExpedienteConsulta panel = (ExpedienteConsulta) quienLlama;
			panel.obtenerDependencia(dependenciaId);
		} else if (quienLlama instanceof ImprimirCargosProceso) {
			ImprimirCargosProceso panel = (ImprimirCargosProceso) quienLlama;
			panel.obtenerDependencia(dependenciaId);
		}
		UI.getCurrent().removeWindow(windowContiene);
	}

	@Override
	public void buttonClick(ClickEvent event) {
		if (event.getSource() == this.btnBuscar) {
			this.txtPaginaActual.setValue("1");
			getAllDependencias();
		} else {
			if (event.getSource() == this.btnSiguiente) {
				Long paginaActual = Long.parseLong(this.txtPaginaActual
						.getValue().toString()) + 1;
				if (paginaActual <= Long.parseLong(this.lblTotalPaginas
						.getValue().toString())) {
					this.txtPaginaActual.setValue(paginaActual.toString());
				}
				getAllDependencias();
			} else {
				if (event.getSource() == this.btnAtras) {
					Long paginaActual = Long.parseLong(this.txtPaginaActual
							.getValue().toString()) - 1;
					if (paginaActual >= 1) {
						this.txtPaginaActual.setValue(paginaActual.toString());
					}
					getAllDependencias();
				} else {
					if (event.getSource() == this.btnInicio) {
						this.txtPaginaActual.setValue("1");
						getAllDependencias();
					} else {
						if (event.getSource() == this.btnFin) {
							this.txtPaginaActual.setValue(this.lblTotalPaginas
									.getValue());
							getAllDependencias();
						}
					}
				}
			}
		}

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// tblDependencias
		tblDependencias = new Table();
		tblDependencias.setImmediate(false);
		tblDependencias.setWidth("600px");
		tblDependencias.setHeight("225px");
		mainLayout.addComponent(tblDependencias, "top:80.0px;left:20.0px;");

		// btnInicio
		btnInicio = new Boton();
		btnInicio.setIcon(new ThemeResource("images/botones/start.png"));
		btnInicio.setImmediate(false);
		btnInicio.setWidth("28px");
		btnInicio.setHeight("24px");
		mainLayout.addComponent(btnInicio, "top:308.0px;left:191.0px;");

		// btnAtras
		btnAtras = new Boton();
		btnAtras.setIcon(new ThemeResource("images/botones/previous.png"));
		btnAtras.setImmediate(false);
		btnAtras.setWidth("28px");
		btnAtras.setHeight("24px");
		mainLayout.addComponent(btnAtras, "top:308.0px;left:217.0px;");

		// btnSiguiente
		btnSiguiente = new Boton();
		btnSiguiente.setIcon(new ThemeResource("images/botones/next.png"));
		btnSiguiente.setImmediate(false);
		btnSiguiente.setWidth("28px");
		btnSiguiente.setHeight("24px");
		mainLayout.addComponent(btnSiguiente, "top:308.0px;left:380.0px;");

		// btnFin
		btnFin = new Boton();
		btnFin.setIcon(new ThemeResource("images/botones/final.png"));
		btnFin.setImmediate(false);
		btnFin.setWidth("28px");
		btnFin.setHeight("24px");
		mainLayout.addComponent(btnFin, "top:308.0px;left:408.0px;");

		// lblPagina
		lblPagina = new Label();
		lblPagina.setImmediate(false);
		lblPagina.setWidth("-1px");
		lblPagina.setHeight("-1px");
		lblPagina.setValue("Página");
		mainLayout.addComponent(lblPagina, "top:311.0px;left:254.0px;");

		// txtPaginaActual
		txtPaginaActual = new NumberField();
		txtPaginaActual.setImmediate(false);
		txtPaginaActual.setWidth("30px");
		txtPaginaActual.setHeight("-1px");
		mainLayout.addComponent(txtPaginaActual, "top:308.0px;left:302.0px;");

		// lblSeparador
		lblSeparador = new Label();
		lblSeparador.setImmediate(false);
		lblSeparador.setWidth("-1px");
		lblSeparador.setHeight("-1px");
		lblSeparador.setValue("/");
		mainLayout.addComponent(lblSeparador, "top:311.0px;left:339.0px;");

		// lblTotalPaginas
		lblTotalPaginas = new Label();
		lblTotalPaginas.setImmediate(false);
		lblTotalPaginas.setWidth("-1px");
		lblTotalPaginas.setHeight("-1px");
		lblTotalPaginas.setValue("0");
		mainLayout.addComponent(lblTotalPaginas, "top:310.0px;left:345.0px;");

		// txtBuscarNombre
		txtBuscarNombre = new TextField();
		txtBuscarNombre.setImmediate(false);
		txtBuscarNombre.setWidth("529px");
		txtBuscarNombre.setHeight("-1px");
		mainLayout.addComponent(txtBuscarNombre, "top:12.0px;left:71.0px;");

		// txtBuscarNomeclatura
		txtBuscarNomeclatura = new TextField();
		txtBuscarNomeclatura.setImmediate(false);
		txtBuscarNomeclatura.setWidth("135px");
		txtBuscarNomeclatura.setHeight("-1px");
		mainLayout.addComponent(txtBuscarNomeclatura,
				"top:44.0px;left:100.0px;");

		// txtBuscarPiso
		txtBuscarPiso = new NumberField();
		txtBuscarPiso.setImmediate(false);
		txtBuscarPiso.setWidth("46px");
		txtBuscarPiso.setHeight("-1px");
		mainLayout.addComponent(txtBuscarPiso, "top:44.0px;left:394.0px;");

		// lblNombre
		lblNombre = new Label();
		lblNombre.setImmediate(false);
		lblNombre.setWidth("-1px");
		lblNombre.setHeight("-1px");
		lblNombre.setValue("Nombre");
		mainLayout.addComponent(lblNombre, "top:16.0px;left:20.0px;");

		// lblNomenclatura
		lblNomenclatura = new Label();
		lblNomenclatura.setImmediate(false);
		lblNomenclatura.setWidth("-1px");
		lblNomenclatura.setHeight("-1px");
		lblNomenclatura.setValue("Nomenclatura");
		mainLayout.addComponent(lblNomenclatura, "top:46.0px;left:20.0px;");

		// lblPiso
		lblPiso = new Label();
		lblPiso.setImmediate(false);
		lblPiso.setWidth("-1px");
		lblPiso.setHeight("-1px");
		lblPiso.setValue("Piso");
		mainLayout.addComponent(lblPiso, "top:46.0px;left:369.0px;");

		// btnBuscar
		btnBuscar = new Button();
		btnBuscar.setCaption("Buscar");
		btnBuscar.setIcon(new ThemeResource("images/botones/find.png"));
		btnBuscar.setImmediate(true);
		btnBuscar.setWidth("100px");
		btnBuscar.setHeight("-1px");
		mainLayout.addComponent(btnBuscar, "top:44.0px;left:500.0px;");

		return mainLayout;
	}

}
