package com.sige.gui;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.vaadin.dialogs.ConfirmDialog;

import com.sige.entidad.Lugar;
import com.sige.entidad.TipoLugar;
import com.sige.gui.ui.NumberField;
import com.sige.servicio.LugarServicio;
import com.sige.servicio.TipoLugarServicio;
import com.sige.servicio.UtilService;
import com.sige.util.Constantes;
import com.sige.util.Injector;
import com.sige.util.Notificacion;
import com.sige.util.Permiso;
import com.sige.util.SigeUtil;
import com.sige.util.TextField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;

public class LugarMantenimiento extends CustomComponent implements
		ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private NumberField txtCodigoTipoLugar;
	@AutoGenerated
	private Button btnImprimir;
	@AutoGenerated
	private Button btnBuscar;
	@AutoGenerated
	private Button btnCancelar;
	@AutoGenerated
	private Button btnEliminar;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private Button btnNuevo;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private ComboBox cbxTipoLugar;
	@AutoGenerated
	private ComboBox cbxProvincia;
	@AutoGenerated
	private ComboBox cbxDistrito;
	@AutoGenerated
	private ComboBox cbxDepartamento;
	@AutoGenerated
	private Label lblNombre;
	@AutoGenerated
	private Label lblTipoLugar;
	@AutoGenerated
	private Label lblDistrito;
	@AutoGenerated
	private Label lblProvincia;
	@AutoGenerated
	private Label lblDepartamento;
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	private boolean flagEsNuevo;
	private Boolean esProvincia;
	private Boolean esDistrito;
	private LugarServicio lugarServicio;
	private CustomComponent quienLlama;
	private Permiso permiso;
	private Lugar lugar;
	private TipoLugarServicio tipoLugarServicio;
	private UtilService utilService;
	private Map<String, Integer> columnLenghts;
	private Window windowContiene;
	private boolean confirmacion = false;

	public LugarMantenimiento(Window windowContiene,
			CustomComponent quienLlama, Permiso permiso) {
		lugarServicio = Injector.obtenerServicio(LugarServicio.class);
		utilService = Injector.obtenerServicio(UtilService.class);
		tipoLugarServicio = Injector.obtenerServicio(TipoLugarServicio.class);
		this.quienLlama = quienLlama;
		this.permiso = permiso;
		this.windowContiene = windowContiene;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		postBuid();
		llenarCombos();
		resetearFormulario();
		// TODO add user code here
	}

	private void llenarCombos() {
		List<Lugar> lugares = lugarServicio.getAllDepartamentos();
		llenarCombo(cbxDepartamento, lugares);
		if (!lugares.isEmpty()) {
			String codigo = lugarServicio.getDepartamento().trim();
			cbxDepartamento.setValue(codigo);
			llenarProvincias(codigo.substring(0, 2));
		}
		List<TipoLugar> tipoLugares = tipoLugarServicio.obtenerTodos();
		for (TipoLugar tipoLugar : tipoLugares) {
			cbxTipoLugar.addItem(tipoLugar.getId());
			cbxTipoLugar.setItemCaption(tipoLugar.getId(),
					tipoLugar.getNombre());
		}

	}

	private void llenarProvincias(String idDepartamento) {
		List<Lugar> lugares = lugarServicio.getAllProvincias(idDepartamento);
		llenarCombo(cbxProvincia, lugares);
		cbxProvincia.setValue(lugarServicio.getProvincia());
		String codProvincia = lugarServicio.getProvincia();
		codProvincia = codProvincia.substring(2, 4);
		llenarDistrito(idDepartamento, codProvincia);
	}

	private void llenarDistrito(String idDepartamento, String idProvincia) {
		List<Lugar> lugares = lugarServicio.getAllDistritos(idDepartamento,
				idProvincia);
		llenarCombo(cbxDistrito, lugares);
		cbxDistrito.setValue(lugarServicio.getDistrito());
	}

	private void llenarCombo(ComboBox combo, List<Lugar> lugares) {
		combo.removeAllItems();
		for (Lugar lugar : lugares) {
			combo.addItem(lugar.getCodigoLugar());
			combo.setItemCaption(lugar.getCodigoLugar(), lugar.getNombre());
		}
	}

	private void postBuid() {

		this.btnNuevo.addClickListener((ClickListener) this);
		this.btnGuardar.addClickListener((ClickListener) this);
		this.btnCancelar.addClickListener((ClickListener) this);
		this.btnEliminar.addClickListener((ClickListener) this);
		this.btnBuscar.addClickListener((ClickListener) this);
		this.btnImprimir.addClickListener((ClickListener) this);
		columnLenghts = utilService.getLengthColumns("lugares");
		this.txtNombre.setMaxLength(columnLenghts.get("nombre"));
		cbxDepartamento.setImmediate(true);
		cbxDistrito.setImmediate(true);
		cbxProvincia.setImmediate(true);
		cbxTipoLugar.setImmediate(true);
		this.btnCancelar.setId("cancelar");
		this.btnEliminar.setId("eliminar");
		this.btnGuardar.setId("guardar");
		this.btnNuevo.setId("nuevo");
		this.btnBuscar.setId("consultar");
		this.btnImprimir.setId("imprimir");
		SigeUtil.validarBotones(permiso, btnNuevo, btnEliminar, btnCancelar,
				btnGuardar, btnImprimir, btnBuscar);
		btnBuscar.setVisible(permiso.getModificar());
		cbxDepartamento.addValueChangeListener(new ValueChangeListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				if (event.getProperty().getValue() != null) {
					llenarProvincias(event.getProperty().getValue().toString()
							.substring(0, 2));
					esProvincia = true;
				}
			}
		});

		cbxProvincia.addValueChangeListener(new ValueChangeListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				if (event.getProperty().getValue() != null) {
					String codigo = event.getProperty().getValue().toString();
					llenarDistrito(codigo.substring(0, 2),
							codigo.substring(2, 4));
					esDistrito = true;
				}
			}
		});

		cbxDistrito.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				// TODO Auto-generated method stub
				if (event.getProperty().getValue() != null) {
					String codigo = cbxDistrito.getValue().toString()
							.substring(0, 6);
					txtCodigoTipoLugar.setValue(lugarServicio
							.getUltimoCorrelativo(codigo.substring(0, 2),
									codigo.substring(2, 4),
									codigo.substring(4, 6)).toString());
				}
			}
		});

		cbxTipoLugar.addValueChangeListener(new ValueChangeListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				if (event.getProperty().getValue() != null) {
					String nombre = cbxTipoLugar.getItemCaption(event
							.getProperty().getValue());
					if (nombre.equalsIgnoreCase("departamento")) {
						cbxDepartamento.setEnabled(false);
						cbxProvincia.setEnabled(false);
						cbxDistrito.setEnabled(false);
						cbxDepartamento.setValue(null);
						cbxDistrito.setValue(null);
						cbxProvincia.setValue(null);
						txtCodigoTipoLugar.setMaxLength(2);
					} else if (nombre.equalsIgnoreCase("provincia")) {
						cbxDepartamento.setEnabled(true);
						cbxDepartamento.setValue(lugarServicio
								.getDepartamento());
						cbxProvincia.setEnabled(false);
						cbxDistrito.setEnabled(false);
						cbxDistrito.setValue(null);
						cbxProvincia.setValue(null);
						txtCodigoTipoLugar.setMaxLength(2);
					} else if (nombre.equalsIgnoreCase("distrito")) {
						cbxDepartamento.setValue(lugarServicio
								.getDepartamento());
						cbxProvincia.setValue(lugarServicio.getProvincia());
						cbxProvincia.setEnabled(true);
						cbxDistrito.setEnabled(false);
						cbxDistrito.setValue(null);
						txtCodigoTipoLugar.setMaxLength(2);
					} else {
						cbxDepartamento.setValue(lugarServicio
								.getDepartamento());
						cbxProvincia.setValue(lugarServicio.getProvincia());
						cbxDistrito.setValue(lugarServicio.getDistrito());
						txtCodigoTipoLugar.setMaxLength(3);
						cbxDepartamento.setEnabled(true);
						cbxProvincia.setEnabled(true);
						cbxDistrito.setEnabled(true);
					}
					txtCodigoTipoLugar.setValue(cbxTipoLugar.getValue()
							.toString());
				}
			}
		});
	}

	public void obtenerMotivo(String motivo, Boolean confirmacion,
			Integer tipoOperacion) {
		if (confirmacion) {
			lugar.setMotivoModificacion(motivo);
			this.confirmacion = true;
			if (tipoOperacion.equals(Constantes.TIPO_OPERACION.MODIFICACION)) {
				btnGuardar.click();
			} else {
				btnEliminar.click();
			}
			this.confirmacion = false;
		}
	}

	private void desactivarCampos(boolean estado) {
		txtNombre.setEnabled(estado);
		cbxDepartamento.setEnabled(estado);
		cbxDistrito.setEnabled(estado);
		cbxProvincia.setEnabled(estado);
		cbxTipoLugar.setEnabled(estado);
	}

	private void resetearFormulario() {
		this.flagEsNuevo = false;
		esDistrito = false;
		esProvincia = false;
		this.btnCancelar.setEnabled(false);
		this.btnNuevo.setEnabled(true);
		this.btnGuardar.setEnabled(false);
		this.btnBuscar.setEnabled(true);
		resetearComun();
		desactivarCampos(false);
	}

	private void resetearComun() {
		this.btnEliminar.setEnabled(false);
		this.txtNombre.setValue("");
		this.txtCodigoTipoLugar.setValue("");
		this.cbxTipoLugar.setValue(null);
		cbxDepartamento.setEnabled(true);
		cbxDistrito.setEnabled(true);
		cbxProvincia.setEnabled(true);
		this.btnImprimir.setEnabled(false);
		// cbxProvincia.setValue(null);
		// cbxDistrito.setValue(null);
	}

	private void NuevoRegistro() {
		lugar = new Lugar();
		this.flagEsNuevo = true;
		this.btnGuardar.setCaption("Guardar");
		this.btnGuardar.setVisible(permiso.getNuevo());
		this.btnGuardar.setEnabled(true);
		this.btnCancelar.setVisible(permiso.getNuevo());
		this.btnCancelar.setEnabled(true);
		this.btnNuevo.setEnabled(false);
		this.btnBuscar.setEnabled(false);
		desactivarCampos(permiso.getNuevo());
		resetearComun();
		// cbxTipoLugar.setValue(2L);
	}

	public void getLugarSeleccionado(Long idLugar) {
		lugar = lugarServicio.obtener(idLugar);
		cbxDepartamento.setValue(lugar.getCodigoLugar().substring(0, 2)
				+ "0000000");
		llenarProvincias(lugar.getCodigoLugar().substring(0, 2));
		cbxProvincia.setValue(lugar.getCodigoLugar().substring(0, 4) + "00000");
		llenarDistrito(lugar.getCodigoLugar().substring(0, 2), lugar
				.getCodigoLugar().substring(2, 4));
		cbxDistrito.setValue(lugar.getCodigoLugar().substring(0, 6) + "000");

		txtNombre.setValue(lugar.getNombre().trim());
		cbxTipoLugar.setValue(lugar.getTipoLugar().getId());
		txtCodigoTipoLugar.setValue(lugar.getCodigoLugar().substring(6, 9));
		txtCodigoTipoLugar.setMaxLength(3);
		btnGuardar.setCaption("Modificar");
		flagEsNuevo = false;
		btnCancelar.setVisible(permiso.getModificar());
		btnCancelar.setEnabled(true);
		btnEliminar.setEnabled(true);
		btnGuardar.setVisible(permiso.getModificar());
		btnGuardar.setEnabled(true);
		this.btnImprimir.setVisible(permiso.getImprimir());
		this.btnImprimir.setEnabled(true);
		desactivarCampos(permiso.getModificar());
	}

	private String generarCodigo() {
		String respuesta = "";
		String codigo;
		if (cbxDepartamento.isEnabled() && cbxProvincia.isEnabled()
				&& cbxDistrito.isEnabled()) {
			codigo = cbxDistrito.getValue().toString().substring(0, 6);
			respuesta = codigo
					+ SigeUtil.completarCeros(
							""
									+ lugarServicio.getCorrelativoLugar(
											codigo.substring(0, 2),
											codigo.substring(2, 4),
											codigo.substring(4, 6)), 3, 1);
		} else if (!cbxDepartamento.isEnabled() && !cbxProvincia.isEnabled()
				&& !cbxDistrito.isEnabled()) {
			respuesta = SigeUtil.completarCeros(
					SigeUtil.completarCeros(
							Long.parseLong(txtCodigoTipoLugar.getValue()
									.toString()) + "", 2, 1), 9, 2);
		} else if (cbxDepartamento.isEnabled() && !cbxProvincia.isEnabled()
				&& !cbxDistrito.isEnabled()) {
			codigo = cbxDepartamento.getValue().toString().substring(0, 2);
			respuesta = SigeUtil
					.completarCeros(
							codigo
									+ SigeUtil.completarCeros(
											Long.parseLong(txtCodigoTipoLugar
													.getValue().toString())
													+ "", 2, 1), 9, 2);

		} else if (cbxDepartamento.isEnabled() && cbxProvincia.isEnabled()
				&& !cbxDistrito.isEnabled()) {
			codigo = cbxProvincia.getValue().toString().substring(0, 4);
			respuesta = SigeUtil
					.completarCeros(
							codigo
									+ SigeUtil.completarCeros(
											Long.parseLong(txtCodigoTipoLugar
													.getValue().toString())
													+ "", 2, 1), 9, 2);
		}
		return respuesta;
	}

	@Override
	public void buttonClick(ClickEvent event) {
		if (event.getSource() == this.btnNuevo) {
			NuevoRegistro();
			this.txtNombre.focus();
			cbxDepartamento.setValue(lugarServicio.getDepartamento());
			cbxProvincia.setValue(lugarServicio.getProvincia());
			cbxDistrito.setValue(lugarServicio.getDistrito());
			cbxDepartamento.setEnabled(false);
			cbxProvincia.setEnabled(false);
			cbxDistrito.setEnabled(false);
		} else {
			if (event.getSource() == this.btnGuardar) {
				if (SigeUtil.validarCamposTexto(txtNombre, txtCodigoTipoLugar)
						&& cbxTipoLugar.getValue() != null) {
					lugar.setNombre(txtNombre.getValue().toString());
					lugar.setTipoLugar(tipoLugarServicio
							.obtener((Long) cbxTipoLugar.getValue()));
					if (!lugarServicio.validarDuplicado(lugar)) {
						Notificacion.show(new Notificacion(
								"El lugar ya existe",
								Constantes.MENSAJE.TYPE_ERROR));
					}
					if (this.flagEsNuevo) {
						lugar.setCodigoLugar(generarCodigo());
						lugarServicio.crear(lugar);
						Notificacion.show(new Notificacion(
								"Se guardo correctamente el lugar",
								Constantes.MENSAJE.TYPE_SUCCES));

					} else {
						if (!confirmacion) {
							Window ventana = SigeUtil.generarBuscador(
									new Window(), "INGRESAR MOTIVO", "360",
									"260");
							ventana.setContent(new PanelMotivoObservacion(
									ventana, this,
									Constantes.TIPO_OPERACION.MODIFICACION,
									(columnLenghts.get("motivomodifica"))));
							UI.getCurrent().addWindow(ventana);
							return;
						}
						lugarServicio.actualizar(lugar);
						Notificacion.show(new Notificacion(
								"Se actualizo correctamente el lugar",
								Constantes.MENSAJE.TYPE_SUCCES));
					}
					resetearFormulario();
					llenarCombos();
				} else {
					Notificacion.show(new Notificacion(
							"Debe llenar todos los campos",
							Constantes.MENSAJE.TYPE_ERROR));
				}
			} else {
				if (event.getSource() == this.btnCancelar) {
					resetearFormulario();
				} else {
					if (event.getSource() == this.btnBuscar) {
						Window ventana = SigeUtil.generarBuscador(new Window(),
								"BUSCAR LUGAR", "560px", "410px");
						ventana.setContent(new LugarBuscar(ventana, this));
						UI.getCurrent().addWindow(ventana);
					} else {
						if (event.getSource() == this.btnEliminar) {
							if (!confirmacion) {
								Window ventana = SigeUtil.generarBuscador(
										new Window(), "INGRESAR MOTIVO", "360",
										"260");
								ventana.setContent(new PanelMotivoObservacion(
										ventana, this,
										Constantes.TIPO_OPERACION.ELIMINACION,
										(columnLenghts.get("motivomodifica"))));
								UI.getCurrent().addWindow(ventana);
								return;
							}
							ConfirmDialog.show(UI.getCurrent(), "Confirmación",
									"¿Desea elminar el lugar?", "Aceptar",
									"Cancelar", new ConfirmDialog.Listener() {
										private static final long serialVersionUID = 1L;

										public void onClose(ConfirmDialog dialog) {
											if (dialog.isConfirmed()) {
												lugarServicio
														.eliminiarLugar(lugar);
												resetearFormulario();
											}
										}
									});
						} else if (event.getSource() == this.btnImprimir) {
							Window ventana = SigeUtil.generarBuscador(
									new Window(), "IMPRIMIR", "800px", "550px");
							Map<String, Object> parametros = new HashMap<String, Object>();
							parametros.put("lugarId", lugar.getId());
							ventana.setContent(new PDFVizualizador(this,
									permiso, parametros, null, "LugarImprimir",
									null));
							UI.getCurrent().addWindow(ventana);
						}
					}
				}
			}
		}
	}

	public void respuesta(Long idLugar) {
		if (quienLlama instanceof PersonaMantenimiento) {
			PersonaMantenimiento panel = (PersonaMantenimiento) quienLlama;
			panel.getLugarSeleccionado(idLugar);
			UI.getCurrent().removeWindow(windowContiene);
		} else {
			return;
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// lblDepartamento
		lblDepartamento = new Label();
		lblDepartamento.setImmediate(false);
		lblDepartamento.setWidth("-1px");
		lblDepartamento.setHeight("-1px");
		lblDepartamento.setValue("Departamento");
		mainLayout.addComponent(lblDepartamento, "top:13.0px;left:20.0px;");

		// lblProvincia
		lblProvincia = new Label();
		lblProvincia.setImmediate(false);
		lblProvincia.setWidth("-1px");
		lblProvincia.setHeight("-1px");
		lblProvincia.setValue("Provincia");
		mainLayout.addComponent(lblProvincia, "top:13.0px;left:221.0px;");

		// lblDistrito
		lblDistrito = new Label();
		lblDistrito.setImmediate(false);
		lblDistrito.setWidth("-1px");
		lblDistrito.setHeight("-1px");
		lblDistrito.setValue("Distrito");
		mainLayout.addComponent(lblDistrito, "top:13.0px;left:420.0px;");

		// lblTipoLugar
		lblTipoLugar = new Label();
		lblTipoLugar.setImmediate(false);
		lblTipoLugar.setWidth("-1px");
		lblTipoLugar.setHeight("-1px");
		lblTipoLugar.setValue("Tipo Lugar");
		mainLayout.addComponent(lblTipoLugar, "top:109.0px;left:20.0px;");

		// lblNombre
		lblNombre = new Label();
		lblNombre.setImmediate(false);
		lblNombre.setWidth("-1px");
		lblNombre.setHeight("-1px");
		lblNombre.setValue("Nombre");
		mainLayout.addComponent(lblNombre, "top:79.0px;left:20.0px;");

		// cbxDepartamento
		cbxDepartamento = new ComboBox();
		cbxDepartamento.setImmediate(true);
		cbxDepartamento.setWidth("180px");
		cbxDepartamento.setHeight("-1px");
		mainLayout.addComponent(cbxDepartamento, "top:38.0px;left:20.0px;");

		// cbxDistrito
		cbxDistrito = new ComboBox();
		cbxDistrito.setImmediate(true);
		cbxDistrito.setWidth("220px");
		cbxDistrito.setHeight("-1px");
		mainLayout.addComponent(cbxDistrito, "top:38.0px;left:420.0px;");

		// cbxProvincia
		cbxProvincia = new ComboBox();
		cbxProvincia.setImmediate(true);
		cbxProvincia.setWidth("181px");
		cbxProvincia.setHeight("-1px");
		mainLayout.addComponent(cbxProvincia, "top:40.0px;left:219.0px;");

		// cbxTipoLugar
		cbxTipoLugar = new ComboBox();
		cbxTipoLugar.setImmediate(true);
		cbxTipoLugar.setWidth("345px");
		cbxTipoLugar.setHeight("-1px");
		mainLayout.addComponent(cbxTipoLugar, "top:107.0px;left:89.0px;");

		// txtNombre
		txtNombre = new TextField();
		txtNombre.setImmediate(false);
		txtNombre.setWidth("551px");
		txtNombre.setHeight("-1px");
		mainLayout.addComponent(txtNombre, "top:77.0px;left:89.0px;");

		// btnNuevo
		btnNuevo = new Button();
		btnNuevo.setCaption("Nuevo");
		btnNuevo.setIcon(new ThemeResource("images/botones/new.png"));
		btnNuevo.setImmediate(true);
		btnNuevo.setWidth("100px");
		btnNuevo.setHeight("-1px");
		mainLayout.addComponent(btnNuevo, "top:140.0px;left:20.0px;");

		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setIcon(new ThemeResource("images/botones/save.png"));
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("100px");
		btnGuardar.setHeight("-1px");
		mainLayout.addComponent(btnGuardar, "top:140.0px;left:126.0px;");

		// btnEliminar
		btnEliminar = new Button();
		btnEliminar.setCaption("Eliminar");
		btnEliminar.setIcon(new ThemeResource("images/botones/delete.png"));
		btnEliminar.setImmediate(true);
		btnEliminar.setWidth("100px");
		btnEliminar.setHeight("-1px");
		mainLayout.addComponent(btnEliminar, "top:140.0px;left:230.0px;");

		// btnCancelar
		btnCancelar = new Button();
		btnCancelar.setCaption("Cancelar");
		btnCancelar.setIcon(new ThemeResource("images/botones/undo.png"));
		btnCancelar.setImmediate(true);
		btnCancelar.setWidth("100px");
		btnCancelar.setHeight("-1px");
		mainLayout.addComponent(btnCancelar, "top:140.0px;left:334.0px;");

		// btnBuscar
		btnBuscar = new Button();
		btnBuscar.setCaption("Buscar");
		btnBuscar.setIcon(new ThemeResource("images/botones/find.png"));
		btnBuscar.setImmediate(true);
		btnBuscar.setWidth("100px");
		btnBuscar.setHeight("-1px");
		mainLayout.addComponent(btnBuscar, "top:140.0px;left:440.0px;");

		// btnImprimir
		btnImprimir = new Button();
		btnImprimir.setCaption("Imprimir");
		btnImprimir.setIcon(new ThemeResource("images/botones/print.png"));
		btnImprimir.setImmediate(true);
		btnImprimir.setWidth("100px");
		btnImprimir.setHeight("-1px");
		mainLayout.addComponent(btnImprimir, "top:140.0px;left:547.0px;");

		// txtCodigoTipoLugar
		txtCodigoTipoLugar = new NumberField();
		txtCodigoTipoLugar.setImmediate(false);
		txtCodigoTipoLugar.setWidth("106px");
		txtCodigoTipoLugar.setHeight("-1px");
		mainLayout
				.addComponent(txtCodigoTipoLugar, "top:107.0px;left:434.0px;");

		return mainLayout;
	}

}
