package com.sige.gui;

import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.io.FileUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.vaadin.dialogs.ConfirmDialog;
import org.vaadin.risto.formsender.FormSenderBuilder;
import org.vaadin.risto.formsender.widgetset.client.shared.Method;

import com.sige.entidad.Dependencia;
import com.sige.entidad.DependenciaTipoTramitePlantilla;
import com.sige.entidad.DocumentoInterno;
import com.sige.entidad.DocumentoInternoDestino;
import com.sige.entidad.DocumentoInternoReferen;
import com.sige.entidad.Expediente;
import com.sige.entidad.ExpedienteDocumento;
import com.sige.entidad.ExpedienteMovimiento;
import com.sige.entidad.TipoDocumento;
import com.sige.servicio.AnexoPresentadoService;
import com.sige.servicio.DependenciaServicio;
import com.sige.servicio.DependenciaTipoTramitePlantillaService;
import com.sige.servicio.DocumentoInternoDestinoService;
import com.sige.servicio.DocumentoInternoService;
import com.sige.servicio.ExpedienteDocumentoService;
import com.sige.servicio.ExpedienteMovimientoServicio;
import com.sige.servicio.ExpedienteServicio;
import com.sige.servicio.TipoDocumentoServicio;
import com.sige.servicio.UtilService;
import com.sige.util.Boton;
import com.sige.util.Constantes;
import com.sige.util.ExpedienteCanonico;
import com.sige.util.Injector;
import com.sige.util.Notificacion;
import com.sige.util.ReceiverCustom;
import com.sige.util.SigeUtil;
import com.sige.util.TextField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.ProgressIndicator;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.UI;
import com.vaadin.ui.Upload;
import com.vaadin.ui.Upload.FailedEvent;
import com.vaadin.ui.Upload.FinishedEvent;
import com.vaadin.ui.Upload.StartedEvent;
import com.vaadin.ui.Upload.SucceededEvent;
import com.vaadin.ui.Window;
import com.vaadin.ui.themes.Reindeer;

public class ModificarDocumentoProceso extends CustomComponent implements
		ClickListener {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabReferenciaDocumentos;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private Button btnEliminar;
	@AutoGenerated
	private Button btnDescargar;
	@AutoGenerated
	private Button cancelProcessing;
	@AutoGenerated
	private Upload upload;
	@AutoGenerated
	private HorizontalLayout progressLayout;
	@AutoGenerated
	private Button btnAgregarDocumento;
	@AutoGenerated
	private Table tblDocumentos;
	@AutoGenerated
	private ComboBox cbxExpediente;
	@AutoGenerated
	private Label lblExpediente;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private Boton btnQuitarReferencia;
	@AutoGenerated
	private Boton btnAgregarReferencia;
	@AutoGenerated
	private Table tbReferencias;
	@AutoGenerated
	private Label label_11;
	@AutoGenerated
	private Label lblExpedientesAnexados;
	@AutoGenerated
	private Boton btnQuitarExpedienteExterno;
	@AutoGenerated
	private Boton btnAgregarExpedienteExterno;
	@AutoGenerated
	private Table tbExpedienteExterno;
	@AutoGenerated
	private Label label_10;
	@AutoGenerated
	private Label lblEnviadoPor;
	@AutoGenerated
	private TextField txtTipoDocumento;
	@AutoGenerated
	private Button btnCerrar;
	@AutoGenerated
	private Button btnGrabar;
	@AutoGenerated
	private CheckBox chkCopiaArchivo;
	@AutoGenerated
	private Label label_13;
	@AutoGenerated
	private TextArea txtAAsunto;
	@AutoGenerated
	private Label label_12;
	@AutoGenerated
	private Boton btnBuscarDependencia;
	@AutoGenerated
	private TextField txtDependenciaDestino;
	@AutoGenerated
	private Label label_9;
	@AutoGenerated
	private TextField txtFolios;
	@AutoGenerated
	private PopupDateField popDateFecha;
	@AutoGenerated
	private Label label_8;
	@AutoGenerated
	private Label label_7;
	@AutoGenerated
	private TextField txtNumeroDocumento;
	@AutoGenerated
	private TextField txtAnioDocumento;
	@AutoGenerated
	private TextField txtSiglasDocumento;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Boton btnBuscarDocumento;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label lblDocumento;
	@AutoGenerated
	private Label lblFechaEnvio;
	@AutoGenerated
	private Label lblDependenciaOrigen;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	private Log logger = LogFactory.getLog(ModificarDocumentoProceso.class);
	private CustomComponent quienLlama;
	private Dependencia dependenciaObtenida;
	private DependenciaServicio dependenciaServicio;
	private ExpedienteMovimientoServicio expedienteMovimientoService;
	private ExpedienteServicio expedienteService;
	private DocumentoInternoService docInternoService;
	private TipoDocumentoServicio tipoDocumentoService;
	private DocumentoInternoDestinoService docInternoDestinoService;
	private AnexoPresentadoService anexoPresentadoService;
	private ExpedienteCanonico expedienteCanonico;
	private Expediente expediente;
	private ExpedienteMovimiento expedienteMovimiento;
	private DocumentoInterno docInterno;
	private DocumentoInternoDestino docInternoDestino;
	private Boolean expedienteEstaSeleccionado = false;
	private Boolean documentoEstaSeleccionado = false;
	private Expediente expedienteSeleccionado;
	private DocumentoInterno documentoInternoSeleccionado;
	private Dependencia dependenciaOrigen;
	private TipoDocumento tipoDocumentoObtenido;
	private Map<String, DocumentoInterno> documentoInternoExpediente;
	private UtilService utilService;
	private Map<String, Integer> docInternoColumnLenghts;
	private Integer cantAnexosExpediente;

	private ReceiverCustom receiver;

	@SuppressWarnings("deprecation")
	private ProgressIndicator pi;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	private Window windowContiene;

	private DependenciaTipoTramitePlantillaService dependenciaTipoTramitePlantillaService;

	private ExpedienteDocumentoService expedienteDocumentoService;

	private ExpedienteDocumento expedienteDocumentoSeleccionado;

	public ModificarDocumentoProceso(Window windowContiene,
			CustomComponent quienLlama, ExpedienteCanonico expedienteCanonico) {
		utilService = Injector.obtenerServicio(UtilService.class);
		anexoPresentadoService = Injector
				.obtenerServicio(AnexoPresentadoService.class);
		documentoInternoExpediente = new HashMap<String, DocumentoInterno>();

		tipoDocumentoService = Injector
				.obtenerServicio(TipoDocumentoServicio.class);
		dependenciaServicio = Injector
				.obtenerServicio(DependenciaServicio.class);
		expedienteService = Injector.obtenerServicio(ExpedienteServicio.class);
		expedienteMovimientoService = Injector
				.obtenerServicio(ExpedienteMovimientoServicio.class);
		docInternoService = Injector
				.obtenerServicio(DocumentoInternoService.class);
		docInternoDestinoService = Injector
				.obtenerServicio(DocumentoInternoDestinoService.class);
		this.dependenciaTipoTramitePlantillaService = Injector
				.obtenerServicio(DependenciaTipoTramitePlantillaService.class);
		this.expedienteDocumentoService = Injector
				.obtenerServicio(ExpedienteDocumentoService.class);

		this.quienLlama = quienLlama;
		this.expedienteCanonico = expedienteCanonico;
		this.windowContiene = windowContiene;
		receiver = new ReceiverCustom();
		receiver.setFileLocation(Constantes.FILE_LOCATION.FILE_LOCATION_DOCUMENTOS);
		buildMainLayout();
		setCompositionRoot(mainLayout);
		postBuild();
		getDetalleDocumento();

		// TODO add user code here
	}

	public void postBuild() {

		pi = new ProgressIndicator();

		upload.setImmediate(true);
		upload.setButtonCaption("Cargar Archivo");

		progressLayout.setSpacing(true);
		progressLayout.setVisible(false);
		cancelProcessing.setVisible(false);
		progressLayout.addComponent(pi);
		progressLayout.setComponentAlignment(pi, Alignment.MIDDLE_LEFT);

		cancelProcessing.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				upload.interruptUpload();
			}
		});
		cancelProcessing.setStyleName("small");

		upload.addStartedListener(new Upload.StartedListener() {

			@Override
			public void uploadStarted(StartedEvent event) {
				if (!event
						.getFilename()
						.substring(event.getFilename().length() - 3,
								event.getFilename().length())
						.equalsIgnoreCase("doc")) {

					upload.interruptUpload();
					Notificacion.show(new Notificacion(
							"El sistema solo acepta archivos .doc",
							Constantes.MENSAJE.TYPE_ERROR));
					return;
				}

				if (expedienteDocumentoSeleccionado != null) {
					receiver.setFileName(expedienteDocumentoSeleccionado
							.getNombreArchivo());
					upload.setVisible(false);
					progressLayout.setVisible(true);
					cancelProcessing.setVisible(true);
					pi.setValue(0f);
					pi.setPollingInterval(500);
				} else {
					upload.interruptUpload();
					Notificacion.show(new Notificacion(
							"Seleccione un documento para cargar",
							Constantes.MENSAJE.TYPE_ERROR));
				}
			}

		});

		upload.addProgressListener(new Upload.ProgressListener() {
			public void updateProgress(long readBytes, long contentLength) {

				pi.setValue(new Float(readBytes / (float) contentLength));
			}

		});

		upload.addSucceededListener(new Upload.SucceededListener() {
			public void uploadSucceeded(SucceededEvent event) {

				Long idExpDoc;
				for (Object o : tblDocumentos.getItemIds()) {
					idExpDoc = (Long) tblDocumentos.getItem(o)
							.getItemProperty("id").getValue();
					if (idExpDoc.equals(expedienteDocumentoSeleccionado.getId())) {
						tblDocumentos.getItem(o).getItemProperty("cargado")
								.setValue(Boolean.TRUE);
						break;
					}
				}
				Notificacion.show(new Notificacion("Se cargo correctamente: "
						+ event.getFilename(), Constantes.MENSAJE.TYPE_SUCCES));
			}
		});

		upload.addFailedListener(new Upload.FailedListener() {

			@Override
			public void uploadFailed(FailedEvent event) {

			}
		});

		upload.addFinishedListener(new Upload.FinishedListener() {

			@Override
			public void uploadFinished(FinishedEvent event) {

				progressLayout.setVisible(false);
				cancelProcessing.setVisible(false);
				upload.setVisible(true);
			}
		});

		popDateFecha.setResolution(Resolution.DAY);
		cantAnexosExpediente = 0;
		lblEnviadoPor.setContentMode(ContentMode.HTML);
		label_13.setContentMode(ContentMode.HTML);
		label_12.setContentMode(ContentMode.HTML);
		label_11.setContentMode(ContentMode.HTML);
		lblExpedientesAnexados.setContentMode(ContentMode.HTML);
		label_10.setContentMode(ContentMode.HTML);
		label_9.setContentMode(ContentMode.HTML);
		label_8.setContentMode(ContentMode.HTML);
		label_7.setContentMode(ContentMode.HTML);
		label_6.setContentMode(ContentMode.HTML);
		label_5.setContentMode(ContentMode.HTML);
		label_4.setContentMode(ContentMode.HTML);
		label_3.setContentMode(ContentMode.HTML);
		lblDocumento.setContentMode(ContentMode.HTML);
		lblFechaEnvio.setContentMode(ContentMode.HTML);
		lblDependenciaOrigen.setContentMode(ContentMode.HTML);
		label_2.setContentMode(ContentMode.HTML);
		label_1.setContentMode(ContentMode.HTML);

		docInternoColumnLenghts = utilService.getLengthColumns("docinterno");
		this.txtNumeroDocumento.setMaxLength(docInternoColumnLenghts
				.get("numerodocumento"));
		this.txtAnioDocumento.setMaxLength(docInternoColumnLenghts
				.get("aniodocumento"));
		this.txtSiglasDocumento.setMaxLength(docInternoColumnLenghts
				.get("siglasdocumento"));
		this.txtAAsunto.setMaxLength(docInternoColumnLenghts.get("asunto"));
		txtDependenciaDestino.setEnabled(false);
		txtTipoDocumento.setEnabled(false);
		this.btnAgregarExpedienteExterno.setStyleName(Reindeer.BUTTON_LINK);
		this.btnAgregarReferencia.setStyleName(Reindeer.BUTTON_LINK);
		this.btnBuscarDependencia.setStyleName(Reindeer.BUTTON_LINK);
		this.btnBuscarDocumento.setStyleName(Reindeer.BUTTON_LINK);
		this.btnQuitarExpedienteExterno.setStyleName(Reindeer.BUTTON_LINK);
		this.btnQuitarReferencia.setStyleName(Reindeer.BUTTON_LINK);
		this.btnAgregarExpedienteExterno.addClickListener((ClickListener) this);
		this.btnAgregarReferencia.addClickListener((ClickListener) this);
		this.btnBuscarDependencia.addClickListener((ClickListener) this);
		this.btnAgregarExpedienteExterno.addClickListener((ClickListener) this);
		this.btnBuscarDocumento.addClickListener((ClickListener) this);
		this.btnCerrar.addClickListener((ClickListener) this);
		this.btnGrabar.addClickListener((ClickListener) this);
		this.btnQuitarExpedienteExterno.addClickListener((ClickListener) this);
		this.btnQuitarReferencia.addClickListener((ClickListener) this);
		this.btnEliminar.addClickListener((ClickListener) this);
		this.btnDescargar.addClickListener((ClickListener) this);

		this.btnAgregarReferencia.setVisible(false);
		this.btnQuitarReferencia.setVisible(false);

		this.cbxExpediente.setImmediate(true);

		this.btnAgregarDocumento.addClickListener((ClickListener) this);
		btnBuscarDocumento.focus();
		btnBuscarDocumento.setTabIndex(1);
		txtNumeroDocumento.setTabIndex(2);
		txtAnioDocumento.setTabIndex(3);
		txtSiglasDocumento.setTabIndex(4);
		popDateFecha.setTabIndex(5);
		txtFolios.setTabIndex(6);
		btnAgregarExpedienteExterno.setTabIndex(7);
		btnQuitarExpedienteExterno.setTabIndex(8);
		txtAAsunto.setTabIndex(9);
		btnGrabar.setTabIndex(10);
		btnCerrar.setTabIndex(11);
		IndexedContainer contenedorReferencia = new IndexedContainer();
		contenedorReferencia.addContainerProperty("id", Long.class, null);
		contenedorReferencia.addContainerProperty("estado", Embedded.class,
				null);
		contenedorReferencia.addContainerProperty("documento", String.class,
				null);
		contenedorReferencia.addContainerProperty("fechaEnvio",
				Timestamp.class, null);
		contenedorReferencia.addContainerProperty("dependenciaOrigen",
				String.class, null);
		contenedorReferencia.addContainerProperty("dependenciaDestino",
				String.class, null);
		contenedorReferencia.addContainerProperty("asunto", String.class, null);
		tbReferencias.setContainerDataSource(contenedorReferencia);
		tbReferencias.setVisibleColumns(new Object[] { "estado", "documento",
				"fechaEnvio", "dependenciaOrigen", "dependenciaDestino",
				"asunto" });
		tbReferencias.setColumnHeader("estado", "");

		tbReferencias.setColumnHeader("documento", "Documento");
		tbReferencias.setColumnHeader("fechaEnvio", "Fecha Envío");
		tbReferencias.setColumnHeader("dependenciaOrigen", "Dep. Origen");
		tbReferencias.setColumnHeader("dependenciaDestino", "Dep. Destino");
		tbReferencias.setColumnHeader("asunto", "Asunto");
		tbReferencias.setColumnWidth("estado", 15);

		tbReferencias.setColumnWidth("documento", 90);
		tbReferencias.setColumnWidth("fechaEnvio", 80);
		tbReferencias.setColumnWidth("dependenciaOrigen", 100);
		tbReferencias.setColumnWidth("dependenciaDestino", 100);
		tbReferencias.setColumnWidth("asunto", 200);
		tbReferencias.setSelectable(true);
		tbReferencias.setImmediate(true);

		IndexedContainer contenedorDocumentos = new IndexedContainer();
		contenedorDocumentos.addContainerProperty("id", Long.class, null);
		contenedorDocumentos.addContainerProperty("item", Long.class, null);
		contenedorDocumentos.addContainerProperty("documento", String.class,
				null);

		contenedorDocumentos
				.addContainerProperty("archivo", String.class, null);
		contenedorDocumentos.addContainerProperty("cargado", Boolean.class,
				null);
		tblDocumentos.setContainerDataSource(contenedorDocumentos);
		tblDocumentos
				.setVisibleColumns(new Object[] { "documento", "archivo" });

		tblDocumentos.setColumnHeader("documento", "Documento");
		tblDocumentos.setColumnHeader("archivo", "Nombre Archivo");

		tblDocumentos.setColumnWidth("documento", 450);
		tblDocumentos.setColumnWidth("archivo", 250);

		tblDocumentos.setColumnAlignment("documento", Table.Align.CENTER);
		tblDocumentos.setColumnAlignment("archivo", Table.Align.CENTER);

		tblDocumentos.setSelectable(true);
		tblDocumentos.setImmediate(true);

		tblDocumentos
				.addValueChangeListener(new Property.ValueChangeListener() {

					@Override
					public void valueChange(ValueChangeEvent event) {
						// TODO Auto-generated method stub
						Item item = tblDocumentos.getItem(tblDocumentos
								.getValue());
						if (item != null) {
							getExpedienteDocumento((Long) item.getItemProperty(
									"id").getValue());
						}

					}

				});

		IndexedContainer contenedorExpedientExterno = new IndexedContainer();
		contenedorExpedientExterno.addContainerProperty("id", Long.class, null);
		contenedorExpedientExterno.addContainerProperty("numero", String.class,
				null);
		contenedorExpedientExterno.addContainerProperty("anio", String.class,
				null);
		tbExpedienteExterno.setContainerDataSource(contenedorExpedientExterno);
		tbExpedienteExterno
				.setVisibleColumns(new Object[] { "numero", "anio" });
		tbExpedienteExterno.setColumnWidth("numero", 100);
		tbExpedienteExterno.setColumnWidth("anio", 100);
		tbExpedienteExterno.setColumnHeader("numero", "Numero");
		tbExpedienteExterno.setColumnHeader("anio", "Año");
		tbExpedienteExterno.setSelectable(true);
		tbExpedienteExterno.setImmediate(true);
		tbExpedienteExterno
				.addValueChangeListener(new Property.ValueChangeListener() {

					@Override
					public void valueChange(ValueChangeEvent event) {
						// TODO Auto-generated method stub
						Item item = tbExpedienteExterno
								.getItem(tbExpedienteExterno.getValue());
						if (item != null) {
							expedienteEstaSeleccionado = true;
							expedienteSeleccionado = expedienteService
									.obtener(Long.parseLong(item
											.getItemProperty("id").getValue()
											.toString()));
						}
					}
				});
	}

	private void getExpedienteDocumento(Long idPlantilla) {
		expedienteDocumentoSeleccionado = expedienteDocumentoService
				.obtener(idPlantilla);
	}

	@SuppressWarnings("unchecked")
	public void getDetalleDocumento() {
		Date date = new Date();
		Timestamp fechaHora = new Timestamp(date.getTime());
		expedienteMovimiento = expedienteMovimientoService
				.obtener(expedienteCanonico.getCodExpedienteMovimiento());
		expediente = expedienteMovimiento.getExpediente();

		docInterno = expedienteMovimiento.getDocumentoInterno();
		docInternoDestino = docInternoDestinoService
				.obtenerDocInternoDestinoPorDocInterno(docInterno
						.getCodigodocumento());
		DocumentoInterno referencia = docInternoService
				.obtenerUltimoDocInternoPorExpediente(expediente);

		DocumentoInternoDestino referenciaDestino = docInternoDestinoService
				.obtenerDocInternoDestinoPorDocInterno(referencia
						.getCodigodocumento());

		if (!expedienteCanonico.getDerivar()) {
			txtDependenciaDestino.setValue(docInterno.getDependencia()
					.getNombre().toString());
			btnBuscarDependencia.setVisible(false);
		}
		dependenciaOrigen = expedienteCanonico.getDependenciaEntidad();
		lblDependenciaOrigen.setValue(dependenciaOrigen.getNombre());

		lblFechaEnvio.setValue(obtenerFormatoFecha(fechaHora));
		lblEnviadoPor.setValue(docInterno.getCreadoPor());
		IndexedContainer contenedor = (IndexedContainer) tbExpedienteExterno
				.getContainerDataSource();
		contenedor.removeAllItems();
		cantAnexosExpediente += anexoPresentadoService
				.obtenerCantidadAnexosDeExpediente(expediente);
		lblExpedientesAnexados.setValue(cantAnexosExpediente
				+ "Expedientes Anexados");
		Item item = contenedor.addItem(0);
		item.getItemProperty("id").setValue(expediente.getId());

		item.getItemProperty("numero").setValue(expediente.getNumero());

		item.getItemProperty("anio").setValue(expediente.getAnio());

		cbxExpediente.addItem(expediente.getId());
		cbxExpediente.setItemCaption(expediente.getId(), expediente.getAnio()
				+ "-" + expediente.getNumero());

		documentoInternoExpediente.put(expediente.getCodigo(), referencia);

		IndexedContainer contenedorReferencias = (IndexedContainer) tbReferencias
				.getContainerDataSource();
		contenedorReferencias.removeAllItems();
		Item itemReferencias = contenedorReferencias.addItem(0);
		itemReferencias.getItemProperty("id").setValue(referencia.getId());
		itemReferencias.getItemProperty("estado").setValue(
				SigeUtil.asignarEstado(referenciaDestino.getTipoMovimiento(),
						referenciaDestino.getRecepcionadoPor() == null ? ""
								: referenciaDestino.getRecepcionadoPor()));
		itemReferencias.getItemProperty("documento").setValue(
				tipoDocumentoService.obtenerTipoDocumento(
						referencia.getCodigoTipoDocumento()).getNombre());
		itemReferencias.getItemProperty("fechaEnvio").setValue(
				referencia.getFechadocumento());
		itemReferencias.getItemProperty("dependenciaOrigen").setValue(
				dependenciaServicio
						.obtener(referencia.getDependencia().getId())
						.getNombre());
		itemReferencias.getItemProperty("dependenciaDestino")
				.setValue(
						dependenciaServicio.obtener(
								referenciaDestino.getDependencia().getId())
								.getNombre());
		itemReferencias.getItemProperty("asunto").setValue(
				referencia.getAsunto());

		getAllDocumentosCargados();
	}

	private void getAllDocumentosCargados() {
		Long idExpediente;
		for (Object o : tbExpedienteExterno.getItemIds()) {
			idExpediente = (Long) tbExpedienteExterno.getItem(o)
					.getItemProperty("id").getValue();
			List<ExpedienteDocumento> expedienteDocumentos = expedienteDocumentoService
					.obtenerTodos(dependenciaOrigen,
							expedienteService.obtener(idExpediente));
			for (ExpedienteDocumento expDoc : expedienteDocumentos) {
				IndexedContainer container = (IndexedContainer) tblDocumentos
						.getContainerDataSource();
				Item item = container.addItem(String.valueOf(expDoc
						.getDependenciaTipoTramitePlantilla().getId())
						+ String.valueOf(idExpediente));
				if (item != null) {

					item.getItemProperty("id").setValue(expDoc.getId());
					item.getItemProperty("item").setValue(
							new Long(container.size()));
					item.getItemProperty("documento").setValue(
							expDoc.getDependenciaTipoTramitePlantilla()
									.getNombrePlantilla());
					item.getItemProperty("archivo").setValue(
							expDoc.getNombreArchivo());
					item.getItemProperty("cargado").setValue(Boolean.TRUE);
				}
			}

		}
	}

	public void obtenerDependencia(Long codDependencia) {
		dependenciaObtenida = dependenciaServicio.obtener(codDependencia);
		txtDependenciaDestino.setValue(dependenciaObtenida.getNombre());
	}

	public void obtenerTipoDocumento(Long codDocumento) {
		Date date = new Date();
		Timestamp fechaHora = new Timestamp(date.getTime());
		tipoDocumentoObtenido = tipoDocumentoService.obtener(codDocumento);
		txtTipoDocumento.setValue(tipoDocumentoObtenido.getNombre());
		txtAnioDocumento.setValue(docInterno.getAñoDocumento());
		txtNumeroDocumento.setValue(SigeUtil.completarCeros(docInternoService
				.obtenerNumDocumento(dependenciaOrigen).toString(), 5, 1));
		txtSiglasDocumento.setValue(expedienteCanonico.getDependenciaEntidad()
				.getNomenclatura());
		txtFolios.setValue(docInterno.getNumerofolios() + "");
		popDateFecha.setValue(fechaHora);
	}

	public void obtenerExpediente(Long idExpediente) {
		Expediente expedienteObtenido = expedienteService.obtener(idExpediente);
		List<Expediente> expedientes = new ArrayList<Expediente>();
		Expediente expediente = null;

		cbxExpediente.addItem(expedienteObtenido.getId());
		cbxExpediente.setItemCaption(
				expedienteObtenido.getId(),
				expedienteObtenido.getAnio() + "-"
						+ expedienteObtenido.getNumero());

		for (Object id : tbExpedienteExterno.getItemIds()) {
			expediente = new Expediente();
			expediente = expedienteService.obtener(Long
					.parseLong(tbExpedienteExterno.getItem(id)
							.getItemProperty("id").getValue().toString()));
			expedientes.add(expediente);
		}
		expedientes.add(expedienteObtenido);

		IndexedContainer contenedor = (IndexedContainer) tbExpedienteExterno
				.getContainerDataSource();
		contenedor.removeAllItems();
		cantAnexosExpediente = 0;
		for (int i = 0; i < expedientes.size(); i++) {

			cantAnexosExpediente += anexoPresentadoService
					.obtenerCantidadAnexosDeExpediente(expedientes.get(i));
			Item item = contenedor.addItem(i);
			item.getItemProperty("id").setValue(expedientes.get(i).getId());
			item.getItemProperty("numero").setValue(
					expedientes.get(i).getNumero());
			item.getItemProperty("anio").setValue(expedientes.get(i).getAnio());
		}
		lblExpedientesAnexados.setValue(cantAnexosExpediente
				+ " Expedientes Anexados");
		agregarDocumentoInternoDelExpediente(expedienteObtenido);
	}

	public void quitarDocInternoExpediente(Expediente expediente) {

		@SuppressWarnings("unused")
		DocumentoInterno docInternoEliminar = documentoInternoExpediente
				.get(expediente.getCodigo());
		documentoInternoExpediente.remove(expediente.getCodigo());

		List<DocumentoInterno> documentosInternos = new ArrayList<DocumentoInterno>();
		DocumentoInterno docInternoObtener = null;
		Expediente expedienteObtener = null;
		for (Object id : tbExpedienteExterno.getItemIds()) {
			docInternoObtener = new DocumentoInterno();
			expedienteObtener = new Expediente();
			expedienteObtener = expedienteService.obtener(Long
					.parseLong(tbExpedienteExterno.getItem(id)
							.getItemProperty("id").getValue().toString()));
			docInternoObtener = documentoInternoExpediente
					.get(expedienteObtener.getCodigo());
			documentosInternos.add(docInternoObtener);
		}
		// DocumentoInterno docInternoAnterior = null;
		// for (Object id : tbReferencias.getItemIds()) {
		// docInternoAnterior = docInternoService.obtener(Long
		// .parseLong(tbReferencias.getItem(id).getItemProperty("id")
		// .toString()));
		// if (!docInternoAnterior.getNumerodocumento().equals(
		// docInternoEliminar.getNumerodocumento())) {
		// documentosInternos.add(docInternoAnterior);
		// }
		//
		// }
		getAllReferencias(documentosInternos);
	}

	public void agregarDocumentoInternoDelExpediente(Expediente expediente) {
		DocumentoInterno docInternoNuevo = docInternoService
				.obtenerUltimoDocInternoPorExpediente(expediente);
		List<DocumentoInterno> documentosInternos = new ArrayList<DocumentoInterno>();
		documentoInternoExpediente.put(expediente.getCodigo(), docInternoNuevo);
		DocumentoInterno docInternoAnterior = null;
		Boolean estaRepetido = false;
		for (Object id : tbReferencias.getItemIds()) {
			docInternoAnterior = docInternoService.obtener(Long
					.parseLong(tbReferencias.getItem(id).getItemProperty("id")
							.getValue().toString()));
			// expedienteService.o
			if (docInternoAnterior.getDependencia().getId() == docInternoNuevo
					.getDependencia().getId()
					&& docInternoAnterior.getNumerodocumento().equals(
							docInternoNuevo.getNumerodocumento())) {
				estaRepetido = true;
			}
			documentosInternos.add(docInternoAnterior);
		}
		if (!estaRepetido) {
			documentosInternos.add(docInternoNuevo);
		}
		getAllReferencias(documentosInternos);

	}

	public void obtenerDocumentoInterno(Long codDocumento) {
		DocumentoInterno docInternoObtenido = docInternoService
				.obtener(codDocumento);
		List<DocumentoInterno> documentos = new ArrayList<DocumentoInterno>();
		DocumentoInterno documentoInterno = null;
		for (Object id : tbReferencias.getItemIds()) {
			documentoInterno = new DocumentoInterno();
			documentoInterno = docInternoService.obtener(Long
					.parseLong(tbReferencias.getItem(id).getItemProperty("id")
							.getValue().toString()));
			documentos.add(documentoInterno);
		}
		documentos.add(docInternoObtenido);

		getAllReferencias(documentos);

	}

	@SuppressWarnings("unchecked")
	public void getAllReferencias(List<DocumentoInterno> documentos) {
		IndexedContainer contenedor = (IndexedContainer) tbReferencias
				.getContainerDataSource();
		contenedor.removeAllItems();
		for (int i = 0; i < documentos.size(); i++) {
			DocumentoInternoDestino docDestino = docInternoDestinoService
					.obtenerDocInternoDestinoPorDocInterno(documentos.get(i)
							.getCodigodocumento());
			Item itemReferencias = contenedor.addItem(i);
			itemReferencias.getItemProperty("id").setValue(
					documentos.get(i).getId());
			itemReferencias.getItemProperty("estado").setValue(
					SigeUtil.asignarEstado(docDestino.getTipoMovimiento(),
							docDestino.getRecepcionadoPor() == null ? ""
									: docDestino.getRecepcionadoPor()));
			itemReferencias.getItemProperty("documento").setValue(
					tipoDocumentoService.obtenerTipoDocumento(
							documentos.get(i).getCodigoTipoDocumento())
							.getNombre());
			itemReferencias.getItemProperty("fechaEnvio").setValue(
					documentos.get(i).getFechadocumento());
			itemReferencias.getItemProperty("dependenciaOrigen").setValue(
					dependenciaServicio.obtener(
							documentos.get(i).getDependencia().getId())
							.getNombre());
			itemReferencias.getItemProperty("dependenciaDestino").setValue(
					dependenciaServicio.obtener(
							docDestino.getDependencia().getId()).getNombre());
			itemReferencias.getItemProperty("asunto").setValue(
					documentos.get(i).getAsunto());
		}
	}

	public String obtenerFormatoFecha(Timestamp Fecha) {
		String fecha = null;
		try {
			fecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(Fecha);

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return fecha;
	}

	public Boolean validarIgualdadDocumentosInternos(
			DocumentoInterno docInternoExistente,
			DocumentoInterno docInternoEliminar) {
		Boolean sonIguales = false;

		return sonIguales;
	}

	@Override
	public void buttonClick(ClickEvent event) {
		// TODO Auto-generated method stub
		if (event.getSource() == this.btnCerrar) {
			UI.getCurrent().removeWindow(windowContiene);
		} else if (event.getSource() == this.btnBuscarDependencia) {
			Window ventana = SigeUtil.generarBuscador(new Window(),
					"BUSCAR DEPENDENCIAS", "645px", "375px");
			ventana.setContent(new DependenciaBuscar(ventana, this));
			UI.getCurrent().addWindow(ventana);
		} else if (event.getSource() == this.btnBuscarDocumento) {

			Window ventana = SigeUtil.generarBuscador(new Window(),
					"BUSCAR DOCUMENTOS", "560px", "320px");
			ventana.setContent(new TipoDocumentoBuscar(ventana, this));
			UI.getCurrent().addWindow(ventana);
		} else if (event.getSource() == this.btnAgregarDocumento) {
			if (cbxExpediente.getValue() != null) {
				Window ventana = SigeUtil.generarBuscador(new Window(),
						"BUSCAR DOCUMENTOS", "460px", "360px");
				ventana.setContent(new PlantillaBuscar(this, ventana,
						expedienteService.obtener((Long) cbxExpediente
								.getValue()), dependenciaOrigen));
				UI.getCurrent().addWindow(ventana);
			} else {
				Notificacion.show(new Notificacion(
						"Debe seleccionar un expediente",
						Constantes.MENSAJE.TYPE_ERROR));
			}
		} else if (event.getSource() == this.btnEliminar) {

			if (expedienteDocumentoSeleccionado != null) {
				ConfirmDialog.show(UI.getCurrent(), "Confirmación",
						"¿Desea elminar el Documento?", "Aceptar", "Cancelar",
						new ConfirmDialog.Listener() {
							private static final long serialVersionUID = 1L;

							public void onClose(ConfirmDialog dialog) {

								if (dialog.isConfirmed()) {
									Long idExpedienteDocumento;
									expedienteDocumentoSeleccionado
											.setEstado(Boolean.FALSE);
									expedienteDocumentoService
											.actualizar(expedienteDocumentoSeleccionado);
									for (Object id : tblDocumentos.getItemIds()) {
										idExpedienteDocumento = (Long) tblDocumentos
												.getItem(id)
												.getItemProperty("id")
												.getValue();
										if (idExpedienteDocumento
												.equals(expedienteDocumentoSeleccionado
														.getId())) {
											tblDocumentos.removeItem(id);
											break;
										}
									}

									Notificacion
											.show(new Notificacion(
													"Se elimino correctamente el documento",
													Constantes.MENSAJE.TYPE_SUCCES));

								}

							}
						});
			} else {

				Notificacion.show(new Notificacion(
						"Seleccione un documento para eliminar",
						Constantes.MENSAJE.TYPE_ERROR));
			}

		} else if (event.getSource() == this.btnDescargar) {

			if (expedienteDocumentoSeleccionado != null) {
				FormSenderBuilder
						.create()
						.withUI(getUI())
						.withAction("./DescargarArchivo")
						.withMethod(Method.POST)
						.withValue(
								"fileLocation",
								Constantes.FILE_LOCATION.FILE_LOCATION_DOCUMENTOS)
						.withValue(
								"fileName",
								expedienteDocumentoSeleccionado
										.getNombreArchivo()).submit();

			} else {
				Notificacion.show(new Notificacion(
						"Debe seleccionar un documento",
						Constantes.MENSAJE.TYPE_ERROR));
			}
		} else if (event.getSource() == this.btnAgregarExpedienteExterno) {
			ExpedienteCanonico expedienteBuscar = new ExpedienteCanonico();
			expedienteBuscar.setTipoBusqueda(1);
			// Dependencia dependencia = dependenciaServicio.obtener();
			expedienteBuscar.setDependenciaEntidad(expedienteCanonico
					.getDependenciaEntidad());
			Long codExpediente = null;
			Expediente expediente = null;
			ExpedienteMovimiento expedienteMov = null;
			List<String> codigosExpediente = new ArrayList<String>();
			List<Long> codigosMov = new ArrayList<Long>();
			for (Object id : tbExpedienteExterno.getItemIds()) {
				expediente = new Expediente();
				expedienteMov = new ExpedienteMovimiento();
				expediente = expedienteService.obtener(Long
						.parseLong(tbExpedienteExterno.getItem(id)
								.getItemProperty("id").getValue().toString()));
				codigosExpediente.add(expediente.getCodigo());
				expedienteMov = expedienteMovimientoService
						.obtenerExpedienteMovimiento(expediente.getCodigo());
				codigosMov.add(expedienteMov.getId());
			}
			expedienteBuscar.setExpedientesRepetidos(codigosExpediente);
			expedienteBuscar.setCodigoMovimientos(codigosMov);
			// expedienteCanonico.setExpediente(expediente);

			Window ventana = SigeUtil.generarBuscador(new Window(),
					"BUSCAR EXPEDIENTE", "670px", "390px");

			ExpedienteDependenciaBuscar expedienteDependenciaBuscar = new ExpedienteDependenciaBuscar(
					ventana, this, expedienteBuscar);
			ventana.setContent(expedienteDependenciaBuscar);
			UI.getCurrent().addWindow(ventana);
			expedienteDependenciaBuscar.getAllExpedientes();
		} else if (event.getSource() == this.btnAgregarReferencia) {
			ExpedienteCanonico expedienteDocumento = new ExpedienteCanonico();
			expedienteDocumento.setDependenciaEntidad(expedienteCanonico
					.getDependenciaEntidad());
			Long codDocumento = null;
			List<Long> codigosDocumento = new ArrayList<Long>();
			for (Object id : tbReferencias.getItemIds()) {
				codDocumento = Long.parseLong(tbReferencias.getItem(id)
						.getItemProperty("id").toString());
				codigosDocumento.add(codDocumento);
			}
			// expedienteDocumento.setDocumentosRepetidos(codigosDocumento);

			Window ventana = SigeUtil.generarBuscador(new Window(),
					"BUSCAR DOCUMENTOS", "760px", "380px");
			ventana.setContent(new DocumentoInternoBuscar(ventana, this,
					expedienteDocumento));
			UI.getCurrent().addWindow(ventana);
		} else if (event.getSource() == this.btnQuitarExpedienteExterno) {
			if (expedienteEstaSeleccionado) {
				ConfirmDialog.show(UI.getCurrent(), "Confirmación",
						"¿Desea quitar el expediente seleccionado?", "Aceptar",
						"Cancelar", new ConfirmDialog.Listener() {
							private static final long serialVersionUID = 1L;

							public void onClose(ConfirmDialog dialog) {
								if (dialog.isConfirmed()) {
									Long numeroExpedientes = 0L;
									for (Object id : tbExpedienteExterno
											.getItemIds()) {
										numeroExpedientes++;
									}
									if (numeroExpedientes == 1) {
										Notificacion
												.show(new Notificacion(
														"Debe haber al menos un expediente",
														Constantes.MENSAJE.TYPE_ERROR));
									} else {
										quitarExpediente();
									}
								}
							}
						});

				tbExpedienteExterno.unselect(tbExpedienteExterno.getValue());
				expedienteEstaSeleccionado = false;
			} else {
				Notificacion.show(new Notificacion(
						"Debe Seleccionar un Expediente de la tabla",
						Constantes.MENSAJE.TYPE_WARNING));
			}
		} else if (event.getSource() == this.btnQuitarReferencia) {
			if (documentoEstaSeleccionado) {
				ConfirmDialog.show(UI.getCurrent(), "Confirmación",
						"¿Desea quitar el documento seleccionado?", "Aceptar",
						"Cancelar", new ConfirmDialog.Listener() {
							private static final long serialVersionUID = 1L;

							public void onClose(ConfirmDialog dialog) {
								if (dialog.isConfirmed()) {
									Long numeroDocumentos = 0L;
									for (Object id : tbReferencias.getItemIds()) {
										numeroDocumentos++;
									}
									if (numeroDocumentos == 1) {
										Notificacion
												.show(new Notificacion(
														"Debe haber al menos un documento",
														Constantes.MENSAJE.TYPE_ERROR));
									} else {
										quitarDocumento();
									}
								}
							}
						});
				tbReferencias.unselect(tbReferencias.getValue());
				documentoEstaSeleccionado = false;
			} else {
				Notificacion.show(new Notificacion(
						"Debe Seleccionar un documento de la tabla",
						Constantes.MENSAJE.TYPE_WARNING));
			}
		} else if (event.getSource() == this.btnGrabar) {
			if (SigeUtil.validarCamposTexto(txtNumeroDocumento,
					txtDependenciaDestino)
					&& !txtAAsunto.getValue().toString().equals("")) {
				for (Object o : tblDocumentos.getItemIds()) {
					if (!((Boolean) tblDocumentos.getItem(o)
							.getItemProperty("cargado").getValue())) {
						Notificacion
								.show(new Notificacion(
										"Debe cargar todos los documentos seleccionados",
										Constantes.MENSAJE.TYPE_ERROR));
						return;
					}
				}

				if (expedienteCanonico.getDerivar()) {
					ConfirmDialog.show(UI.getCurrent(), "Confirmación",
							"¿Desea Derivar el expediente?", "Aceptar",
							"Cancelar", new ConfirmDialog.Listener() {

								@Override
								public void onClose(ConfirmDialog dialog) {
									// TODO Auto-generated method stub
									if (dialog.isConfirmed()) {

										derivarExpediente();

									}
								}
							});
				} else {
					ConfirmDialog.show(UI.getCurrent(), "Confirmación",
							"¿Desea Responder el expediente?", "Aceptar",
							"Cancelar", new ConfirmDialog.Listener() {

								@Override
								public void onClose(ConfirmDialog dialog) {
									// TODO Auto-generated method stub
									if (dialog.isConfirmed()) {

										responderExpediente();

									}
								}
							});
				}
			} else {
				Notificacion.show(new Notificacion(
						"Debe rellenar todos los campos",
						Constantes.MENSAJE.TYPE_ERROR));
			}

		}
	}

	public void responderExpediente() {
		DocumentoInterno documentoInternoResponder = new DocumentoInterno();
		documentoInternoResponder.setCodigodocumento(SigeUtil.completarCeros(
				docInternoService.obtenerUltimoCorrelativo().toString(), 8, 1));
		documentoInternoResponder.setDependencia(dependenciaOrigen);
		documentoInternoResponder.setCodigoTipoDocumento(tipoDocumentoObtenido
				.getCodigoTipoDocumento());
		documentoInternoResponder.setNumerodocumento(this.txtNumeroDocumento
				.getValue().toString());
		documentoInternoResponder.setAñoDocumento(this.txtAnioDocumento
				.getValue().toString());
		documentoInternoResponder.setSiglasdocumento(this.txtSiglasDocumento
				.getValue().toString().toUpperCase());
		documentoInternoResponder.setNumerofolios(Short
				.parseShort(this.txtFolios.getValue().toString()));
		documentoInternoResponder.setFechadocumento(Timestamp
				.valueOf(this.popDateFecha.getValue().toString()));
		documentoInternoResponder.setAsunto(this.txtAAsunto.getValue()
				.toString().toUpperCase());
		documentoInternoResponder.setCopiaArchivo(chkCopiaArchivo.getValue());
		DocumentoInternoDestino docDestinoResponder = new DocumentoInternoDestino();
		docDestinoResponder.setDocumentoInterno(documentoInternoResponder);
		docDestinoResponder.setDependencia(docInterno.getDependencia());
		docDestinoResponder.setOrden(new Short("1"));
		docDestinoResponder.setTipoMovimiento('0');
		List<ExpedienteMovimiento> expedientesMov = new ArrayList<ExpedienteMovimiento>();
		Expediente expediente = null;
		ExpedienteMovimiento expedienteMov = null;
		Integer orden = 1;
		Integer contador = 0;

		for (Object id : tbExpedienteExterno.getItemIds()) {

			expediente = new Expediente();
			expedienteMov = new ExpedienteMovimiento();
			expediente = expedienteService.obtener(Long
					.parseLong(tbExpedienteExterno.getItem(id)
							.getItemProperty("id").getValue().toString()));
			logger.info("expediente" + expediente.getCodigo());
			expedienteMov.setExpediente(expediente);
			expedienteMov.setDependencia(docInterno.getDependencia());
			expedienteMov.setDocumentoInterno(documentoInternoResponder);
			expedienteMov.setOrden(orden++);
			expedienteMov.setCorrelativo(expedienteMovimientoService
					.obtenerCorrelativoPorExpediente(expediente));
			expedienteMov.setEscopia('0');
			expedientesMov.add(expedienteMov);
			contador++;
		}
		orden = 1;
		DocumentoInterno referencia = null;
		DocumentoInternoReferen docInternoReferencia = null;
		List<DocumentoInternoReferen> docReferencias = new ArrayList<DocumentoInternoReferen>();
		List<DocumentoInternoDestino> docsDestino = new ArrayList<DocumentoInternoDestino>();
		DocumentoInternoDestino docDestino = null;
		for (Object id : tbReferencias.getItemIds()) {
			docDestino = new DocumentoInternoDestino();
			referencia = new DocumentoInterno();
			docInternoReferencia = new DocumentoInternoReferen();
			referencia = docInternoService.obtener(Long.parseLong(tbReferencias
					.getItem(id).getItemProperty("id").getValue().toString()));
			// docDestino = docInternoDestinoService
			// .obtenerDocInternoDestinoPorDocInterno(referencia
			// .getCodigodocumento());
			// docsDestino.add(docDestino);
			docInternoReferencia.setCodigoDocumento(documentoInternoResponder
					.getCodigodocumento());
			docInternoReferencia.setCodigoDocumentoReferencia(referencia
					.getCodigodocumento());
			docInternoReferencia
					.setCodigoDependencia(dependenciaOrigen.getId());
			docInternoReferencia.setOrden(Short.parseShort(orden.toString()));
			docReferencias.add(docInternoReferencia);
			orden++;

		}
		expedienteService.responderExpediente(expedientesMov,
				documentoInternoResponder, docDestinoResponder, docReferencias);

		docInternoDestino.setTipoMovimiento('1');
		docInternoDestinoService.actualizar(docInternoDestino);
		if (quienLlama instanceof MovimientoExpedienteProceso) {
			MovimientoExpedienteProceso panel = (MovimientoExpedienteProceso) quienLlama;
			panel.mostrarMensajeExitoDerivar(txtDependenciaDestino.getValue()
					.toString(), contador, 0);
			UI.getCurrent().removeWindow(windowContiene);
		}

	}

	public void derivarExpediente() {
		DocumentoInterno documentoInternoDerivar = new DocumentoInterno();
		documentoInternoDerivar.setCodigodocumento(SigeUtil.completarCeros(
				docInternoService.obtenerUltimoCorrelativo().toString(), 8, 1));
		documentoInternoDerivar.setDependencia(dependenciaOrigen);
		documentoInternoDerivar.setCodigoTipoDocumento(tipoDocumentoObtenido
				.getCodigoTipoDocumento());
		documentoInternoDerivar.setNumerodocumento(this.txtNumeroDocumento
				.getValue().toString());
		documentoInternoDerivar.setAñoDocumento(this.txtAnioDocumento
				.getValue().toString());
		documentoInternoDerivar.setSiglasdocumento(this.txtSiglasDocumento
				.getValue().toString().toUpperCase());
		documentoInternoDerivar.setNumerofolios(Short.parseShort(this.txtFolios
				.getValue().toString()));
		documentoInternoDerivar.setFechadocumento(Timestamp
				.valueOf(this.popDateFecha.getValue().toString()));
		documentoInternoDerivar.setAsunto(this.txtAAsunto.getValue().toString()
				.toUpperCase());
		documentoInternoDerivar.setCopiaArchivo(chkCopiaArchivo.getValue());
		DocumentoInternoDestino docDestinoDerivar = new DocumentoInternoDestino();
		docDestinoDerivar.setDocumentoInterno(documentoInternoDerivar);
		docDestinoDerivar.setDependencia(dependenciaObtenida);
		docDestinoDerivar.setOrden(new Short("1"));
		docDestinoDerivar.setTipoMovimiento('0');
		List<ExpedienteMovimiento> expedientesMov = new ArrayList<ExpedienteMovimiento>();
		Expediente expediente = null;
		ExpedienteMovimiento expedienteMov = null;
		Integer orden = 1;
		Integer contador = 0;
		for (Object id : tbExpedienteExterno.getItemIds()) {
			expediente = new Expediente();
			expedienteMov = new ExpedienteMovimiento();
			expediente = expedienteService.obtener(Long
					.parseLong(tbExpedienteExterno.getItem(id)
							.getItemProperty("id").getValue().toString()));
			logger.info("expediente" + expediente.getCodigo());
			expedienteMov.setExpediente(expediente);
			expedienteMov.setDependencia(dependenciaObtenida);
			expedienteMov.setDocumentoInterno(documentoInternoDerivar);
			expedienteMov.setOrden(orden++);
			expedienteMov.setCorrelativo(expedienteMovimientoService
					.obtenerCorrelativoPorExpediente(expediente));
			expedienteMov.setEscopia('0');
			expedientesMov.add(expedienteMov);
			contador++;
		}
		orden = 1;
		DocumentoInterno referencia = null;
		DocumentoInternoReferen docInternoReferencia = null;
		List<DocumentoInternoReferen> docReferencias = new ArrayList<DocumentoInternoReferen>();
		for (Object id : tbReferencias.getItemIds()) {
			referencia = new DocumentoInterno();
			docInternoReferencia = new DocumentoInternoReferen();
			referencia = docInternoService.obtener(Long.parseLong(tbReferencias
					.getItem(id).getItemProperty("id").getValue().toString()));
			docInternoReferencia.setCodigoDocumento(documentoInternoDerivar
					.getCodigodocumento());
			docInternoReferencia.setCodigoDocumentoReferencia(referencia
					.getCodigodocumento());
			docInternoReferencia
					.setCodigoDependencia(dependenciaOrigen.getId());
			docInternoReferencia.setOrden(Short.parseShort(orden.toString()));
			docReferencias.add(docInternoReferencia);
			orden++;

		}
		expedienteService.derivarExpediente(expedientesMov,
				documentoInternoDerivar, docDestinoDerivar, docReferencias);
		docInternoDestino.setTipoMovimiento('2');
		docInternoDestinoService.actualizar(docInternoDestino);
		if (quienLlama instanceof MovimientoExpedienteProceso) {
			MovimientoExpedienteProceso panel = (MovimientoExpedienteProceso) quienLlama;
			panel.mostrarMensajeExitoDerivar(dependenciaObtenida.getNombre(),
					contador, 1);
			UI.getCurrent().removeWindow(windowContiene);
		}
	}

	public void quitarDocumento() {
		List<DocumentoInterno> documentos = new ArrayList<DocumentoInterno>();
		DocumentoInterno documentoInterno = null;
		for (Object id : tbReferencias.getItemIds()) {
			documentoInterno = new DocumentoInterno();
			documentoInterno = docInternoService.obtener(Long
					.parseLong(tbReferencias.getItem(id).getItemProperty("id")
							.getValue().toString()));
			if (documentoInterno.getId() != documentoInternoSeleccionado
					.getId()) {
				documentos.add(documentoInterno);
			}
		}
		getAllReferencias(documentos);
	}

	@SuppressWarnings("unchecked")
	public void quitarExpediente() {
		List<Expediente> expedientes = new ArrayList<Expediente>();
		Expediente expediente = null;
		for (Object id : tbExpedienteExterno.getItemIds()) {
			expediente = new Expediente();
			expediente = expedienteService.obtener(Long
					.parseLong(tbExpedienteExterno.getItem(id)
							.getItemProperty("id").getValue().toString()));
			if (expediente.getId() != expedienteSeleccionado.getId()) {
				expedientes.add(expediente);
			}
		}
		cbxExpediente.removeItem(expedienteSeleccionado.getId());
		IndexedContainer contenedorExpedientes = (IndexedContainer) tbExpedienteExterno
				.getContainerDataSource();
		contenedorExpedientes.removeAllItems();
		cantAnexosExpediente = 0;
		for (int i = 0; i < expedientes.size(); i++) {
			cantAnexosExpediente += anexoPresentadoService
					.obtenerCantidadAnexosDeExpediente(expedientes.get(i));

			Item item = contenedorExpedientes.addItem(i);
			item.getItemProperty("id").setValue(expedientes.get(i).getId());
			item.getItemProperty("numero").setValue(
					expedientes.get(i).getNumero());
			item.getItemProperty("anio").setValue(expedientes.get(i).getAnio());
		}
		lblExpedientesAnexados.setValue(cantAnexosExpediente
				+ " Expedientes Anexados");
		quitarDocInternoExpediente(expedienteSeleccionado);
	}

	public void obtenerPlantilla(Long idPlantilla, Long idExpediente) {
		DependenciaTipoTramitePlantilla dpttp = dependenciaTipoTramitePlantillaService
				.obtener(idPlantilla);

		IndexedContainer container = (IndexedContainer) tblDocumentos
				.getContainerDataSource();
		Item item = container.addItem(String.valueOf(idPlantilla)
				+ String.valueOf(idExpediente));
		String fileName;
		if (item != null) {

			try {
				fileName = "E"
						+ SigeUtil.completarCeros(String.valueOf(idExpediente),
								8, 1) + "-" + dpttp.getNombreArchivo();
				File origen = new File(
						Constantes.FILE_LOCATION.FILE_LOCATION_PLANTILLAS
								+ dpttp.getNombreArchivo());
				File destination = new File(
						Constantes.FILE_LOCATION.FILE_LOCATION_DOCUMENTOS
								+ fileName);

				FileUtils.copyFile(origen, destination);

				ExpedienteDocumento expedienteDocumento = new ExpedienteDocumento();
				expedienteDocumento.setNombreArchivo(fileName);
				expedienteDocumento.setDependencia(dpttp
						.getDependenciaTipoTramite().getDependencia());
				expedienteDocumento.setExpediente(expedienteService
						.obtener(idExpediente));
				expedienteDocumento.setDependenciaTipoTramitePlantilla(dpttp);
				expedienteDocumentoService.crear(expedienteDocumento);

				item.getItemProperty("id")
						.setValue(expedienteDocumento.getId());
				item.getItemProperty("item").setValue(
						new Long(container.size()));
				item.getItemProperty("documento").setValue(
						dpttp.getNombrePlantilla());
				item.getItemProperty("archivo").setValue(
						expedienteDocumento.getNombreArchivo());
				item.getItemProperty("cargado").setValue(Boolean.FALSE);
			} catch (IOException e) {
				Notificacion
						.show(new Notificacion(
								"No se Pudo agregar el documento , porfavor intente nuevamente",
								Constantes.MENSAJE.TYPE_ERROR));
				tblDocumentos.removeItem(String.valueOf(idPlantilla)
						+ String.valueOf(idExpediente));

			}
		} else {
			Notificacion.show(new Notificacion("El Documento ya fue agregado",
					Constantes.MENSAJE.TYPE_ERROR));
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("<b>Dependencia Origen:");
		mainLayout.addComponent(label_1, "top:20.0px;left:20.0px;");

		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("<b>Fecha Env&iacute;o:");
		mainLayout.addComponent(label_2, "top:20.0px;left:520.0px;");

		// lblDependenciaOrigen
		lblDependenciaOrigen = new Label();
		lblDependenciaOrigen.setImmediate(false);
		lblDependenciaOrigen.setWidth("360px");
		lblDependenciaOrigen.setHeight("-1px");
		lblDependenciaOrigen.setValue("Dependencia origen");
		mainLayout.addComponent(lblDependenciaOrigen,
				"top:20.0px;left:140.0px;");

		// lblFechaEnvio
		lblFechaEnvio = new Label();
		lblFechaEnvio.setImmediate(false);
		lblFechaEnvio.setWidth("200px");
		lblFechaEnvio.setHeight("-1px");
		lblFechaEnvio.setValue("Fecha envío");
		mainLayout.addComponent(lblFechaEnvio, "top:20.0px;left:600.0px;");

		// lblDocumento
		lblDocumento = new Label();
		lblDocumento.setImmediate(false);
		lblDocumento.setWidth("-1px");
		lblDocumento.setHeight("-1px");
		lblDocumento.setValue("<b>Documento:");
		mainLayout.addComponent(lblDocumento, "top:60.0px;left:20.0px;");

		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Tipo: ");
		mainLayout.addComponent(label_3, "top:60.0px;left:100.0px;");

		// btnBuscarDocumento
		btnBuscarDocumento = new Boton();
		btnBuscarDocumento
				.setIcon(new ThemeResource("images/botones/find.png"));
		btnBuscarDocumento.setImmediate(false);
		btnBuscarDocumento.setWidth("30px");
		btnBuscarDocumento.setHeight("25px");
		mainLayout.addComponent(btnBuscarDocumento, "top:57.0px;left:380.0px;");

		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Nro:");
		mainLayout.addComponent(label_4, "top:60.0px;left:437.0px;");

		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("A&ntilde;o:");
		mainLayout.addComponent(label_5, "top:60.0px;left:576.0px;");

		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Siglas:");
		mainLayout.addComponent(label_6, "top:60.0px;left:680.0px;");

		// txtSiglasDocumento
		txtSiglasDocumento = new TextField();
		txtSiglasDocumento.setImmediate(false);
		txtSiglasDocumento.setWidth("80px");
		txtSiglasDocumento.setHeight("-1px");
		mainLayout.addComponent(txtSiglasDocumento, "top:56.0px;left:720.0px;");

		// txtAnioDocumento
		txtAnioDocumento = new TextField();
		txtAnioDocumento.setImmediate(false);
		txtAnioDocumento.setWidth("57px");
		txtAnioDocumento.setHeight("-1px");
		mainLayout.addComponent(txtAnioDocumento, "top:57.0px;left:603.0px;");

		// txtNumeroDocumento
		txtNumeroDocumento = new TextField();
		txtNumeroDocumento.setImmediate(false);
		txtNumeroDocumento.setWidth("100px");
		txtNumeroDocumento.setHeight("-1px");
		mainLayout.addComponent(txtNumeroDocumento, "top:56.0px;left:460.0px;");

		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Fecha: ");
		mainLayout.addComponent(label_7, "top:100.0px;left:100.0px;");

		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("Folios: ");
		mainLayout.addComponent(label_8, "top:100.0px;left:300.0px;");

		// popDateFecha
		popDateFecha = new PopupDateField();
		popDateFecha.setImmediate(false);
		popDateFecha.setWidth("120px");
		popDateFecha.setHeight("-1px");
		mainLayout.addComponent(popDateFecha, "top:100.0px;left:140.0px;");

		// txtFolios
		txtFolios = new TextField();
		txtFolios.setImmediate(false);
		txtFolios.setWidth("70px");
		txtFolios.setHeight("-1px");
		mainLayout.addComponent(txtFolios, "top:100.0px;left:340.0px;");

		// label_9
		label_9 = new Label();
		label_9.setImmediate(false);
		label_9.setWidth("80px");
		label_9.setHeight("-1px");
		label_9.setValue("<b>Dependencia Destino: ");
		mainLayout.addComponent(label_9, "top:125.0px;left:20.0px;");

		// txtDependenciaDestino
		txtDependenciaDestino = new TextField();
		txtDependenciaDestino.setImmediate(false);
		txtDependenciaDestino.setWidth("480px");
		txtDependenciaDestino.setHeight("-1px");
		mainLayout.addComponent(txtDependenciaDestino,
				"top:136.0px;left:100.0px;");

		// btnBuscarDependencia
		btnBuscarDependencia = new Boton();
		btnBuscarDependencia.setIcon(new ThemeResource(
				"images/botones/find.png"));
		btnBuscarDependencia.setImmediate(false);
		btnBuscarDependencia.setDescription("Buscar Dependencia");
		btnBuscarDependencia.setWidth("30px");
		btnBuscarDependencia.setHeight("25px");
		mainLayout.addComponent(btnBuscarDependencia,
				"top:136.0px;left:580.0px;");

		// label_12
		label_12 = new Label();
		label_12.setImmediate(false);
		label_12.setWidth("-1px");
		label_12.setHeight("-1px");
		label_12.setValue("<b>Asunto: ");
		mainLayout.addComponent(label_12, "top:410.0px;left:20.0px;");

		// txtAAsunto
		txtAAsunto = new TextArea();
		txtAAsunto.setImmediate(false);
		txtAAsunto.setWidth("660px");
		txtAAsunto.setHeight("50px");
		mainLayout.addComponent(txtAAsunto, "top:410.0px;left:100.0px;");

		// label_13
		label_13 = new Label();
		label_13.setImmediate(false);
		label_13.setWidth("-1px");
		label_13.setHeight("-1px");
		label_13.setValue("<b>Enviado Por: ");
		mainLayout.addComponent(label_13, "top:472.0px;left:500.0px;");

		// chkCopiaArchivo
		chkCopiaArchivo = new CheckBox();
		chkCopiaArchivo.setCaption("Copia a Archivo");
		chkCopiaArchivo.setImmediate(false);
		chkCopiaArchivo.setWidth("-1px");
		chkCopiaArchivo.setHeight("-1px");
		mainLayout.addComponent(chkCopiaArchivo, "top:474.0px;left:20.0px;");

		// btnGrabar
		btnGrabar = new Button();
		btnGrabar.setCaption("Guardar");
		btnGrabar.setIcon(new ThemeResource("images/botones/save.png"));
		btnGrabar.setImmediate(true);
		btnGrabar.setWidth("110px");
		btnGrabar.setHeight("-1px");
		mainLayout.addComponent(btnGrabar, "top:504.0px;left:300.0px;");

		// btnCerrar
		btnCerrar = new Button();
		btnCerrar.setCaption("Salir");
		btnCerrar.setIcon(new ThemeResource("images/botones/close.png"));
		btnCerrar.setImmediate(true);
		btnCerrar.setWidth("110px");
		btnCerrar.setHeight("-1px");
		mainLayout.addComponent(btnCerrar, "top:504.0px;left:420.0px;");

		// txtTipoDocumento
		txtTipoDocumento = new TextField();
		txtTipoDocumento.setImmediate(false);
		txtTipoDocumento.setWidth("253px");
		txtTipoDocumento.setHeight("-1px");
		mainLayout.addComponent(txtTipoDocumento, "top:56.0px;left:127.0px;");

		// lblEnviadoPor
		lblEnviadoPor = new Label();
		lblEnviadoPor.setImmediate(false);
		lblEnviadoPor.setWidth("-1px");
		lblEnviadoPor.setHeight("-1px");
		lblEnviadoPor.setValue("Supervisor");
		mainLayout.addComponent(lblEnviadoPor, "top:472.0px;left:580.0px;");

		// tabReferenciaDocumentos
		tabReferenciaDocumentos = buildTabReferenciaDocumentos();
		mainLayout.addComponent(tabReferenciaDocumentos,
				"top:171.0px;left:20.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabReferenciaDocumentos() {
		// common part: create layout
		tabReferenciaDocumentos = new TabSheet();
		tabReferenciaDocumentos.setImmediate(true);
		tabReferenciaDocumentos.setWidth("780px");
		tabReferenciaDocumentos.setHeight("229px");

		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		tabReferenciaDocumentos.addTab(absoluteLayout_2,
				"Expediente Orignal/Referencia", null);

		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		tabReferenciaDocumentos.addTab(absoluteLayout_3, "Documentos", null);

		return tabReferenciaDocumentos;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("100.0%");

		// label_10
		label_10 = new Label();
		label_10.setImmediate(false);
		label_10.setWidth("68px");
		label_10.setHeight("-1px");
		label_10.setValue("<b>Expediente Externo Original: ");
		absoluteLayout_2.addComponent(label_10, "top:8.0px;left:6.0px;");

		// tbExpedienteExterno
		tbExpedienteExterno = new Table();
		tbExpedienteExterno.setImmediate(false);
		tbExpedienteExterno.setWidth("270px");
		tbExpedienteExterno.setHeight("84px");
		absoluteLayout_2.addComponent(tbExpedienteExterno,
				"top:4.0px;left:80.0px;");

		// btnAgregarExpedienteExterno
		btnAgregarExpedienteExterno = new Boton();
		btnAgregarExpedienteExterno.setIcon(new ThemeResource(
				"images/botones/add.png"));
		btnAgregarExpedienteExterno.setImmediate(false);
		btnAgregarExpedienteExterno.setWidth("30px");
		btnAgregarExpedienteExterno.setHeight("25px");
		absoluteLayout_2.addComponent(btnAgregarExpedienteExterno,
				"top:25.0px;left:349.0px;");

		// btnQuitarExpedienteExterno
		btnQuitarExpedienteExterno = new Boton();
		btnQuitarExpedienteExterno.setIcon(new ThemeResource(
				"images/botones/remove.png"));
		btnQuitarExpedienteExterno.setImmediate(false);
		btnQuitarExpedienteExterno.setDescription("Quitar");
		btnQuitarExpedienteExterno.setWidth("30px");
		btnQuitarExpedienteExterno.setHeight("25px");
		absoluteLayout_2.addComponent(btnQuitarExpedienteExterno,
				"top:50.0px;left:350.0px;");

		// lblExpedientesAnexados
		lblExpedientesAnexados = new Label();
		lblExpedientesAnexados.setImmediate(false);
		lblExpedientesAnexados.setWidth("-1px");
		lblExpedientesAnexados.setHeight("-1px");
		lblExpedientesAnexados.setValue("0 Expedientes Anexados");
		absoluteLayout_2.addComponent(lblExpedientesAnexados,
				"top:73.0px;left:350.0px;");

		// label_11
		label_11 = new Label();
		label_11.setImmediate(false);
		label_11.setWidth("-1px");
		label_11.setHeight("-1px");
		label_11.setValue("<b>Referencia: ");
		absoluteLayout_2.addComponent(label_11, "top:97.0px;left:0.0px;");

		// tbReferencias
		tbReferencias = new Table();
		tbReferencias.setImmediate(false);
		tbReferencias.setWidth("652px");
		tbReferencias.setHeight("85px");
		absoluteLayout_2
				.addComponent(tbReferencias, "top:103.0px;left:87.0px;");

		// btnAgregarReferencia
		btnAgregarReferencia = new Boton();
		btnAgregarReferencia
				.setIcon(new ThemeResource("images/botones/add.png"));
		btnAgregarReferencia.setImmediate(false);
		btnAgregarReferencia.setDescription("Agregar");
		btnAgregarReferencia.setWidth("30px");
		btnAgregarReferencia.setHeight("25px");
		absoluteLayout_2.addComponent(btnAgregarReferencia,
				"top:140.0px;left:739.0px;");

		// btnQuitarReferencia
		btnQuitarReferencia = new Boton();
		btnQuitarReferencia.setIcon(new ThemeResource(
				"images/botones/remove.png"));
		btnQuitarReferencia.setImmediate(false);
		btnQuitarReferencia.setDescription("Quitar");
		btnQuitarReferencia.setWidth("30px");
		btnQuitarReferencia.setHeight("25px");
		absoluteLayout_2.addComponent(btnQuitarReferencia,
				"top:163.0px;left:739.0px;");

		return absoluteLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("100.0%");
		absoluteLayout_3.setHeight("100.0%");

		// lblExpediente
		lblExpediente = new Label();
		lblExpediente.setImmediate(false);
		lblExpediente.setWidth("-1px");
		lblExpediente.setHeight("-1px");
		lblExpediente.setValue("Expediente :");
		absoluteLayout_3.addComponent(lblExpediente, "top:6.0px;left:9.0px;");

		// cbxExpediente
		cbxExpediente = new ComboBox();
		cbxExpediente.setImmediate(false);
		cbxExpediente.setWidth("338px");
		cbxExpediente.setHeight("-1px");
		absoluteLayout_3.addComponent(cbxExpediente, "top:6.0px;left:81.0px;");

		// tblDocumentos
		tblDocumentos = new Table();
		tblDocumentos.setImmediate(false);
		tblDocumentos.setWidth("750px");
		tblDocumentos.setHeight("132px");
		absoluteLayout_3.addComponent(tblDocumentos, "top:33.0px;left:15.0px;");

		// btnAgregarDocumento
		btnAgregarDocumento = new Button();
		btnAgregarDocumento.setCaption("Agregar Documento");
		btnAgregarDocumento
				.setIcon(new ThemeResource("images/botones/add.png"));
		btnAgregarDocumento.setImmediate(true);
		btnAgregarDocumento.setWidth("-1px");
		btnAgregarDocumento.setHeight("-1px");
		absoluteLayout_3.addComponent(btnAgregarDocumento,
				"top:168.0px;left:55.0px;");

		// progressLayout
		progressLayout = new HorizontalLayout();
		progressLayout.setImmediate(false);
		progressLayout.setWidth("148px");
		progressLayout.setHeight("28px");
		progressLayout.setMargin(false);
		absoluteLayout_3.addComponent(progressLayout,
				"top:165.0px;left:539.0px;");

		// upload
		upload = new Upload(null, receiver);
		upload.setImmediate(false);
		upload.setWidth("-1px");
		upload.setHeight("32px");
		absoluteLayout_3.addComponent(upload, "top:168.0px;left:651.0px;");

		// cancelProcessing
		cancelProcessing = new Button();
		cancelProcessing.setCaption("Cancelar");
		cancelProcessing.setImmediate(true);
		cancelProcessing.setWidth("-1px");
		cancelProcessing.setHeight("-1px");
		absoluteLayout_3.addComponent(cancelProcessing,
				"top:171.0px;left:692.0px;");

		// btnDescargar
		btnDescargar = new Button();
		btnDescargar.setCaption("Descargar");
		btnDescargar.setIcon(new ThemeResource("images/botones/down.png"));
		btnDescargar.setImmediate(true);
		btnDescargar.setWidth("110px");
		btnDescargar.setHeight("-1px");
		absoluteLayout_3
				.addComponent(btnDescargar, "top:167.0px;left:242.0px;");

		// btnEliminar
		btnEliminar = new Button();
		btnEliminar.setCaption("Eliminar");
		btnEliminar.setIcon(new ThemeResource("images/botones/remove.png"));
		btnEliminar.setImmediate(true);
		btnEliminar.setWidth("110px");
		btnEliminar.setHeight("-1px");
		absoluteLayout_3.addComponent(btnEliminar, "top:168.0px;left:389.0px;");

		return absoluteLayout_3;
	}

}
