package com.sige.gui;

import java.util.Date;

import com.sige.entidad.DocumentoInternoDestino;
import com.sige.entidad.ExpedienteMovimiento;
import com.sige.servicio.DiaNoHabilServicio;
import com.sige.servicio.DocumentoInternoDestinoService;
import com.sige.servicio.DocumentoInternoMapeoServicio;
import com.sige.util.Injector;
import com.sige.util.SigeUtil;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;

public class PanelDetalleMovimientoExpediente extends CustomComponent implements
		ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnSalir;
	@AutoGenerated
	private Label lblEnviadoPorValue;
	@AutoGenerated
	private Label lblEnvioPor;
	@AutoGenerated
	private Label lblRecepcionadoPorValue;
	@AutoGenerated
	private Label lblRecepcionadoPor;
	@AutoGenerated
	private Label lblNumeroFoliosValue;
	@AutoGenerated
	private Label lblNumeroFolios;
	@AutoGenerated
	private Label lblDiasTranscurridosValue;
	@AutoGenerated
	private Label lblDiasTranscurridos;
	@AutoGenerated
	private Label lblFechaEnvioValue;
	@AutoGenerated
	private Label lblFechaEnvio;
	@AutoGenerated
	private Label lblFechaRecepcionValue;
	@AutoGenerated
	private Label lblFechaRecepcion;
	@AutoGenerated
	private Label lblAsuntoValue;
	@AutoGenerated
	private Label lblAsunto;
	@AutoGenerated
	private Label lblDependenciaDestinoValue;
	@AutoGenerated
	private Label lblDependenciaDestino;
	@AutoGenerated
	private Label lblDependenciaOrigenValue;
	@AutoGenerated
	private Label lblDependenciaOrigen;
	@AutoGenerated
	private Label lblDependenciasRuta;
	@AutoGenerated
	private Button btnRuta;
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	private DocumentoInternoDestinoService documentoInternoDestinoService;
	private Window windowContenido;
	private ExpedienteMovimiento expedienteMovimiento;
	private DiaNoHabilServicio diaNoHabilServicio;
	
	private DocumentoInternoMapeoServicio documentoInternoMapeoServicio;

	public PanelDetalleMovimientoExpediente(Window windowContenido,ExpedienteMovimiento expedienteMovimiento) {

		this.documentoInternoDestinoService = Injector.obtenerServicio(DocumentoInternoDestinoService.class);
		this.diaNoHabilServicio = Injector.obtenerServicio(DiaNoHabilServicio.class);
		this.documentoInternoMapeoServicio = Injector.obtenerServicio(DocumentoInternoMapeoServicio.class);
		buildMainLayout();
		setCompositionRoot(mainLayout);
		this.windowContenido = windowContenido;
		this.expedienteMovimiento = expedienteMovimiento;
		postBuild();
		// TODO add user code here
	}

	private void postBuild() {

		btnSalir.addClickListener((ClickListener) this);
		btnRuta.addClickListener((ClickListener) this);

		DocumentoInternoDestino docDestino = documentoInternoDestinoService.obtenerDocInternoDestinoPorDocInterno(expedienteMovimiento.getDocumentoInterno().getCodigodocumento());

		lblDependenciaDestinoValue.setValue(docDestino.getDependencia().getNombre());
		lblFechaEnvioValue.setValue(SigeUtil.obtenerFormatoFecha(expedienteMovimiento.getDocumentoInterno().getFechadocumento()));

		lblFechaEnvioValue.setValue(SigeUtil.obtenerFormatoFecha(expedienteMovimiento.getDocumentoInterno().getFechadocumento()));
		if (docDestino.getFechaRecepcion() != null) {
			lblFechaRecepcionValue.setValue(SigeUtil.obtenerFormatoFecha(docDestino.getFechaRecepcion()));
			Date fechaFin = new Date(expedienteMovimiento.getDocumentoInterno().getFechadocumento().getTime());

			Date fechaRecepcion = new Date(docDestino.getFechaRecepcion()
					.getTime());

			lblDiasTranscurridosValue.setValue((SigeUtil.getDiasTranscurridos(
					fechaFin, fechaRecepcion) - diaNoHabilServicio
					.getCantidadDiasNoHabiles(fechaRecepcion, fechaFin))
					+ "");

		} else {
			lblFechaRecepcionValue.setValue("");
			lblDiasTranscurridosValue.setValue("");
		}

		lblDependenciaOrigenValue.setValue(expedienteMovimiento
				.getDocumentoInterno().getDependencia().getNombre());
		lblAsuntoValue.setValue(expedienteMovimiento.getDocumentoInterno()
				.getAsunto());
		lblNumeroFoliosValue.setValue(expedienteMovimiento.getExpediente()
				.getNumeroFolios() + "");
		lblEnviadoPorValue.setValue(expedienteMovimiento.getCreadoPor());
		lblRecepcionadoPorValue.setValue(docDestino.getRecepcionadoPor());

		
		//SETEO DE DATOS DE RECORRIDO
		//lblDependenciasRutaValue.setValue("Recorrido del Documento");
	}

	@Override
	public void buttonClick(ClickEvent event) {
		if (event.getSource() == this.btnSalir) {
			UI.getCurrent().removeWindow(windowContenido);
		}
		if (event.getSource() == this.btnRuta) {
			Window ventana = SigeUtil.generarBuscador(new Window(),"RECORRIDO DEL DOCUMENTO", "774px", "550px");
			System.out.println(""+expedienteMovimiento.getExpediente().getCodigo());
			ventana.setContent(new PanelMovimientoExpedienteGrafico(this,documentoInternoMapeoServicio.obtenerUltimoMovimiento(expedienteMovimiento.getDocumentoInterno().getCodigodocumento())));
			UI.getCurrent().addWindow(ventana);
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// lblAsunto
				lblAsunto = new Label();
				lblAsunto.setImmediate(false);
				lblAsunto.setWidth("-1px");
				lblAsunto.setHeight("-1px");
				lblAsunto.setValue("Asunto :");
				mainLayout.addComponent(lblAsunto, "top:20.0px;left:20.0px;");

				// lblAsuntoValue
				lblAsuntoValue = new Label();
				lblAsuntoValue.setImmediate(false);
				lblAsuntoValue.setWidth("633px");
				lblAsuntoValue.setHeight("66px");
				lblAsuntoValue.setValue("Label");
				mainLayout.addComponent(lblAsuntoValue, "top:20.0px;left:67.0px;");
		
		// lblDependenciaOrigen
		lblDependenciaOrigen = new Label();
		lblDependenciaOrigen.setImmediate(false);
		lblDependenciaOrigen.setWidth("-1px");
		lblDependenciaOrigen.setHeight("-1px");
		lblDependenciaOrigen.setValue("Dependencia de Origen :");
		mainLayout.addComponent(lblDependenciaOrigen, "top:48.0px;left:20.0px;");

		// lblDependenciaOrigenValue
		lblDependenciaOrigenValue = new Label();
		lblDependenciaOrigenValue.setImmediate(false);
		lblDependenciaOrigenValue.setWidth("537px");
		lblDependenciaOrigenValue.setHeight("-1px");
		lblDependenciaOrigenValue.setValue("Label");
		mainLayout.addComponent(lblDependenciaOrigenValue,"top:48.0px;left:170.0px;");

		// lblDependenciaDestino
		lblDependenciaDestino = new Label();
		lblDependenciaDestino.setImmediate(false);
		lblDependenciaDestino.setWidth("-1px");
		lblDependenciaDestino.setHeight("-1px");
		lblDependenciaDestino.setValue("Dependencia de Destino :");
		mainLayout.addComponent(lblDependenciaDestino,"top:74.0px;left:20.0px;");

		// lblDependenciaDestinoValue
		lblDependenciaDestinoValue = new Label();
		lblDependenciaDestinoValue.setImmediate(false);
		lblDependenciaDestinoValue.setWidth("530px");
		lblDependenciaDestinoValue.setHeight("-1px");
		lblDependenciaDestinoValue.setValue("Label");
		mainLayout.addComponent(lblDependenciaDestinoValue,"top:74.0px;left:163.0px;");

		
		lblDependenciasRuta = new Label();
		lblDependenciasRuta.setImmediate(false);
		lblDependenciasRuta.setWidth("-1px");
		lblDependenciasRuta.setHeight("-1px");
		lblDependenciasRuta.setValue("Recorrido del Expediente :");
		mainLayout.addComponent(lblDependenciasRuta, "top:104.0px;left:20.0px;");
		
		// lblDependenciaDestinoValue
		btnRuta = new Button();
		btnRuta.setCaption("Ver recorrido");
		btnRuta.setImmediate(true);
		btnRuta.setWidth("110px");
		btnRuta.setHeight("-1px");
		mainLayout.addComponent(btnRuta, "top:104.0px;left:170.0px;");
		

		// lblFechaRecepcion
		lblFechaRecepcion = new Label();
		lblFechaRecepcion.setImmediate(false);
		lblFechaRecepcion.setWidth("-1px");
		lblFechaRecepcion.setHeight("-1px");
		lblFechaRecepcion.setValue("Fecha Recepción :");
		mainLayout.addComponent(lblFechaRecepcion, "top:182.0px;left:20.0px;");

		// lblFechaRecepcionValue
		lblFechaRecepcionValue = new Label();
		lblFechaRecepcionValue.setImmediate(false);
		lblFechaRecepcionValue.setWidth("232px");
		lblFechaRecepcionValue.setHeight("-1px");
		lblFechaRecepcionValue.setValue("Label");
		mainLayout.addComponent(lblFechaRecepcionValue,"top:182.0px;left:128.0px;");

		// lblFechaEnvio
		lblFechaEnvio = new Label();
		lblFechaEnvio.setImmediate(false);
		lblFechaEnvio.setWidth("-1px");
		lblFechaEnvio.setHeight("-1px");
		lblFechaEnvio.setValue("Fecha de envío :");
		mainLayout.addComponent(lblFechaEnvio, "top:182.0px;left:376.0px;");

		// lblFechaEnvioValue
		lblFechaEnvioValue = new Label();
		lblFechaEnvioValue.setImmediate(false);
		lblFechaEnvioValue.setWidth("231px");
		lblFechaEnvioValue.setHeight("-1px");
		lblFechaEnvioValue.setValue("Label");
		mainLayout
				.addComponent(lblFechaEnvioValue, "top:182.0px;left:469.0px;");

		// lblDiasTranscurridos
		lblDiasTranscurridos = new Label();
		lblDiasTranscurridos.setImmediate(false);
		lblDiasTranscurridos.setWidth("-1px");
		lblDiasTranscurridos.setHeight("-1px");
		lblDiasTranscurridos.setValue("Días Transcurridos :");
		mainLayout.addComponent(lblDiasTranscurridos,"top:210.0px;left:20.0px;");

		// lblDiasTranscurridosValue
		lblDiasTranscurridosValue = new Label();
		lblDiasTranscurridosValue.setImmediate(false);
		lblDiasTranscurridosValue.setWidth("100px");
		lblDiasTranscurridosValue.setHeight("-1px");
		lblDiasTranscurridosValue.setValue("Label");
		mainLayout.addComponent(lblDiasTranscurridosValue,"top:210.0px;left:140.0px;");

		// lblNumeroFolios
		lblNumeroFolios = new Label();
		lblNumeroFolios.setImmediate(false);
		lblNumeroFolios.setWidth("-1px");
		lblNumeroFolios.setHeight("-1px");
		lblNumeroFolios.setValue("Número de Folios :");
		mainLayout.addComponent(lblNumeroFolios, "top:210.0px;left:376.0px;");

		// lblNumeroFoliosValue
		lblNumeroFoliosValue = new Label();
		lblNumeroFoliosValue.setImmediate(false);
		lblNumeroFoliosValue.setWidth("100px");
		lblNumeroFoliosValue.setHeight("-1px");
		lblNumeroFoliosValue.setValue("Label");
		mainLayout.addComponent(lblNumeroFoliosValue,"top:210.0px;left:486.0px;");

		// lblRecepcionadoPor
		lblRecepcionadoPor = new Label();
		lblRecepcionadoPor.setImmediate(false);
		lblRecepcionadoPor.setWidth("-1px");
		lblRecepcionadoPor.setHeight("-1px");
		lblRecepcionadoPor.setValue("Recepcionado Por:");
		mainLayout.addComponent(lblRecepcionadoPor, "top:238.0px;left:20.0px;");

		// lblRecepcionadoPorValue
		lblRecepcionadoPorValue = new Label();
		lblRecepcionadoPorValue.setImmediate(false);
		lblRecepcionadoPorValue.setWidth("228px");
		lblRecepcionadoPorValue.setHeight("-1px");
		lblRecepcionadoPorValue.setValue("Label");
		mainLayout.addComponent(lblRecepcionadoPorValue,"top:238.0px;left:132.0px;");

		// lblEnvioPor
		lblEnvioPor = new Label();
		lblEnvioPor.setImmediate(false);
		lblEnvioPor.setWidth("-1px");
		lblEnvioPor.setHeight("-1px");
		lblEnvioPor.setValue("Enviado Por :");
		mainLayout.addComponent(lblEnvioPor, "top:238.0px;left:376.0px;");

		// lblEnviadoPorValue
		lblEnviadoPorValue = new Label();
		lblEnviadoPorValue.setImmediate(false);
		lblEnviadoPorValue.setWidth("257px");
		lblEnviadoPorValue.setHeight("-1px");
		lblEnviadoPorValue.setValue("Label");
		mainLayout.addComponent(lblEnviadoPorValue, "top:238.0px;left:452.0px;");

		// btnSalir
		btnSalir = new Button();
		btnSalir.setCaption("Salir");
		btnSalir.setImmediate(true);
		btnSalir.setWidth("110px");
		btnSalir.setHeight("-1px");
		mainLayout.addComponent(btnSalir, "top:266.0px;left:295.0px;");

		return mainLayout;
	}

}
