package com.sige.gui;

import java.util.List;

import org.vaadin.risto.formsender.FormSenderBuilder;
import org.vaadin.risto.formsender.widgetset.client.shared.Method;

import com.sige.entidad.Expediente;
import com.sige.entidad.ExpedienteDocumento;
import com.sige.servicio.ExpedienteDocumentoService;
import com.sige.util.Constantes;
import com.sige.util.Injector;
import com.sige.util.Notificacion;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;

public class PanelExpedienteDocumento extends CustomComponent implements
		ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnDescargar;
	@AutoGenerated
	private Table tblExpedienteDocumento;
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	private ExpedienteDocumento expedienteDocumentoSeleccionado;
	private ExpedienteDocumentoService expedienteDocumentoService;

	private Expediente expediente;

	public PanelExpedienteDocumento(Expediente expediente) {
		this.expedienteDocumentoService = Injector
				.obtenerServicio(ExpedienteDocumentoService.class);
		this.expediente = expediente;

		buildMainLayout();
		setCompositionRoot(mainLayout);
		postBuild();
		getAllDocumentosCargados();
	}

	private void postBuild() {

		this.btnDescargar.addClickListener((ClickListener) this);

		IndexedContainer container = new IndexedContainer();
		container.addContainerProperty("id", Long.class, null);
		container.addContainerProperty("item", Long.class, null);
		container.addContainerProperty("dependencia", String.class, null);
		container.addContainerProperty("expediente", String.class, null);

		container.addContainerProperty("documento", String.class, null);

		tblExpedienteDocumento.setContainerDataSource(container);
		tblExpedienteDocumento.setVisibleColumns(new Object[] { "item",
				"dependencia", "expediente", "documento" });

		tblExpedienteDocumento.setColumnWidth("item", 25);
		tblExpedienteDocumento.setColumnWidth("documento", 200);
		tblExpedienteDocumento.setColumnWidth("dependencia", 200);
		tblExpedienteDocumento.setColumnWidth("expediente", 150);

		tblExpedienteDocumento.setColumnHeader("item", "Item");
		tblExpedienteDocumento.setColumnHeader("documento", "Documento");
		tblExpedienteDocumento.setColumnHeader("dependencia", "Dependencia");
		tblExpedienteDocumento.setColumnHeader("expediente", "Expediente");

		tblExpedienteDocumento.setColumnAlignment("item", Table.Align.CENTER);
		tblExpedienteDocumento.setColumnAlignment("documento",
				Table.Align.CENTER);
		tblExpedienteDocumento.setColumnAlignment("dependencia",
				Table.Align.CENTER);
		tblExpedienteDocumento.setColumnAlignment("expediente",
				Table.Align.CENTER);
		tblExpedienteDocumento.setSelectable(true);
		tblExpedienteDocumento.setImmediate(true);
		tblExpedienteDocumento
				.addValueChangeListener(new Property.ValueChangeListener() {

					@Override
					public void valueChange(ValueChangeEvent event) {
						// TODO Auto-generated method stub
						Item item = tblExpedienteDocumento
								.getItem(tblExpedienteDocumento.getValue());
						if (item != null) {
							obtenerExpedienteDocumento((Long) item
									.getItemProperty("id").getValue());
						}

					}

				});

	}

	private void getAllDocumentosCargados() {
		List<ExpedienteDocumento> expedienteDocumentos = expedienteDocumentoService
				.obtenerTodos(null, expediente);
		for (ExpedienteDocumento expDoc : expedienteDocumentos) {
			IndexedContainer container = (IndexedContainer) tblExpedienteDocumento
					.getContainerDataSource();
			Item item = container.addItem(expDoc.getId());
			if (item != null) {

				item.getItemProperty("id").setValue(expDoc.getId());
				item.getItemProperty("item").setValue(
						new Long(container.size()));
				item.getItemProperty("documento").setValue(
						expDoc.getDependenciaTipoTramitePlantilla()
								.getNombrePlantilla());
				item.getItemProperty("dependencia").setValue(
						expDoc.getDependencia().getNombre());
				item.getItemProperty("expediente").setValue(
						expediente.getAnio() + "-" + expediente.getNumero());
			}

		}
	}

	private void obtenerExpedienteDocumento(Long idExpedienteDocumento) {
		expedienteDocumentoSeleccionado = expedienteDocumentoService
				.obtener(idExpedienteDocumento);
	}

	@Override
	public void buttonClick(ClickEvent event) {
		if (event.getSource() == this.btnDescargar) {
			if (expedienteDocumentoSeleccionado != null) {
				FormSenderBuilder
						.create()
						.withUI(getUI())
						.withAction("./DescargarArchivo")
						.withMethod(Method.POST)
						.withValue(
								"fileLocation",
								Constantes.FILE_LOCATION.FILE_LOCATION_DOCUMENTOS)
						.withValue(
								"fileName",
								expedienteDocumentoSeleccionado
										.getNombreArchivo()).submit();

			} else {
				Notificacion.show(new Notificacion(
						"Debe seleccionar un documento",
						Constantes.MENSAJE.TYPE_ERROR));
			}
		}

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// tblExpedienteDocumento
		tblExpedienteDocumento = new Table();
		tblExpedienteDocumento.setImmediate(false);
		tblExpedienteDocumento.setWidth("600px");
		tblExpedienteDocumento.setHeight("240px");
		mainLayout.addComponent(tblExpedienteDocumento,
				"top:20.0px;left:20.0px;");

		// btnDescargar
		btnDescargar = new Button();
		btnDescargar.setCaption("Descargar");
		btnDescargar.setIcon(new ThemeResource("images/botones/down.png"));
		btnDescargar.setImmediate(true);
		btnDescargar.setWidth("110px");
		btnDescargar.setHeight("-1px");
		mainLayout.addComponent(btnDescargar, "top:264.0px;left:510.0px;");

		return mainLayout;
	}

}
