package com.sige.gui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.vaadin.dialogs.ConfirmDialog;

import com.sige.entidad.Dependencia;
import com.sige.entidad.DependenciaTipoTramite;
import com.sige.entidad.DependenciaTipoTramitePlantilla;
import com.sige.entidad.TipoTramite;
import com.sige.servicio.DependenciaServicio;
import com.sige.servicio.DependenciaTipoTramitePlantillaService;
import com.sige.servicio.DependenciaTipoTramiteService;
import com.sige.servicio.TipoTramiteService;
import com.sige.servicio.UtilService;
import com.sige.util.Boton;
import com.sige.util.Constantes;
import com.sige.util.Injector;
import com.sige.util.Notificacion;
import com.sige.util.Permiso;
import com.sige.util.ReceiverCustom;
import com.sige.util.SigeUtil;
import com.sige.util.TextField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.ProgressIndicator;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.Upload;
import com.vaadin.ui.Upload.FailedEvent;
import com.vaadin.ui.Upload.FinishedEvent;
import com.vaadin.ui.Upload.StartedEvent;
import com.vaadin.ui.Upload.SucceededEvent;
import com.vaadin.ui.Window;

public class PlantillaMantenimiento extends CustomComponent implements
		ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnCancelar;
	@AutoGenerated
	private Button btnEliminar;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private Button btnNuevo;
	@AutoGenerated
	private Panel pnlPlanilla;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private Button cancelProcessing;
	@AutoGenerated
	private HorizontalLayout progressLayout;
	@AutoGenerated
	private Upload upload;
	@AutoGenerated
	private Label lblArchivo;
	@AutoGenerated
	private TextField txtNombrePlanilla;
	@AutoGenerated
	private Label lblNombrePlanilla;
	@AutoGenerated
	private Table tblPlantillas;
	@AutoGenerated
	private Boton btnBuscar;
	@AutoGenerated
	private ComboBox cbxDependencia;
	@AutoGenerated
	private TextField txtTipoTramite;
	@AutoGenerated
	private Label lblTipoTramite;
	@AutoGenerated
	private Label lblDependencia;
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	private DependenciaServicio dependenciaServicio;
	private ReceiverCustom receiver;
	private TipoTramiteService tipoTramiteService;
	private TipoTramite tipoTramiteObtenido;
	private DependenciaTipoTramiteService dependenciaTipoTramiteService;
	@SuppressWarnings("deprecation")
	private ProgressIndicator pi;
	private DependenciaTipoTramite dependenciaTipoTramiteObtenido;
	private DependenciaTipoTramitePlantillaService dependenciaTipoTramitePlantillaService;
	private DependenciaTipoTramitePlantilla dependenciaTipoTramitePlantilla;
	private SimpleDateFormat formato;
	private Map<Long, DependenciaTipoTramitePlantilla> dttpMap;
	private boolean flagEsNuevo = false;
	private Long itemSelec;
	private Permiso permiso;
	private Map<String, Integer> columnLenghts;
	private UtilService utilService;
	private boolean confirmacion = false;

	public PlantillaMantenimiento(Window windowContiene,
			CustomComponent quienLlama, Permiso permiso) {
		this.dependenciaServicio = Injector
				.obtenerServicio(DependenciaServicio.class);
		this.tipoTramiteService = Injector
				.obtenerServicio(TipoTramiteService.class);
		this.dependenciaTipoTramiteService = Injector
				.obtenerServicio(DependenciaTipoTramiteService.class);
		this.dependenciaTipoTramitePlantillaService = Injector
				.obtenerServicio(DependenciaTipoTramitePlantillaService.class);
		receiver = new ReceiverCustom();
		utilService = Injector.obtenerServicio(UtilService.class);
		receiver.setFileLocation(System.getProperty("java.io.tmpdir"));
		buildMainLayout();
		setCompositionRoot(mainLayout);
		formato = new SimpleDateFormat("ddMyyyyhhmmss");
		this.permiso = permiso;
		dttpMap = new HashMap<Long, DependenciaTipoTramitePlantilla>();
		postBuild();
		resetearFormulario();
	}

	public void obtenerMotivo(String motivo, Boolean confirmacion,
			Integer tipoOperacion) {
		if (confirmacion) {
			dependenciaTipoTramitePlantilla.setMotivoModificacion(motivo);
			this.confirmacion = true;
			if (tipoOperacion.equals(Constantes.TIPO_OPERACION.MODIFICACION)) {
				btnGuardar.click();
			} else {
				btnEliminar.click();
			}
			this.confirmacion = false;
		}
	}

	private void postBuild() {
		columnLenghts = utilService
				.getLengthColumns("dependenciatipotramiteplantilla");
		cbxDependencia.setImmediate(true);
		this.btnCancelar.setId("cancelar");
		this.btnEliminar.setId("eliminar");
		this.btnGuardar.setId("guardar");
		this.btnNuevo.setId("nuevo");
		this.btnBuscar.setStyleName("buscar");
		SigeUtil.validarBotones(permiso, btnNuevo, btnEliminar, btnCancelar,
				btnGuardar);
		pi = new ProgressIndicator();
		txtNombrePlanilla.setMaxLength(columnLenghts.get("nombreplantilla"));
		List<Dependencia> dependencias = dependenciaServicio.obtenerTodos();
		for (Dependencia dp : dependencias) {
			cbxDependencia.addItem(dp.getId());
			cbxDependencia.setItemCaption(dp.getId(), dp.getNombre().trim());
		}
		if (dependencias.size() > 0) {
			cbxDependencia.setValue(dependencias.get(0).getId());
		}
		cbxDependencia.addValueChangeListener(new ValueChangeListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				if (event.getProperty().getValue() != null) {
					if (tipoTramiteObtenido != null
							&& cbxDependencia.getValue() != null) {
						dependenciaTipoTramiteObtenido = dependenciaTipoTramiteService
								.getDependenciaTipoTramite(dependenciaServicio
										.obtener((Long) cbxDependencia
												.getValue()),
										tipoTramiteObtenido);
						if (!flagEsNuevo) {
							getAllPlantillas();
						} else {
							clearTable();
						}
					}
				}
			}
		});

		upload.setImmediate(true);
		upload.setButtonCaption("Cargar Archivo");

		progressLayout.setSpacing(true);
		progressLayout.setVisible(false);
		cancelProcessing.setVisible(false);
		progressLayout.addComponent(pi);
		progressLayout.setComponentAlignment(pi, Alignment.MIDDLE_LEFT);

		cancelProcessing.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				upload.interruptUpload();
			}
		});
		cancelProcessing.setStyleName("small");

		upload.addStartedListener(new Upload.StartedListener() {

			@Override
			public void uploadStarted(StartedEvent event) {
				if (dependenciaTipoTramiteObtenido == null) {
					Notificacion.show(new Notificacion(
							"Debe elegir la dependencia y el tipo de tramite",
							Constantes.MENSAJE.TYPE_ERROR));
					upload.interruptUpload();
					return;
				}

				if (txtNombrePlanilla.isEmpty()) {
					Notificacion.show(new Notificacion(
							"Debe introducir el nombre de la plantilla",
							Constantes.MENSAJE.TYPE_ERROR));
					upload.interruptUpload();
					return;
				}

				if (event
						.getFilename()
						.substring(event.getFilename().length() - 3,
								event.getFilename().length())
						.equalsIgnoreCase("doc")) {
					receiver.setFileName(formato.format(new Date()) + ".doc");
					upload.setVisible(false);
					progressLayout.setVisible(true);
					cancelProcessing.setVisible(true);
					pi.setValue(0f);
					pi.setPollingInterval(500);
				} else {
					upload.interruptUpload();
					Notificacion.show(new Notificacion(
							"El sistema solo acepta archivos .doc",
							Constantes.MENSAJE.TYPE_ERROR));
				}
			}

		});

		upload.addProgressListener(new Upload.ProgressListener() {
			public void updateProgress(long readBytes, long contentLength) {
				pi.setValue(new Float(readBytes / (float) contentLength));
			}

		});

		upload.addSucceededListener(new Upload.SucceededListener() {
			public void uploadSucceeded(SucceededEvent event) {

				if (dependenciaTipoTramitePlantilla != null) {
					if (!txtNombrePlanilla
							.getValue()
							.trim()
							.equalsIgnoreCase(
									dependenciaTipoTramitePlantilla
											.getNombrePlantilla().trim())
							&& dependenciaTipoTramitePlantillaService
									.validarDuplicado(
											dependenciaTipoTramiteObtenido,
											txtNombrePlanilla.getValue())) {
						Notificacion.show(new Notificacion(
								"Ya existe una plantilla con este nombre ",
								Constantes.MENSAJE.TYPE_ERROR));
						upload.interruptUpload();
						return;

					}
				} else {
					if (dependenciaTipoTramitePlantillaService
							.validarDuplicado(dependenciaTipoTramiteObtenido,
									txtNombrePlanilla.getValue())) {
						Notificacion.show(new Notificacion(
								"Ya existe una plantilla con este nombre ",
								Constantes.MENSAJE.TYPE_ERROR));
						upload.interruptUpload();
						return;

					}
				}
				if (flagEsNuevo && dependenciaTipoTramitePlantilla == null) {

					IndexedContainer container = (IndexedContainer) tblPlantillas
							.getContainerDataSource();
					Item item = container.addItem(txtNombrePlanilla.getValue());
					if (item != null) {
						item.getItemProperty("item").setValue(
								new Long(container.size()));
						item.getItemProperty("documento").setValue(
								txtNombrePlanilla.getValue());
						item.getItemProperty("archivo").setValue(
								event.getFilename());
						item.getItemProperty("rutaTemp").setValue(
								receiver.getFileLocation()
										+ receiver.getFileName());
						txtNombrePlanilla.setValue("");

					} else {
						Notificacion.show(new Notificacion(
								"Ya se agrego una plantilla con este nombre: "
										+ txtNombrePlanilla.getValue(),
								Constantes.MENSAJE.TYPE_ERROR));
						upload.interruptUpload();
					}
				} else {
					dependenciaTipoTramitePlantilla.setRutaTemp(receiver
							.getFileLocation() + receiver.getFileName());
					dependenciaTipoTramitePlantilla.setNombreArchivo(event
							.getFilename());
				}

			}
		});

		upload.addFailedListener(new Upload.FailedListener() {

			@Override
			public void uploadFailed(FailedEvent event) {

			}
		});

		upload.addFinishedListener(new Upload.FinishedListener() {

			@Override
			public void uploadFinished(FinishedEvent event) {
				progressLayout.setVisible(false);
				cancelProcessing.setVisible(false);
				upload.setVisible(true);
			}
		});

		this.btnBuscar.addClickListener((ClickListener) this);
		this.btnCancelar.addClickListener((ClickListener) this);
		this.btnEliminar.addClickListener((ClickListener) this);
		this.btnGuardar.addClickListener((ClickListener) this);
		this.btnNuevo.addClickListener((ClickListener) this);

		this.txtTipoTramite.setEnabled(false);

		IndexedContainer container = new IndexedContainer();
		container.addContainerProperty("id", Long.class, null);
		container.addContainerProperty("item", Long.class, null);
		container.addContainerProperty("documento", String.class, null);
		container.addContainerProperty("archivo", String.class, null);
		container.addContainerProperty("rutaTemp", String.class, null);

		tblPlantillas.setContainerDataSource(container);
		tblPlantillas
				.setVisibleColumns(new Object[] { "documento", "archivo" });

		tblPlantillas.setColumnWidth("documento", 205);
		tblPlantillas.setColumnWidth("archivo", 185);

		tblPlantillas.setColumnHeader("documento", "Nombre Plantilla");
		tblPlantillas.setColumnHeader("archivo", "Nombre Archivo");

		tblPlantillas.setColumnAlignment("documento", Table.Align.CENTER);
		tblPlantillas.setColumnAlignment("archivo", Table.Align.CENTER);
		tblPlantillas.setSelectable(true);
		tblPlantillas.setImmediate(true);
		tblPlantillas
				.addValueChangeListener(new Property.ValueChangeListener() {

					@Override
					public void valueChange(ValueChangeEvent event) {
						// TODO Auto-generated method stub
						btnGuardar.setCaption("Actualizar");
						btnEliminar.setEnabled(true);
						btnNuevo.setEnabled(true);
						btnGuardar.setVisible(permiso.getModificar());
						btnGuardar.setEnabled(true);
						btnCancelar.setVisible(permiso.getModificar());
						btnCancelar.setEnabled(true);
						upload.setEnabled(true);
						txtNombrePlanilla.setEnabled(true);
						Item item = tblPlantillas.getItem(tblPlantillas
								.getValue());
						if (item != null) {
							desactivarSelectores(false);
							txtNombrePlanilla.setValue(item
									.getItemProperty("documento").getValue()
									.toString());
							if (flagEsNuevo) {
								itemSelec = (Long) item.getItemProperty("item")
										.getValue();
								dependenciaTipoTramitePlantilla = new DependenciaTipoTramitePlantilla();
								dependenciaTipoTramitePlantilla
										.setNombreArchivo(item
												.getItemProperty("archivo")
												.getValue().toString());
								dependenciaTipoTramitePlantilla
										.setRutaTemp(item
												.getItemProperty("rutaTemp")
												.getValue().toString());
							} else {
								getDependenciaTipoTramitePlantilla(new Long(
										item.getItemProperty("id").getValue()
												.toString()));
							}
							tblPlantillas.unselect(tblPlantillas.getValue());
						}
					}
				});
	}

	private void desactivarSelectores(boolean estado) {
		btnBuscar.setEnabled(estado);
		cbxDependencia.setEnabled(estado);
	}

	private void desactivarCampos(boolean estado) {
		txtNombrePlanilla.setEnabled(estado);
		upload.setEnabled(estado);
	}

	private void resetearFormulario() {
		this.flagEsNuevo = false;
		this.btnNuevo.setEnabled(true);
		this.btnCancelar.setEnabled(false);
		this.btnGuardar.setEnabled(false);
		this.btnEliminar.setEnabled(false);
		dependenciaTipoTramitePlantilla = null;
		desactivarCampos(false);
		this.txtNombrePlanilla.setValue("");
	}

	private void NuevoRegistro() {
		this.flagEsNuevo = true;
		dependenciaTipoTramitePlantilla = null;
		this.btnCancelar.setVisible(permiso.getNuevo());
		this.btnCancelar.setEnabled(true);
		this.btnGuardar.setCaption("Guardar");
		this.btnGuardar.setVisible(permiso.getNuevo());
		this.btnGuardar.setEnabled(true);
		this.btnEliminar.setEnabled(false);

		this.btnNuevo.setEnabled(false);
		desactivarCampos(permiso.getNuevo());

	}

	private void clearTable() {
		tblPlantillas.getContainerDataSource().removeAllItems();
	}

	private void getAllPlantillas() {
		IndexedContainer container = (IndexedContainer) tblPlantillas
				.getContainerDataSource();
		container.removeAllItems();

		List<DependenciaTipoTramitePlantilla> dependenciaTipoTramitePlantillasListado = null;

		dependenciaTipoTramitePlantillasListado = dependenciaTipoTramitePlantillaService
				.obtenerTodos(dependenciaTipoTramiteObtenido);
		Long itemN = 1L;
		for (int i = 0; i < dependenciaTipoTramitePlantillasListado.size(); i++) {
			Item item = container.addItem(i);
			item.getItemProperty("id").setValue(
					dependenciaTipoTramitePlantillasListado.get(i).getId());
			item.getItemProperty("item").setValue(itemN);
			item.getItemProperty("documento").setValue(
					dependenciaTipoTramitePlantillasListado.get(i)
							.getNombrePlantilla());
			item.getItemProperty("archivo").setValue(
					dependenciaTipoTramitePlantillasListado.get(i)
							.getNombreArchivo());
			item.getItemProperty("rutaTemp").setValue("");
			itemN++;
		}
	}

	private void getDependenciaTipoTramitePlantilla(Long id) {
		dependenciaTipoTramitePlantilla = dependenciaTipoTramitePlantillaService
				.obtener(id);
	}

	public void obtenerTipoTramite(String codTipoTramite) {
		tipoTramiteObtenido = tipoTramiteService
				.obtenerTipoTramitePorCod(codTipoTramite);
		txtTipoTramite.setValue(tipoTramiteObtenido.getNombre());
		if (cbxDependencia.getValue() != null && tipoTramiteObtenido != null) {
			dependenciaTipoTramiteObtenido = dependenciaTipoTramiteService
					.getDependenciaTipoTramite(dependenciaServicio
							.obtener((Long) cbxDependencia.getValue()),
							tipoTramiteObtenido);
			if (!flagEsNuevo) {
				getAllPlantillas();
			} else {
				clearTable();
			}
		}
	}

	@SuppressWarnings("unchecked")
	@Override
	public void buttonClick(ClickEvent event) {
		if (event.getSource() == this.btnBuscar) {
			Window subWindow = SigeUtil.generarBuscador(new Window(),
					"BUSCAR TIPO TRAMITE", "775px", "430px");
			TipoTramiteBuscar componente = new TipoTramiteBuscar(subWindow,
					this, null);
			subWindow.setContent(componente);
			UI.getCurrent().addWindow(subWindow);
			componente.rellenarDatosTablaTipoTramite();
		} else if (event.getSource() == this.btnGuardar) {
			if (flagEsNuevo) {
				if (dependenciaTipoTramitePlantilla == null) {
					List<DependenciaTipoTramitePlantilla> dttpls = new ArrayList<DependenciaTipoTramitePlantilla>();
					for (Object o : tblPlantillas.getItemIds()) {
						dependenciaTipoTramitePlantilla = new DependenciaTipoTramitePlantilla();
						dependenciaTipoTramitePlantilla
								.setDependenciaTipoTramite(dependenciaTipoTramiteObtenido);
						dependenciaTipoTramitePlantilla
								.setNombrePlantilla(tblPlantillas.getItem(o)
										.getItemProperty("documento")
										.getValue().toString());
						dependenciaTipoTramitePlantilla
								.setRutaTemp(tblPlantillas.getItem(o)
										.getItemProperty("rutaTemp").getValue()
										.toString());
						dttpls.add(dependenciaTipoTramitePlantilla);
					}
					if (!dependenciaTipoTramitePlantillaService
							.crearTodos(dttpls)) {
						Notificacion
								.show(new Notificacion(
										"No se pudo guardar las plantillas, porfavor intente nuevamente",
										Constantes.MENSAJE.TYPE_ERROR));
						getAllPlantillas();
					}
					resetearFormulario();
					getAllPlantillas();
					Notificacion.show(new Notificacion(
							"Se Guardaron correctamente las plantillas",
							Constantes.MENSAJE.TYPE_SUCCES));
					getAllPlantillas();
				} else {
					Long item;
					for (Object o : tblPlantillas.getItemIds()) {
						item = (Long) tblPlantillas.getItem(o)
								.getItemProperty("item").getValue();
						if (itemSelec.equals(item)) {
							tblPlantillas.getItem(o)
									.getItemProperty("documento")
									.setValue(txtNombrePlanilla.getValue());
							tblPlantillas
									.getItem(o)
									.getItemProperty("archivo")
									.setValue(
											dependenciaTipoTramitePlantilla
													.getNombreArchivo());
							tblPlantillas
									.getItem(o)
									.getItemProperty("rutaTemp")
									.setValue(
											dependenciaTipoTramitePlantilla
													.getRutaTemp());
							break;
						}
					}
					NuevoRegistro();
					this.txtNombrePlanilla.setValue("");
				}
			} else {
				if (txtNombrePlanilla.isEmpty()) {
					Notificacion.show(new Notificacion(
							"Debe ingresar el nombre de la plantilla",
							Constantes.MENSAJE.TYPE_ERROR));
					return;
				}
				if (!txtNombrePlanilla
						.getValue()
						.trim()
						.equalsIgnoreCase(
								dependenciaTipoTramitePlantilla
										.getNombrePlantilla().trim())
						&& dependenciaTipoTramitePlantillaService
								.validarDuplicado(
										dependenciaTipoTramiteObtenido,
										txtNombrePlanilla.getValue())) {
					Notificacion.show(new Notificacion(
							"Ya existe una plantilla con este nombre",
							Constantes.MENSAJE.TYPE_ERROR));
					return;
				}
				if (!confirmacion) {
					Window ventana = SigeUtil.generarBuscador(new Window(),
							"INGRESAR MOTIVO", "360", "260");
					ventana.setContent(new PanelMotivoObservacion(ventana,
							this, Constantes.TIPO_OPERACION.MODIFICACION,
							(columnLenghts.get("motivomodifica"))));
					UI.getCurrent().addWindow(ventana);
					return;
				}
				dependenciaTipoTramitePlantilla
						.setNombrePlantilla(txtNombrePlanilla.getValue());
				if (!dependenciaTipoTramitePlantillaService
						.update(dependenciaTipoTramitePlantilla)) {
					Notificacion
							.show(new Notificacion(
									"No se pudo actualizar la plantilla , porfavor intente nuevamente",
									Constantes.MENSAJE.TYPE_ERROR));
					return;
				}
				getAllPlantillas();
				resetearFormulario();
				getAllPlantillas();
				Notificacion.show(new Notificacion(
						"Se Actualizo correctamente la plantilla",
						Constantes.MENSAJE.TYPE_SUCCES));
				getAllPlantillas();
			}
			desactivarSelectores(true);

		} else if (event.getSource() == this.btnNuevo) {
			NuevoRegistro();
			txtNombrePlanilla.setValue("");
			cbxDependencia.setEnabled(true);
			btnBuscar.setEnabled(true);
			clearTable();
		} else if (event.getSource() == this.btnEliminar) {
			if (!confirmacion) {
				Window ventana = SigeUtil.generarBuscador(new Window(),
						"INGRESAR MOTIVO", "360", "260");
				ventana.setContent(new PanelMotivoObservacion(ventana, this,
						Constantes.TIPO_OPERACION.ELIMINACION, (columnLenghts
								.get("motivomodifica"))));
				UI.getCurrent().addWindow(ventana);
				return;
			}
			ConfirmDialog.show(UI.getCurrent(), "Confirmación",
					"¿Desea elminar La plantilla?", "Aceptar", "Cancelar",
					new ConfirmDialog.Listener() {
						private static final long serialVersionUID = 1L;

						public void onClose(ConfirmDialog dialog) {
							if (dialog.isConfirmed()) {
								if (flagEsNuevo) {
									Long item;
									for (Object o : tblPlantillas.getItemIds()) {
										item = (Long) tblPlantillas.getItem(o)
												.getItemProperty("item")
												.getValue();
										if (itemSelec.equals(item)) {
											tblPlantillas.removeItem(o);
											break;
										}
									}
									NuevoRegistro();
								} else {
									dependenciaTipoTramitePlantillaService
											.eliminarDependenciaTipoTramitePlantilla(dependenciaTipoTramitePlantilla);
								}
								Notificacion
										.show(new Notificacion(
												"Se elimino correctamente la plantilla",
												Constantes.MENSAJE.TYPE_SUCCES));
								getAllPlantillas();
								txtNombrePlanilla.setValue("");
								if (!flagEsNuevo) {
									resetearFormulario();
								}
							}
						}
					});

		} else if (event.getSource() == this.btnCancelar) {
			if (flagEsNuevo && dependenciaTipoTramitePlantilla != null) {
				NuevoRegistro();
			} else {
				resetearFormulario();
				getAllPlantillas();
			}
			desactivarSelectores(true);
		}

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// lblDependencia
		lblDependencia = new Label();
		lblDependencia.setImmediate(false);
		lblDependencia.setWidth("-1px");
		lblDependencia.setHeight("-1px");
		lblDependencia.setValue("Dependencia :");
		mainLayout.addComponent(lblDependencia, "top:10.0px;left:20.0px;");

		// lblTipoTramite
		lblTipoTramite = new Label();
		lblTipoTramite.setImmediate(false);
		lblTipoTramite.setWidth("-1px");
		lblTipoTramite.setHeight("-1px");
		lblTipoTramite.setValue("Tipo Tramite :");
		mainLayout.addComponent(lblTipoTramite, "top:50.0px;left:20.0px;");

		// txtTipoTramite
		txtTipoTramite = new TextField();
		txtTipoTramite.setImmediate(false);
		txtTipoTramite.setWidth("320px");
		txtTipoTramite.setHeight("-1px");
		mainLayout.addComponent(txtTipoTramite, "top:49.0px;left:100.0px;");

		// cbxDependencia
		cbxDependencia = new ComboBox();
		cbxDependencia.setImmediate(false);
		cbxDependencia.setWidth("345px");
		cbxDependencia.setHeight("-1px");
		mainLayout.addComponent(cbxDependencia, "top:10.0px;left:103.0px;");

		// btnBuscar
		btnBuscar = new Boton();
		btnBuscar.setIcon(new ThemeResource("images/botones/find.png"));
		btnBuscar.setImmediate(false);
		btnBuscar.setWidth("28px");
		btnBuscar.setHeight("24px");
		mainLayout.addComponent(btnBuscar, "top:49.0px;left:420.0px;");

		// tblPlantillas
		tblPlantillas = new Table();
		tblPlantillas.setImmediate(false);
		tblPlantillas.setWidth("428px");
		tblPlantillas.setHeight("180px");
		mainLayout.addComponent(tblPlantillas, "top:213.0px;left:17.0px;");

		// pnlPlanilla
		pnlPlanilla = buildPnlPlanilla();
		mainLayout.addComponent(pnlPlanilla, "top:86.0px;left:20.0px;");

		// btnNuevo
		btnNuevo = new Button();
		btnNuevo.setCaption("Nuevo");
		btnNuevo.setIcon(new ThemeResource("images/botones/new.png"));
		btnNuevo.setImmediate(true);
		btnNuevo.setWidth("100px");
		btnNuevo.setHeight("-1px");
		mainLayout.addComponent(btnNuevo, "top:404.0px;left:19.0px;");

		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setIcon(new ThemeResource("images/botones/save.png"));
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("100px");
		btnGuardar.setHeight("-1px");
		mainLayout.addComponent(btnGuardar, "top:404.0px;left:126.0px;");

		// btnEliminar
		btnEliminar = new Button();
		btnEliminar.setCaption("Eliminar");
		btnEliminar.setIcon(new ThemeResource("images/botones/delete.png"));
		btnEliminar.setImmediate(true);
		btnEliminar.setWidth("100px");
		btnEliminar.setHeight("-1px");
		mainLayout.addComponent(btnEliminar, "top:404.0px;left:235.0px;");

		// btnCancelar
		btnCancelar = new Button();
		btnCancelar.setCaption("Cancelar");
		btnCancelar.setIcon(new ThemeResource("images/botones/undo.png"));
		btnCancelar.setImmediate(true);
		btnCancelar.setWidth("100px");
		btnCancelar.setHeight("-1px");
		mainLayout.addComponent(btnCancelar, "top:404.0px;left:345.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPnlPlanilla() {
		// common part: create layout
		pnlPlanilla = new Panel();
		pnlPlanilla.setCaption("Datos de Plantilla");
		pnlPlanilla.setImmediate(false);
		pnlPlanilla.setWidth("425px");
		pnlPlanilla.setHeight("114px");

		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		pnlPlanilla.setContent(absoluteLayout_2);

		return pnlPlanilla;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("100.0%");

		// lblNombrePlanilla
		lblNombrePlanilla = new Label();
		lblNombrePlanilla.setImmediate(false);
		lblNombrePlanilla.setWidth("-1px");
		lblNombrePlanilla.setHeight("-1px");
		lblNombrePlanilla.setValue("Nombre de Planilla :");
		absoluteLayout_2.addComponent(lblNombrePlanilla,
				"top:9.0px;left:3.0px;");

		// txtNombrePlanilla
		txtNombrePlanilla = new TextField();
		txtNombrePlanilla.setImmediate(false);
		txtNombrePlanilla.setWidth("304px");
		txtNombrePlanilla.setHeight("-1px");
		absoluteLayout_2.addComponent(txtNombrePlanilla,
				"top:6.0px;left:115.0px;");

		// lblArchivo
		lblArchivo = new Label();
		lblArchivo.setImmediate(false);
		lblArchivo.setWidth("-1px");
		lblArchivo.setHeight("-1px");
		lblArchivo.setValue("Archivo :");
		absoluteLayout_2.addComponent(lblArchivo, "top:48.0px;left:3.0px;");

		// upload
		upload = new Upload(null, receiver);
		upload.setImmediate(false);
		upload.setWidth("-1px");
		upload.setHeight("-1px");
		absoluteLayout_2.addComponent(upload, "top:46.0px;left:52.0px;");

		// progressLayout
		progressLayout = new HorizontalLayout();
		progressLayout.setImmediate(false);
		progressLayout.setWidth("148px");
		progressLayout.setHeight("28px");
		progressLayout.setMargin(false);
		absoluteLayout_2
				.addComponent(progressLayout, "top:46.0px;left:52.0px;");

		// cancelProcessing
		cancelProcessing = new Button();
		cancelProcessing.setCaption("Cancelar");
		cancelProcessing.setImmediate(true);
		cancelProcessing.setWidth("-1px");
		cancelProcessing.setHeight("-1px");
		absoluteLayout_2.addComponent(cancelProcessing,
				"top:47.0px;left:206.0px;");

		return absoluteLayout_2;
	}

}
