package com.sige.gui;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.codec.digest.DigestUtils;
import org.vaadin.dialogs.ConfirmDialog;

import com.sige.entidad.Dependencia;
import com.sige.entidad.Grupo;
import com.sige.entidad.Usuario;
import com.sige.entidad.UsuarioAcceso;
import com.sige.entidad.UsuarioDependencia;
import com.sige.gui.ui.NumberField;
import com.sige.servicio.DependenciaServicio;
import com.sige.servicio.GrupoServicio;
import com.sige.servicio.UsuarioAccesoServicio;
import com.sige.servicio.UsuarioDependenciaServicio;
import com.sige.servicio.UsuarioServicio;
import com.sige.servicio.UtilService;
import com.sige.util.Boton;
import com.sige.util.Busqueda;
import com.sige.util.Constantes;
import com.sige.util.Injector;
import com.sige.util.Notificacion;
import com.sige.util.Permiso;
import com.sige.util.SigeUtil;
import com.sige.util.TextField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.event.ShortcutListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TreeTable;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.vaadin.ui.themes.Reindeer;

public class UsuariosMantenimiento extends CustomComponent implements
		ClickListener {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private PasswordField txtConfirClave;

	@AutoGenerated
	private Label lblConfirmacion;

	@AutoGenerated
	private TabSheet tabGruposDependencias;

	@AutoGenerated
	private TreeTable treeDependencias;

	@AutoGenerated
	private TreeTable treeGrupos;

	@AutoGenerated
	private Button btnImprimir;

	@AutoGenerated
	private Label lblTotalPaginas;

	@AutoGenerated
	private Label lblSeparador;

	@AutoGenerated
	private NumberField txtPaginaActual;

	@AutoGenerated
	private Label lblPagina;

	@AutoGenerated
	private Boton btnFin;

	@AutoGenerated
	private Boton btnSiguiente;

	@AutoGenerated
	private Boton btnAtras;

	@AutoGenerated
	private Boton btnInicio;

	@AutoGenerated
	private Button btnCancelar;

	@AutoGenerated
	private Button btnEliminar;

	@AutoGenerated
	private Button btnGuardar;

	@AutoGenerated
	private Button btnNuevo;

	@AutoGenerated
	private PasswordField txtClave;

	@AutoGenerated
	private TextField txtNombres;

	@AutoGenerated
	private TextField txtUsuario;

	@AutoGenerated
	private Label lblClave;

	@AutoGenerated
	private Label lblNombres;

	@AutoGenerated
	private Label lblUsuario;

	@AutoGenerated
	private Label lblTitulo;

	@AutoGenerated
	private Boton btnBuscar;

	@AutoGenerated
	private TextField txtBuscarNombres;

	@AutoGenerated
	private TextField txtBuscarUsuario;

	@AutoGenerated
	private Table tblUsuarios;

	private static final long serialVersionUID = 1L;

	/*- VaadinEditorProperties={"grid":"RegularGrid,10","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private boolean flagEsNuevo = false;

	private UsuarioServicio usuarioServicio;

	private Usuario usuario;

	private GrupoServicio grupoServicio;

	private UsuarioAccesoServicio usuarioAccesoServicio;

	private UsuarioDependenciaServicio usuarioDependenciaServicio;

	private DependenciaServicio dependenciaServicio;

	private Map<Long, Grupo> grups;

	private Map<Long, Dependencia> dependencias;

	private Map<Long, UsuarioAcceso> usuarioAccesosMap;

	private String claveEncritada = "";

	private List<UsuarioAcceso> usuarioAccesos;
	private Window quienLlama;
	private Permiso permiso;
	private List<UsuarioDependencia> usuarioDependencias;
	private UtilService utilService;
	private Map<String, Integer> columnLenghts;
	private Map<Long, UsuarioDependencia> usuarioDependenciasMap;
	private boolean confirmacion = false;

	public UsuariosMantenimiento(Window quienLlama, Permiso permiso) {
		usuarioServicio = Injector.obtenerServicio(UsuarioServicio.class);
		grupoServicio = Injector.obtenerServicio(GrupoServicio.class);
		usuarioAccesoServicio = Injector
				.obtenerServicio(UsuarioAccesoServicio.class);
		usuarioDependenciaServicio = Injector
				.obtenerServicio(UsuarioDependenciaServicio.class);
		dependenciaServicio = Injector
				.obtenerServicio(DependenciaServicio.class);
		utilService = Injector.obtenerServicio(UtilService.class);
		this.quienLlama = quienLlama;
		this.permiso = permiso;
		usuarioAccesosMap = new HashMap<Long, UsuarioAcceso>();
		usuarioDependenciasMap = new HashMap<Long, UsuarioDependencia>();
		buildMainLayout();
		setCompositionRoot(mainLayout);
		postBuid();
		resetearFormulario();
		getAllUsuarios();
	}

	private void postBuid() {
		lblTitulo.setContentMode(ContentMode.HTML);

		columnLenghts = utilService.getLengthColumns("usuario");
		this.btnNuevo.addClickListener((ClickListener) this);
		this.btnGuardar.addClickListener((ClickListener) this);
		this.btnCancelar.addClickListener((ClickListener) this);
		this.btnEliminar.addClickListener((ClickListener) this);
		this.btnBuscar.addClickListener((ClickListener) this);
		this.btnInicio.addClickListener((ClickListener) this);
		this.btnAtras.addClickListener((ClickListener) this);
		this.btnSiguiente.addClickListener((ClickListener) this);
		this.btnFin.addClickListener((ClickListener) this);
		this.btnImprimir.addClickListener((ClickListener) this);
		this.btnInicio.setStyleName(Reindeer.BUTTON_LINK);
		this.btnAtras.setStyleName(Reindeer.BUTTON_LINK);
		this.btnSiguiente.setStyleName(Reindeer.BUTTON_LINK);
		this.btnFin.setStyleName(Reindeer.BUTTON_LINK);
		this.btnBuscar.setStyleName("buscar");
		this.txtPaginaActual.setValue("1");

		this.txtPaginaActual.setId("paginaActual");
		this.txtBuscarNombres.setId("buscarNombres");
		this.txtBuscarUsuario.setId("buscarUsuario");
		this.txtClave.setId("clave");
		this.txtNombres.setId("nombres");
		this.txtUsuario.setId("usuario");
		this.btnCancelar.setId("cancelar");
		this.btnEliminar.setId("eliminar");
		this.btnGuardar.setId("guardar");
		this.btnNuevo.setId("nuevo");
		this.btnBuscar.setId("consultar");

		this.txtUsuario.setMaxLength(columnLenghts.get("usuario"));
		this.txtClave.setMaxLength(columnLenghts.get("contrasenha"));
		this.txtNombres.setMaxLength(columnLenghts.get("nombres"));
		this.txtUsuario.setTabIndex(1);
		this.txtNombres.setTabIndex(2);
		this.txtClave.setTabIndex(3);
		this.txtConfirClave.setTabIndex(4);
		this.tabGruposDependencias.setTabIndex(5);
		this.btnNuevo.setTabIndex(6);
		this.btnGuardar.setTabIndex(7);
		this.btnCancelar.setTabIndex(8);
		this.btnEliminar.setTabIndex(9);
		this.btnImprimir.setTabIndex(10);
		this.txtBuscarNombres.setTabIndex(12);
		this.txtBuscarUsuario.setTabIndex(11);
		this.tblUsuarios.setTabIndex(13);
		this.btnInicio.setTabIndex(14);
		this.btnSiguiente.setTabIndex(17);
		this.btnAtras.setTabIndex(15);
		this.btnFin.setTabIndex(18);
		this.txtPaginaActual.setTabIndex(16);
		IndexedContainer container = new IndexedContainer();
		container.addContainerProperty("id", Long.class, null);
		container.addContainerProperty("item", Long.class, null);
		container.addContainerProperty("usuario", String.class, null);
		container.addContainerProperty("nombres", String.class, null);

		tblUsuarios.setContainerDataSource(container);
		tblUsuarios.setVisibleColumns(new Object[] { "item", "usuario",
				"nombres" });
		tblUsuarios.setColumnWidth("item", 25);
		tblUsuarios.setColumnWidth("usuario", 100);
		tblUsuarios.setColumnWidth("nombres", 160);

		tblUsuarios.setColumnHeader("item", "Item");
		tblUsuarios.setColumnHeader("usuario", "Usuario");
		tblUsuarios.setColumnHeader("nombres", "Nombres");
		tblUsuarios.setSelectable(true);
		tblUsuarios.setImmediate(true);

		this.btnImprimir.setId("imprimir");
		SigeUtil.validarBotones(permiso, btnNuevo, btnEliminar, btnBuscar,
				btnCancelar, btnGuardar, btnImprimir);
		txtBuscarNombres.setVisible(permiso.getConsultar());
		txtBuscarUsuario.setVisible(permiso.getConsultar());
		this.txtPaginaActual.setImmediate(true);
		this.tblUsuarios
				.addValueChangeListener(new Property.ValueChangeListener() {
					private static final long serialVersionUID = 1L;

					public void valueChange(ValueChangeEvent event) {
						Item item = tblUsuarios.getItem(tblUsuarios.getValue());
						if (item != null) {
							resetearGrupos();
							resetearDependencias();
							btnGuardar.setCaption("Actualizar");
							btnEliminar.setEnabled(true);
							btnNuevo.setEnabled(true);
							flagEsNuevo = false;
							btnGuardar.setVisible(permiso.getModificar());
							btnGuardar.setEnabled(true);
							btnCancelar.setVisible(permiso.getModificar());
							btnCancelar.setEnabled(true);
							desactivarCampos(permiso.getModificar());
							getUsuario(new Long(item.getItemProperty("id").getValue().toString()));
							txtUsuario.setEnabled(false);
							tblUsuarios.unselect(tblUsuarios.getValue());
						}
					}
				});

		this.txtBuscarUsuario.setImmediate(true);
		this.txtBuscarUsuario.addTextChangeListener(new TextChangeListener() {

			@Override
			public void textChange(TextChangeEvent event) {
				// TODO Auto-generated method stub
				txtPaginaActual.setValue("1");
				txtBuscarUsuario.setValue(event.getText());
				getAllUsuarios();
			}
		});

		this.txtBuscarNombres.setImmediate(true);
		this.txtBuscarNombres.addTextChangeListener(new TextChangeListener() {

			@Override
			public void textChange(TextChangeEvent event) {
				// TODO Auto-generated method stub
				txtPaginaActual.setValue("1");
				txtBuscarNombres.setValue(event.getText());
				getAllUsuarios();
			}
		});

		this.txtPaginaActual.addShortcutListener(new ShortcutListener("",
				KeyCode.ENTER, null) {
			private static final long serialVersionUID = 1L;

			@Override
			public void handleAction(Object sender, Object target) {
				if (target instanceof TextField
						&& ((TextField) target).getId().equals("paginaActual")) {
					Long paginaActual = null;
					try {
						paginaActual = Long.parseLong(txtPaginaActual
								.getValue().toString());
					} catch (Exception exception) {
						paginaActual = 1L;
						Notification notificacion = new Notification(
								"Mensaje de error",
								"<br/>Debe Ingresar un nÃºmero");
						notificacion.setDelayMsec(10000);
						notificacion
								.setPosition(Notification.POSITION_CENTERED_TOP);
						UI.getCurrent().showNotification(notificacion);
					}
					txtPaginaActual.setValue(paginaActual.toString());
					getAllUsuarios();
				}
			}
		});

		IndexedContainer containe = new IndexedContainer();
		containe.addContainerProperty("grupo", CheckBox.class, null);
		treeGrupos.setColumnHeader("grupo", "");
		treeGrupos.setStyleName("grupos");
		treeGrupos.setContainerDataSource(containe);
		List<Grupo> grupos = grupoServicio.obtenerTodos();
		grups = new HashMap<Long, Grupo>();
		for (Grupo grupo : grupos) {
			grups.put(grupo.getId(), grupo);
			treeGrupos.addItem(
					new Object[] { new CheckBox(grupo.getDescripcion()) },
					grupo.getId());
		}
		treeGrupos.setPageLength(treeGrupos.size());

		IndexedContainer contain = new IndexedContainer();
		contain.addContainerProperty("dependencia", CheckBox.class, null);
		treeDependencias.setColumnHeader("dependencia", "");
		treeDependencias.setStyleName("grupos");
		treeDependencias.setContainerDataSource(contain);
		List<Dependencia> dependencias = dependenciaServicio.obtenerTodos();
		this.dependencias = new HashMap<Long, Dependencia>();
		for (Dependencia dependencia : dependencias) {
			this.dependencias.put(dependencia.getId(), dependencia);
			treeDependencias.addItem(
					new Object[] { new CheckBox(dependencia.getNombre()) },
					dependencia.getId());
		}
		treeDependencias.setPageLength(treeDependencias.size());
	}

	@SuppressWarnings("unchecked")
	private void getAllUsuarios() {
		IndexedContainer container = (IndexedContainer) tblUsuarios
				.getContainerDataSource();
		container.removeAllItems();

		List<Usuario> usuariosListado = null;
		Long paginaActual = Long.parseLong(this.txtPaginaActual.getValue()
				.toString());
		Usuario usuarioBuscar = new Usuario();
		usuarioBuscar.setUsuario(this.txtBuscarUsuario.getValue().toString());
		usuarioBuscar.setNombres(this.txtBuscarNombres.getValue().toString());
		Busqueda busqueda = usuarioServicio.buscarPorUsuario(usuarioBuscar,
				paginaActual);
		usuariosListado = (List<Usuario>) busqueda.getRegistos();
		
		this.lblTotalPaginas.setValue(busqueda.getNumeroPaginas().toString());
		this.txtPaginaActual.setValue(busqueda.getPaginaActual().toString());

		Long numeroItem = (Long.parseLong(this.txtPaginaActual.getValue()
				.toString()) - 1) * Constantes.PAGINACION.USUARIO + 1;
		for (int i = 0; i < usuariosListado.size(); i++) {
			Item item = container.addItem(i);
			item.getItemProperty("id").setValue(usuariosListado.get(i).getId());
			item.getItemProperty("item").setValue(numeroItem++);
			item.getItemProperty("usuario").setValue(
					usuariosListado.get(i).getUsuario());
			item.getItemProperty("nombres").setValue(
					usuariosListado.get(i).getNombres());
		}
	}

	private void getUsuario(Long usuarioId) {
		usuario = usuarioServicio.obtener(usuarioId);
		this.txtUsuario.setValue(usuario.getUsuario().trim());
		this.txtClave.setValue(usuario.getContrasenha().trim());
		this.txtConfirClave.setValue(usuario.getContrasenha().trim());
		this.txtNombres.setValue(usuario.getNombres().trim());
		this.claveEncritada = usuario.getContrasenha().trim();
		usuarioAccesosMap.clear();
		usuarioAccesos = usuarioAccesoServicio.buscarPorCodUsuario(usuarioId,true);
		
		Long idGrupo = null;
		for (UsuarioAcceso usuarioAcceso : usuarioAccesos) {
			idGrupo = usuarioAccesoServicio.getCodigoGrupo(usuarioAcceso.getId());
			usuarioAccesosMap.put(idGrupo, usuarioAcceso);
			if (usuarioAcceso.getEstado()) {
				((CheckBox) treeGrupos.getItem(idGrupo).getItemProperty("grupo").getValue()).setValue(true);
			}
		}

		usuarioDependenciasMap.clear();
		usuarioDependencias = usuarioDependenciaServicio.buscarPorCodigoUsuario(usuarioId, true);

		for (UsuarioDependencia usuarioDependencia : usuarioDependencias) {
			usuarioDependenciasMap.put(usuarioDependencia.getDependencia().getId(), usuarioDependencia);
			if (usuarioDependencia.getEstado()) {
				if (treeDependencias.getItem(usuarioDependencia.getDependencia().getId()) != null) {
					((CheckBox) treeDependencias.getItem(usuarioDependencia.getDependencia().getId()).getItemProperty("dependencia").getValue()).setValue(true);
				} else {
					usuarioDependenciasMap.get(usuarioDependencia.getDependencia().getId()).setEstado(Boolean.FALSE);
					usuarioDependencia.setEstado(Boolean.FALSE);
					usuarioDependenciaServicio.actualizar(usuarioDependencia);
				}
			}
		}
	}

	private void desactivarCampos(boolean estado) {
		txtClave.setEnabled(estado);
		txtNombres.setEnabled(estado);
		txtUsuario.setEnabled(estado);
		txtConfirClave.setEnabled(estado);
		tabGruposDependencias.setEnabled(estado);
	}

	private void resetearFormulario() {
		this.flagEsNuevo = false;
		this.btnNuevo.setEnabled(true);
		this.btnCancelar.setEnabled(false);
		this.btnGuardar.setEnabled(false);
		this.claveEncritada = "";
		desactivarCampos(false);
		resetearGrupos();
		resetearDependencias();
	}

	private void resetearGrupos() {
		for (Object id : treeGrupos.getItemIds()) {
			((CheckBox) treeGrupos.getItem(id).getItemProperty("grupo")
					.getValue()).setValue(false);
		}
		this.btnEliminar.setEnabled(false);
		this.txtUsuario.setValue("");
		this.txtClave.setValue("");
		this.txtNombres.setValue("");
		this.txtConfirClave.setValue("");
	}

	private void resetearDependencias() {
		for (Object id : treeDependencias.getItemIds()) {
			((CheckBox) treeDependencias.getItem(id)
					.getItemProperty("dependencia").getValue()).setValue(false);
		}
	}

	private void NuevoRegistro() {
		usuario = new Usuario();
		this.flagEsNuevo = true;
		this.btnCancelar.setVisible(permiso.getNuevo());
		this.btnCancelar.setEnabled(true);
		this.btnGuardar.setCaption("Guardar");
		this.btnGuardar.setVisible(permiso.getNuevo());
		this.btnGuardar.setEnabled(true);

		this.btnNuevo.setEnabled(false);
		desactivarCampos(permiso.getNuevo());
		resetearGrupos();
		resetearDependencias();
	}

	private Boolean validarClave() {
		if (claveEncritada.equals(this.txtClave.getValue().trim())
				&& claveEncritada.equals(this.txtConfirClave.getValue().trim())) {
			return true;
		} else {
			return this.txtClave.getValue().equals(
					this.txtConfirClave.getValue());
		}
	}

	public void obtenerMotivo(String motivo, Boolean confirmacion,
			Integer tipoOperacion) {
		if (confirmacion) {
			usuario.setMotivoModificacion(motivo);
			this.confirmacion = true;
			if (tipoOperacion.equals(Constantes.TIPO_OPERACION.MODIFICACION)) {
				btnGuardar.click();
			} else {
				btnEliminar.click();
			}
			this.confirmacion = false;
		}
	}

	@Override
	public void buttonClick(ClickEvent event) {
		if (event.getSource() == this.btnNuevo) {
			NuevoRegistro();
			this.txtUsuario.focus();
		} else {
			if (event.getSource() == this.btnGuardar) {
				if (SigeUtil.validarCamposTexto(txtNombres, txtUsuario)
						&& txtClave.getValue().toString().length() > 0) {
					if (!validarClave()) {
						Notificacion.show(new Notificacion(
								"Las contraseñas no coinciden",
								Constantes.MENSAJE.TYPE_ERROR));
						return;
					}
					usuario.setUsuario(this.txtUsuario.getValue().toString());
					usuario.setContrasenha(this.txtClave.getValue().toString());
					usuario.setNombres(this.txtNombres.getValue().toString());
					usuarioAccesos = new ArrayList<UsuarioAcceso>();
					usuarioDependencias = new ArrayList<UsuarioDependencia>();
					UsuarioAcceso usuarioAcceso;
					UsuarioDependencia usuarioDependencia;
					if (this.flagEsNuevo) {
						if (!usuarioServicio.validarDuplicado(usuario)) {
							Notificacion.show(new Notificacion(
									"El usuario ya existe",
									Constantes.MENSAJE.TYPE_ERROR));
							return;
						}
						usuarioServicio.crear(usuario);
						for (Object id : treeGrupos.getItemIds()) {
							if (((CheckBox) treeGrupos.getItem(id)
									.getItemProperty("grupo").getValue())
									.getValue() == Boolean.TRUE) {
								usuarioAcceso = new UsuarioAcceso();
								usuarioAcceso.setGrupo(grups.get(id));
								usuarioAcceso.setUsuario(usuario);
								usuarioAccesos.add(usuarioAcceso);
							}
						}
						for (Object id : treeDependencias.getItemIds()) {
							if (((CheckBox) treeDependencias.getItem(id)
									.getItemProperty("dependencia").getValue())
									.getValue() == Boolean.TRUE) {
								usuarioDependencia = new UsuarioDependencia();
								usuarioDependencia.setUsuario(usuario);
								usuarioDependencia.setDependencia(dependencias
										.get(id));
								usuarioDependencias.add(usuarioDependencia);
							}
						}
						Notificacion.show(new Notificacion(
								"Se guardo correctamente el usuario",
								Constantes.MENSAJE.TYPE_SUCCES));
					} else {
						if (!claveEncritada.equals(this.txtClave.getValue()
								.trim())) {
							usuario.setContrasenha(DigestUtils.sha512Hex(
									usuario.getContrasenha()).substring(0, 16));
						}
						if (!confirmacion) {
							Window ventana = SigeUtil.generarBuscador(
									new Window(), "INGRESAR MOTIVO", "360",
									"260");
							ventana.setContent(new PanelMotivoObservacion(
									ventana, this,
									Constantes.TIPO_OPERACION.MODIFICACION,
									(columnLenghts.get("motivomodifica"))));
							UI.getCurrent().addWindow(ventana);
							return;
						}

						usuarioServicio.actualizar(usuario);
						boolean value;
						for (Object id : treeGrupos.getItemIds()) {
							value = (Boolean) ((CheckBox) treeGrupos
									.getItem(id).getItemProperty("grupo")
									.getValue()).getValue();
							if (usuarioAccesosMap.get(id) != null) {
								usuarioAcceso = usuarioAccesosMap.get(id);
								if (value != usuarioAcceso.getEstado()) {
									usuarioAcceso.setEstado(value);
									usuarioAccesoServicio
											.actualizar(usuarioAcceso);
								}
							} else if (usuarioAccesosMap.get(id) == null
									&& value) {
								usuarioAcceso = new UsuarioAcceso();
								usuarioAcceso.setGrupo(grups.get(id));
								usuarioAcceso.setUsuario(usuario);
								usuarioAccesos.add(usuarioAcceso);
							}
						}
						for (Object id : treeDependencias.getItemIds()) {
							value = (Boolean) ((CheckBox) treeDependencias
									.getItem(id).getItemProperty("dependencia")
									.getValue()).getValue();
							if (usuarioDependenciasMap.get(id) != null) {
								usuarioDependencia = usuarioDependenciasMap
										.get(id);
								if (value != usuarioDependencia.getEstado()) {
									usuarioDependencia.setEstado(value);
									usuarioDependenciaServicio
											.actualizar(usuarioDependencia);
								}
							} else if (usuarioDependenciasMap.get(id) == null
									&& value) {
								usuarioDependencia = new UsuarioDependencia();
								usuarioDependencia.setUsuario(usuario);
								usuarioDependencia.setDependencia(dependencias
										.get(id));
								usuarioDependencias.add(usuarioDependencia);
							}
						}
						Notificacion.show(new Notificacion(
								"Se actualizo correctamente el usuario",
								Constantes.MENSAJE.TYPE_SUCCES));
					}
					usuarioDependenciaServicio.grabarTodos(usuarioDependencias);
					usuarioAccesoServicio.grabarTodos(usuarioAccesos);
					resetearFormulario();
					getAllUsuarios();
				} else {
					Notificacion.show(new Notificacion(
							"Debe llenar todos los campos",
							Constantes.MENSAJE.TYPE_ERROR));
				}
			} else {
				if (event.getSource() == this.btnCancelar) {
					resetearFormulario();
				} else {
					if (event.getSource() == this.btnBuscar) {
						this.txtPaginaActual.setValue("1");
						getAllUsuarios();
					} else {
						if (event.getSource() == this.btnEliminar) {
							if (!confirmacion) {
								Window ventana = SigeUtil.generarBuscador(
										new Window(), "INGRESAR MOTIVO", "360",
										"260");
								ventana.setContent(new PanelMotivoObservacion(
										ventana, this,
										Constantes.TIPO_OPERACION.ELIMINACION,
										(columnLenghts.get("motivomodifica"))));
								UI.getCurrent().addWindow(ventana);
								return;
							}

							ConfirmDialog.show(UI.getCurrent(), "Confirmación",
									"¿Desea elminar el usuario?", "Aceptar",
									"Cancelar", new ConfirmDialog.Listener() {
										private static final long serialVersionUID = 1L;

										public void onClose(ConfirmDialog dialog) {
											if (dialog.isConfirmed()) {
												usuarioServicio
														.eliminiarUsuario(usuario);
												resetearFormulario();
												getAllUsuarios();
											}
										}
									});
						} else {
							if (event.getSource() == this.btnSiguiente) {
								Long paginaActual = Long
										.parseLong(this.txtPaginaActual
												.getValue().toString()) + 1;
								if (paginaActual <= Long
										.parseLong(this.lblTotalPaginas
												.getValue().toString())) {
									this.txtPaginaActual.setValue(paginaActual
											.toString());
								}
								getAllUsuarios();
							} else {
								if (event.getSource() == this.btnAtras) {
									Long paginaActual = Long
											.parseLong(this.txtPaginaActual
													.getValue().toString()) - 1;
									if (paginaActual >= 1) {
										this.txtPaginaActual
												.setValue(paginaActual
														.toString());
									}
									getAllUsuarios();
								} else {
									if (event.getSource() == this.btnInicio) {
										this.txtPaginaActual.setValue("1");
										getAllUsuarios();
									} else {
										if (event.getSource() == this.btnFin) {
											this.txtPaginaActual
													.setValue(this.lblTotalPaginas
															.getValue());
											getAllUsuarios();
										} else if (event.getSource() == this.btnImprimir) {
											Window ventana = SigeUtil
													.generarBuscador(
															new Window(),
															"IMPRIMIR",
															"800px", "550px");
											Map<String, Object> parametros = new HashMap<String, Object>();
											parametros.put("usuario",this.txtBuscarUsuario
															.getValue()
															.toUpperCase());
											parametros.put("nombres",
													this.txtBuscarNombres
															.getValue()
															.toUpperCase());
											ventana.setContent(new PDFVizualizador(
													this, permiso, parametros,
													null, "UsuariosImprimir",
													null));
											UI.getCurrent().addWindow(ventana);
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("710px");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("710px");
		setHeight("100.0%");

		// tblUsuarios
		tblUsuarios = new Table();
		tblUsuarios.setImmediate(false);
		tblUsuarios.setWidth("327px");
		tblUsuarios.setHeight("206px");
		mainLayout.addComponent(tblUsuarios, "top:58.0px;left:20.0px;");

		// txtBuscarUsuario
		txtBuscarUsuario = new TextField();
		txtBuscarUsuario.setImmediate(false);
		txtBuscarUsuario.setWidth("107px");
		txtBuscarUsuario.setHeight("-1px");
		mainLayout.addComponent(txtBuscarUsuario, "top:34.0px;left:58.0px;");

		// txtBuscarNombres
		txtBuscarNombres = new TextField();
		txtBuscarNombres.setImmediate(false);
		txtBuscarNombres.setWidth("156px");
		txtBuscarNombres.setHeight("-1px");
		mainLayout.addComponent(txtBuscarNombres, "top:34.0px;left:165.0px;");

		// btnBuscar
		btnBuscar = new Boton();
		btnBuscar.setIcon(new ThemeResource("images/botones/find.png"));
		btnBuscar.setImmediate(false);
		btnBuscar.setWidth("28px");
		btnBuscar.setHeight("24px");
		mainLayout.addComponent(btnBuscar, "top:34.0px;left:321.0px;");

		// lblTitulo
		lblTitulo = new Label();
		lblTitulo.setImmediate(false);
		lblTitulo.setWidth("-1px");
		lblTitulo.setHeight("-1px");
		lblTitulo.setValue("<b>Datos de Usuario</b>");
		mainLayout.addComponent(lblTitulo, "top:10.0px;left:449.0px;");

		// lblUsuario
		lblUsuario = new Label();
		lblUsuario.setImmediate(false);
		lblUsuario.setWidth("-1px");
		lblUsuario.setHeight("-1px");
		lblUsuario.setValue("Usuario");
		mainLayout.addComponent(lblUsuario, "top:40.0px;left:359.0px;");

		// lblNombres
		lblNombres = new Label();
		lblNombres.setImmediate(false);
		lblNombres.setWidth("-1px");
		lblNombres.setHeight("-1px");
		lblNombres.setValue("Nombres");
		mainLayout.addComponent(lblNombres, "top:69.0px;left:359.0px;");

		// lblClave
		lblClave = new Label();
		lblClave.setImmediate(false);
		lblClave.setWidth("-1px");
		lblClave.setHeight("-1px");
		lblClave.setValue("Clave");
		mainLayout.addComponent(lblClave, "top:98.0px;left:359.0px;");

		// txtUsuario
		txtUsuario = new TextField();
		txtUsuario.setImmediate(false);
		txtUsuario.setWidth("240px");
		txtUsuario.setHeight("-1px");
		mainLayout.addComponent(txtUsuario, "top:37.0px;left:420.0px;");

		// txtNombres
		txtNombres = new TextField();
		txtNombres.setImmediate(false);
		txtNombres.setWidth("280px");
		txtNombres.setHeight("-1px");
		mainLayout.addComponent(txtNombres, "top:67.0px;left:420.0px;");

		// txtClave
		txtClave = new PasswordField();
		txtClave.setImmediate(false);
		txtClave.setWidth("240px");
		txtClave.setHeight("-1px");
		mainLayout.addComponent(txtClave, "top:98.0px;left:420.0px;");

		// btnNuevo
		btnNuevo = new Button();
		btnNuevo.setCaption("Nuevo");
		btnNuevo.setIcon(new ThemeResource("images/botones/new.png"));
		btnNuevo.setImmediate(true);
		btnNuevo.setWidth("110px");
		btnNuevo.setHeight("-1px");
		mainLayout.addComponent(btnNuevo, "top:280.0px;left:360.0px;");

		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setIcon(new ThemeResource("images/botones/save.png"));
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("110px");
		btnGuardar.setHeight("-1px");
		mainLayout.addComponent(btnGuardar, "top:280.0px;left:476.0px;");

		// btnEliminar
		btnEliminar = new Button();
		btnEliminar.setCaption("Eliminar");
		btnEliminar.setIcon(new ThemeResource("images/botones/delete.png"));
		btnEliminar.setImmediate(true);
		btnEliminar.setWidth("110px");
		btnEliminar.setHeight("-1px");
		mainLayout.addComponent(btnEliminar, "top:310.0px;left:360.0px;");

		// btnCancelar
		btnCancelar = new Button();
		btnCancelar.setCaption("Cancelar");
		btnCancelar.setIcon(new ThemeResource("images/botones/undo.png"));
		btnCancelar.setImmediate(true);
		btnCancelar.setWidth("110px");
		btnCancelar.setHeight("-1px");
		mainLayout.addComponent(btnCancelar, "top:280.0px;left:590.0px;");

		// btnInicio
		btnInicio = new Boton();
		btnInicio.setIcon(new ThemeResource("images/botones/start.png"));
		btnInicio.setImmediate(true);
		btnInicio.setWidth("30px");
		btnInicio.setHeight("-1px");
		mainLayout.addComponent(btnInicio, "top:270.0px;left:40.0px;");

		// btnAtras
		btnAtras = new Boton();
		btnAtras.setIcon(new ThemeResource("images/botones/previous.png"));
		btnAtras.setImmediate(true);
		btnAtras.setWidth("30px");
		btnAtras.setHeight("-1px");
		mainLayout.addComponent(btnAtras, "top:270.0px;left:70.0px;");

		// btnSiguiente
		btnSiguiente = new Boton();
		btnSiguiente.setIcon(new ThemeResource("images/botones/next.png"));
		btnSiguiente.setImmediate(true);
		btnSiguiente.setWidth("30px");
		btnSiguiente.setHeight("-1px");
		mainLayout.addComponent(btnSiguiente, "top:270.0px;left:259.0px;");

		// btnFin
		btnFin = new Boton();
		btnFin.setIcon(new ThemeResource("images/botones/final.png"));
		btnFin.setImmediate(true);
		btnFin.setWidth("30px");
		btnFin.setHeight("-1px");
		mainLayout.addComponent(btnFin, "top:270.0px;left:289.0px;");

		// lblPagina
		lblPagina = new Label();
		lblPagina.setImmediate(false);
		lblPagina.setWidth("-1px");
		lblPagina.setHeight("-1px");
		lblPagina.setValue("Página");
		mainLayout.addComponent(lblPagina, "top:274.0px;left:113.0px;");

		// txtPaginaActual
		txtPaginaActual = new NumberField();
		txtPaginaActual.setImmediate(true);
		txtPaginaActual.setWidth("37px");
		txtPaginaActual.setHeight("-1px");
		mainLayout.addComponent(txtPaginaActual, "top:270.0px;left:163.0px;");

		// lblSeparador
		lblSeparador = new Label();
		lblSeparador.setImmediate(false);
		lblSeparador.setWidth("-1px");
		lblSeparador.setHeight("-1px");
		lblSeparador.setValue("/");
		mainLayout.addComponent(lblSeparador, "top:274.0px;left:206.0px;");

		// lblTotalPaginas
		lblTotalPaginas = new Label();
		lblTotalPaginas.setImmediate(false);
		lblTotalPaginas.setWidth("-1px");
		lblTotalPaginas.setHeight("-1px");
		lblTotalPaginas.setValue("9999");
		mainLayout.addComponent(lblTotalPaginas, "top:274.0px;left:216.0px;");

		// btnImprimir
		btnImprimir = new Button();
		btnImprimir.setCaption("Imprimir");
		btnImprimir.setIcon(new ThemeResource("images/botones/print.png"));
		btnImprimir.setImmediate(true);
		btnImprimir.setWidth("110px");
		btnImprimir.setHeight("-1px");
		mainLayout.addComponent(btnImprimir, "top:310.0px;left:476.0px;");

		// tabGruposDependencias
		tabGruposDependencias = buildTabGruposDependencias();
		mainLayout.addComponent(tabGruposDependencias,
				"top:155.0px;left:359.0px;");

		// lblConfirmacion
		lblConfirmacion = new Label();
		lblConfirmacion.setImmediate(false);
		lblConfirmacion.setWidth("-1px");
		lblConfirmacion.setHeight("-1px");
		lblConfirmacion.setValue("Confirmar Clave");
		mainLayout.addComponent(lblConfirmacion, "top:125.0px;left:359.0px;");

		// txtConfirClave
		txtConfirClave = new PasswordField();
		txtConfirClave.setImmediate(false);
		txtConfirClave.setWidth("240px");
		txtConfirClave.setHeight("-1px");
		mainLayout.addComponent(txtConfirClave, "top:125.0px;left:460.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabGruposDependencias() {
		// common part: create layout
		tabGruposDependencias = new TabSheet();
		tabGruposDependencias.setImmediate(true);
		tabGruposDependencias.setWidth("341px");
		tabGruposDependencias.setHeight("120px");

		// treeGrupos
		treeGrupos = new TreeTable();
		treeGrupos.setImmediate(true);
		treeGrupos.setWidth("338px");
		treeGrupos.setHeight("85px");
		tabGruposDependencias.addTab(treeGrupos, "Grupo(s)", null);

		// treeDependencias
		treeDependencias = new TreeTable();
		treeDependencias.setImmediate(true);
		treeDependencias.setWidth("338px");
		treeDependencias.setHeight("86px");
		tabGruposDependencias.addTab(treeDependencias, "Dependencia(s)", null);

		return tabGruposDependencias;
	}

}
