package com.sige.gui;

import java.util.List;
import java.util.Map;

import com.sige.entidad.Via;
import com.sige.servicio.UtilService;
import com.sige.servicio.ViaServicio;
import com.sige.util.Boton;
import com.sige.util.Busqueda;
import com.sige.util.Constantes;
import com.sige.util.Injector;
import com.sige.util.TextField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.event.ShortcutListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.vaadin.ui.themes.Reindeer;

public class ViaBuscar extends CustomComponent implements ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnBuscar;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private Label lblTotalPaginas;
	@AutoGenerated
	private Label lblSeparador;
	@AutoGenerated
	private Label llblPagina;
	@AutoGenerated
	private TextField txtPaginaActual;
	@AutoGenerated
	private Boton btnFin;
	@AutoGenerated
	private Boton btnSiguiente;
	@AutoGenerated
	private Boton btnAtras;
	@AutoGenerated
	private Boton btnInicio;
	@AutoGenerated
	private Table tblVias;
	@AutoGenerated
	private Label lblNombre;
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	private ViaServicio viaServicio;
	private Window windowContiene;
	private CustomComponent quienLlama;
	private UtilService utilService;
	private Map<String, Integer> columnLenghts;

	public ViaBuscar(Window windowContiene, CustomComponent quienLlama) {
		utilService = Injector.obtenerServicio(UtilService.class);
		viaServicio = Injector.obtenerServicio(ViaServicio.class);
		this.windowContiene = windowContiene;
		this.quienLlama = quienLlama;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		postBuid();
		// TODO add user code here
		getAllVias();
	}

	private void postBuid() {
		columnLenghts = utilService.getLengthColumns("vias");
		txtNombre.setMaxLength(columnLenghts.get("nombre"));
		this.btnBuscar.addClickListener((ClickListener) this);
		this.btnInicio.addClickListener((ClickListener) this);
		this.btnAtras.addClickListener((ClickListener) this);
		this.btnSiguiente.addClickListener((ClickListener) this);
		this.btnFin.addClickListener((ClickListener) this);
		this.btnInicio.setStyleName(Reindeer.BUTTON_LINK);
		this.btnAtras.setStyleName(Reindeer.BUTTON_LINK);
		this.btnSiguiente.setStyleName(Reindeer.BUTTON_LINK);
		this.btnFin.setStyleName(Reindeer.BUTTON_LINK);
		this.txtPaginaActual.setValue("1");

		txtNombre.setTabIndex(1);
		btnBuscar.setTabIndex(2);
		tblVias.setTabIndex(3);
		btnInicio.setTabIndex(4);
		btnAtras.setTabIndex(5);
		txtPaginaActual.setTabIndex(6);
		btnSiguiente.setTabIndex(7);
		btnFin.setTabIndex(8);

		this.txtPaginaActual.setId("paginaActual");
		this.txtNombre.setId("buscarNombres");
		IndexedContainer container = new IndexedContainer();
		container.addContainerProperty("id", Long.class, null);
		container.addContainerProperty("item", Long.class, null);
		container.addContainerProperty("nombre", String.class, null);
		tblVias.setContainerDataSource(container);
		tblVias.setVisibleColumns(new Object[] { "item", "nombre" });
		tblVias.setColumnWidth("item", 25);
		tblVias.setColumnWidth("nombre", 310);

		tblVias.setColumnHeader("item", "Item");
		tblVias.setColumnHeader("nombre", "Nombre");
		tblVias.setSelectable(true);
		tblVias.setImmediate(true);

		this.txtPaginaActual.setImmediate(true);
		this.tblVias.addItemClickListener(new ItemClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void itemClick(ItemClickEvent event) {
				if (event.isDoubleClick()) {
					Item item = tblVias.getItem(event.getItemId());
					respuesta(new Long(item.getItemProperty("id").getValue()
							.toString()));
				}
			}
		});

		this.txtPaginaActual.addShortcutListener(new ShortcutListener("",
				KeyCode.ENTER, null) {
			private static final long serialVersionUID = 1L;

			@Override
			public void handleAction(Object sender, Object target) {
				if (target instanceof TextField
						&& ((TextField) target).getId().equals("paginaActual")) {
					Long paginaActual = null;
					try {
						paginaActual = Long.parseLong(txtPaginaActual
								.getValue().toString());
					} catch (Exception exception) {
						paginaActual = 1L;
					}
					txtPaginaActual.setValue(paginaActual.toString());
					getAllVias();
				}
			}
		});
		this.txtNombre.setImmediate(true);
		this.txtNombre.addTextChangeListener(new TextChangeListener() {

			private static final long serialVersionUID = 1L;

			@Override
			public void textChange(TextChangeEvent event) {
				// TODO Auto-generated method stub
				txtPaginaActual.setValue("1");
				txtNombre.setValue(event.getText());
				getAllVias();
			}
		});
	}

	@SuppressWarnings("unchecked")
	private void getAllVias() {
		IndexedContainer container = (IndexedContainer) tblVias
				.getContainerDataSource();
		container.removeAllItems();

		List<Via> viasListado = null;
		Long paginaActual = Long.parseLong(this.txtPaginaActual.getValue()
				.toString());
		Via viaBuscar = new Via();
		viaBuscar.setNombre(this.txtNombre.getValue().toString());
		Busqueda busqueda = viaServicio.buscarPorVia(viaBuscar, paginaActual);
		viasListado = (List<Via>) busqueda.getRegistos();
		this.lblTotalPaginas.setValue(busqueda.getNumeroPaginas().toString());
		this.txtPaginaActual.setValue(busqueda.getPaginaActual().toString());

		Long numeroItem = (Long.parseLong(this.txtPaginaActual.getValue()
				.toString()) - 1) * Constantes.PAGINACION.VIA + 1;
		for (int i = 0; i < viasListado.size(); i++) {
			Item item = container.addItem(i);
			item.getItemProperty("id").setValue(viasListado.get(i).getId());
			item.getItemProperty("item").setValue(numeroItem++);
			item.getItemProperty("nombre").setValue(
					viasListado.get(i).getNombre());
		}
	}

	private void respuesta(Long viaId) {
		if (quienLlama instanceof PersonaMantenimiento) {
			PersonaMantenimiento panel = (PersonaMantenimiento) quienLlama;
			panel.getViaSeleccionada(viaId);
		} else if (quienLlama instanceof PersonaBuscar) {
			PersonaBuscar panel = (PersonaBuscar) quienLlama;
			panel.getViaSeleccionada(viaId);
		}
		UI.getCurrent().removeWindow(windowContiene);
	}

	@Override
	public void buttonClick(ClickEvent event) {
		if (event.getSource() == this.btnBuscar) {
			this.txtPaginaActual.setValue("1");
			getAllVias();
		} else {
			if (event.getSource() == this.btnSiguiente) {
				Long paginaActual = Long.parseLong(this.txtPaginaActual
						.getValue().toString()) + 1;
				if (paginaActual <= Long.parseLong(this.lblTotalPaginas
						.getValue().toString())) {
					this.txtPaginaActual.setValue(paginaActual.toString());
				}
				getAllVias();
			} else {
				if (event.getSource() == this.btnAtras) {
					Long paginaActual = Long.parseLong(this.txtPaginaActual
							.getValue().toString()) - 1;
					if (paginaActual >= 1) {
						this.txtPaginaActual.setValue(paginaActual.toString());
					}
					getAllVias();
				} else {
					if (event.getSource() == this.btnInicio) {
						this.txtPaginaActual.setValue("1");
						getAllVias();
					} else {
						if (event.getSource() == this.btnFin) {
							this.txtPaginaActual.setValue(this.lblTotalPaginas
									.getValue());
							getAllVias();
						}
					}
				}
			}
		}

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// lblNombre
		lblNombre = new Label();
		lblNombre.setImmediate(false);
		lblNombre.setWidth("-1px");
		lblNombre.setHeight("-1px");
		lblNombre.setValue("Nombre");
		mainLayout.addComponent(lblNombre, "top:20.0px;left:27.0px;");

		// tblVias
		tblVias = new Table();
		tblVias.setImmediate(false);
		tblVias.setWidth("420px");
		tblVias.setHeight("220px");
		mainLayout.addComponent(tblVias, "top:50.0px;left:20.0px;");

		// btnInicio
		btnInicio = new Boton();
		btnInicio.setIcon(new ThemeResource("images/botones/start.png"));
		btnInicio.setImmediate(false);
		btnInicio.setWidth("28px");
		btnInicio.setHeight("24px");
		mainLayout.addComponent(btnInicio, "top:280.0px;left:60.0px;");

		// btnAtras
		btnAtras = new Boton();
		btnAtras.setIcon(new ThemeResource("images/botones/previous.png"));
		btnAtras.setImmediate(false);
		btnAtras.setWidth("28px");
		btnAtras.setHeight("24px");
		mainLayout.addComponent(btnAtras, "top:280.0px;left:88.0px;");

		// btnSiguiente
		btnSiguiente = new Boton();
		btnSiguiente.setIcon(new ThemeResource("images/botones/next.png"));
		btnSiguiente.setImmediate(false);
		btnSiguiente.setWidth("28px");
		btnSiguiente.setHeight("24px");
		mainLayout.addComponent(btnSiguiente, "top:280.0px;left:344.0px;");

		// btnFin
		btnFin = new Boton();
		btnFin.setIcon(new ThemeResource("images/botones/final.png"));
		btnFin.setImmediate(false);
		btnFin.setWidth("28px");
		btnFin.setHeight("24px");
		mainLayout.addComponent(btnFin, "top:280.0px;left:372.0px;");

		// txtPaginaActual
		txtPaginaActual = new TextField();
		txtPaginaActual.setImmediate(false);
		txtPaginaActual.setWidth("37px");
		txtPaginaActual.setHeight("-1px");
		mainLayout.addComponent(txtPaginaActual, "top:280.0px;left:211.0px;");

		// llblPagina
		llblPagina = new Label();
		llblPagina.setImmediate(false);
		llblPagina.setWidth("-1px");
		llblPagina.setHeight("-1px");
		llblPagina.setValue("Página");
		mainLayout.addComponent(llblPagina, "top:282.0px;left:162.0px;");

		// lblSeparador
		lblSeparador = new Label();
		lblSeparador.setImmediate(false);
		lblSeparador.setWidth("-1px");
		lblSeparador.setHeight("-1px");
		lblSeparador.setValue("/");
		mainLayout.addComponent(lblSeparador, "top:282.0px;left:258.0px;");

		// lblTotalPaginas
		lblTotalPaginas = new Label();
		lblTotalPaginas.setImmediate(false);
		lblTotalPaginas.setWidth("-1px");
		lblTotalPaginas.setHeight("-1px");
		lblTotalPaginas.setValue("9999");
		mainLayout.addComponent(lblTotalPaginas, "top:282.0px;left:271.0px;");

		// txtNombre
		txtNombre = new TextField();
		txtNombre.setImmediate(false);
		txtNombre.setWidth("260px");
		txtNombre.setHeight("-1px");
		mainLayout.addComponent(txtNombre, "top:18.0px;left:77.0px;");

		// btnBuscar
		btnBuscar = new Button();
		btnBuscar.setCaption("Buscar");
		btnBuscar.setIcon(new ThemeResource("images/botones/find.png"));
		btnBuscar.setImmediate(true);
		btnBuscar.setWidth("100px");
		btnBuscar.setHeight("-1px");
		mainLayout.addComponent(btnBuscar, "top:18.0px;left:340.0px;");

		return mainLayout;
	}

}
